### ISSUE TITLE
Inverse Uses

### ISSUE THREAD

**Issue by uboslinux** [google/physical-web#161]
Define how the Thing can notify the user, after the user has discovered and interacted with the Thing and given permission for one-time, or repeated notification. This seems to be a general-enough pattern to figure this out once and apply everywhere.

More details blogged here: http://upon2020.com/blog/2014/10/another-inverse-physicalweb-use-case/ and referenced here per suggestion of @scottjenson in the hope that others can chime in.

**Comment by cco3** [comment]
This issue seems a bit dated.  If there's still anything to discuss, we can reopen.
