### ISSUE TITLE
URL input improvements

### ISSUE THREAD

**Issue by schilit** [google/physical-web#179]
***Problem***

Users must enter a scheme in the Config Activity (one of "http://" "https://" or "urn:uuid:").

If no scheme is entered a default is prepended ("http://"), but entry for other schemes is burdensome.

***Recommended Solution***

Google Analytics and other sites that require URL input use a drop down selector:
![URL Chooser](https://lh6.googleusercontent.com/A2b1dA7lxcXUJL3djZI_AU7EeSMkRC9FfL6Mx8F_E0rgcSjnCv0l12jK1VFavn4agcgkiHyBrFo=w2560-h1238)

The Config Activity can use a [Spinner](http://developer.android.com/guide/topics/ui/controls/spinner.html) in Android: 
![Spinner](https://cloud.githubusercontent.com/assets/8324877/4965692/d3134744-6790-11e4-8713-29f4d52b23ff.png)

**Comment by scottjenson** [comment]
This is well covered in the URI Beacon app
