### ISSUE TITLE
Move physical-web/firmware/tessel  to uribeacon/beacons/tessel 

### ISSUE THREAD

**Issue by schilit** [google/physical-web#184]
@MrNice 

We now have a repo dedicated to uribeacon and we're moving firmware files. Could you send a merge request with a copy/delete:

from: github.com/google/physical-web//firmware/tessel
to: github.com/google/uribeacon/beacons/tessel

If you don't want to bother let me know and I'd be happy to do this.

Thanks!

**Comment by mbrevda** [comment]
Where can I find this code now that the uribeacon repo was (mostly) moved?

**Comment by dermike** [comment]
@mbrevda https://github.com/google/uribeacon/tree/uribeacon-final/beacons/tessel

Just change 0xD8 to 0xAA
And 0x00 flag to 0x10

**Comment by mbrevda** [comment]
Thanks!

**Comment by scottjenson** [comment]
Thank you @dermike ! I want to make sure we're not creating confusion here. If it would help for to have more updated images that need into the Eddystone repo, please let me know and we'll take care of it. I thought we'd moved the primary ones over but apparently we missed one. Any others?
