### ISSUE TITLE
Use UriBeacon.RegionResolver comparator (for sorting) once it is implemented in UriBeacon

### ISSUE THREAD

**Issue by matthewsibigtroth** [google/physical-web#228]
Currently we use the same comparator in both NearbyBeaconsFragment and UriBeaconDiscoveryService. This could be abstracted and live in UriBeacon and hence allow for less code repetition.

**Comment by scottjenson** [comment]
As we're moving towards proxy sorting, with signal strength being honored by the proxy server, this is no longer needed.
