### ISSUE TITLE
Implement UriBeacon ScanController for service scanning

### ISSUE THREAD

**Issue by matthewsibigtroth** [google/physical-web#244]
Currently the UriBeaconDiscoveryService in the android app is scanning as follows:
When the service starts up (or restarts when either the app is exited or if the screen was just turned back on) we run a brief low-latency scan and then stop that scan and start low-power scanning.

This functionality and methodology currently exists in UriBeacon's ScanController. We can use that class instead of the above patch.

**Comment by scottjenson** [comment]
As we are only scanning when the screen is on, we don't see much power drain at this point so we're pushing this off for now.
