### ISSUE TITLE
PhoneGap support

### ISSUE THREAD

**Issue by umaar** [google/physical-web#256]
Can you provide a PhoneGap build? This is so web developers can write in JavaScript and deploy on a device.

**Comment by dinhviethoa** [comment]
Hi, we don't have support for PhoneGap for now.

**Comment by umaar** [comment]
Is this on the roadmap? The intention was a tool/technology which would make it easier to write JavaScript code which scans for beacons. It's great that we can already do this with node.js for example, but that's only for desktop.

**Comment by scottjenson** [comment]
Our goal is to get the scanner into all phones (as a background process)
that way everyone can see everything. That is our core goal and we're
focusing all of our energy on that. A phonegap build would be useful to a
crowd that wants to continue down the 'every beacon type gets it's own app"
approach that iBeacon is using. We're trying to break out of that cycle.

**Comment by umaar** [comment]
Thanks for explaining, feel free to close this issue.

**Comment by scottjenson** [comment]
You're welcome, thanks for raising the issue as it's helpful to get these core principles more clearly explained.

**Comment by scottjenson** [comment]
It's possible but as I mentioned before, it's supporting a direction that
we don't feel is worth our effort (Please see previous post) We *love* the
PhoneGap project but feel that we need to focus our energies on getting
this background process into all phones so the very need for any native app
(phonegap or full native) completely goes away.

**Comment by don** [comment]
For people that want to do this with PhoneGap, use the [BLE plugin](https://github.com/don/cordova-plugin-ble-central) to scan for beacons and get the advertising data from beacons. Then use JavaScript to parse the data. (If you build a JavaScript URL decoder, send a pull request to [node-uri-beacon](https://github.com/don/node-uri-beacon).)
