### ISSUE TITLE
web-service should fetch json-ld documents that are linked in the href attribute

### ISSUE THREAD

**Issue by kartben** [google/physical-web#257]
At the moment only the JSON documents that are inlined in a `<script type="application/ld+json">` element's text() are appended to the siteinfo. If the URL of a JSON-LD document is specified in the href attribute it should probably be fetched too.

**Comment by dinhviethoa** [comment]
Are there reasons why you wouldn't include the JSON documents inline?
I'd like to understand the use case before rushing into implementation.

Meanwhile, is it a good workaround for you to include the JSON inline?

**Comment by kartben** [comment]
My thought process here is that I spent about 15 minutes looking for an existing Web page that would contain an inline JSON-LD document so as I could test how it would be parsed by the proxy, and I litterally couldn't find any, even when trying relatively hard to ask the Google. I understand that it is not a problem for people who will craft their own webpages, but I think many people are also interested in linking to existing web pages, that may have href'd JSON-LD docs.

The use case I had in mind is I think quite common, and associating URLs like http://live.dbpedia.org/page/Mona_Lisa etc to beacons in a museum so as to allow to easily get the metadata (width, height, painter, etc) associated to each painting.
I think it's a quite common use case to link to existing JSON-LD documents from a web page, especially JSON-LD documents from dbpedia or similar.

**Comment by scottjenson** [comment]
The goal of the Physical Web is to be as thin as possible: we literally
want to get the user to the a web page as easily as possible. Living inside
our picker is an interesting experiment but it creates a tension between
the web browser and the beacon browser.

I appreciate that there are cases (like museums) where you want to browse a
range of related beacons but we feel that should be put into a web page and
now the beacon browser. Once we have BLE JS support in the browser, that
can be written fairly easily. Once you open the museum page, *it* can then
find/get metadata (in many ways, not just JSON+LD)and provide a museum
appropriate way to view/browser/scan the exhibits nearby

Scott

**Comment by scottjenson** [comment]
Close due to lack of comments, but willing to reopen if necessary
