### ISSUE TITLE
Offline workflow

### ISSUE THREAD

**Issue by blainekasten** [google/physical-web#260]
How is this supposed to work if the users device doeant have a connection? This could happeb for several reasons in modern cases. A big one being network overload in an area. Say on football game days when the area is overrun with requests it seems none of these physical web devices would work then. 

Discuss.

**Comment by schilit** [comment]
Caching at the client would be a start. But eventually you would probably
want to visit the web page, for example, to order a hot dog from your seat
at that football game.

**Comment by scottjenson** [comment]
We get this question a quite a bit. But it's a bit like asking "how could I
use Twitter?" or "How could I get email?" if you didn't have a connection.

If you don't have a connection, many of your most valuable services are no
longer available to you. As we are based on the web, you pretty much are
going to need a connection.

Scott

**Comment by blainekasten** [comment]
So, I understand that is the obvious answer. But the thing is, this proposal seems to have an end goal to remove the current interface to machines and change the way we interact with the world.

For example, currently if you walk up to a soda machine to get soda, you put in money and click the button. With the above understanding of the project, it seems as if the machine would not have a normal click interface or anything anymore and just put out the bluetooth beacon in which users could interface with and purchase soda from their phone. If this is the case, then when the network is congested like original stated, nobody would be able to purchase a soda.

If this is not the case, and all physical web is to allow users to purchase soda in a "new" way. Then altogether I would personally argue this project may not see the light of day. I would imagine that the end goal would need to be a change up to our entire world and make everything simpler and faster to use, and provide more than a normal 'analog' interface could provide.

I argue this is wholistically different than saying "how could I use Twitter" without a connection. Twitter is an online resource. While a soda machine is a real world, in front of you, item that you would want to use at that moment. 

So i'm eager to hear thoughts. Do you guys agree this should change the way we use all items in the world? or does it just give us a second way to use items? If so, what makes you believe it is a desire of the world to adopt?

**Comment by scottjenson** [comment]
Well there are a couple of answers. The first is that there is a path to have offline work, but it requires a few additional layers to be involved:

**Bluetooth LE Javascript support** Having access to BLE through JS would allow your webpage to connect directly to the device in front of you. 

**Service Workers** Allowing you to 'save' your site as you can with any service working page, would allow you to cache the entire thing onto your phone. 

The combination of these two things would allow you to then use a device without any connectivity but a) We need to get all three experimental technologies in play and b) this requires quite a bit of forethought on the users part. If they don't proactively save the webpage, it won't be cached for them.

Sorry for the wondering answer, just letting you know that were deeply interested in this issue and have been thinking about it.

However, the heart of your question goes far beyond this answer. You are comparing hard cash + physical buttons to a more etherial web approach and I see your concern. Again a couple of ways to think about it:

### The Obnoxious Approach
You can be out of cash/coins. While the physical world is more robust, it has it's downsides. I was just recently at CES and didn't have any cash/coins so the vending machines were useless to me. This is clearly a slightly sneaking answer but we have to admit that 'hard physical systems' aren't infallible.

### The Longer Term Approach
In the longer range vision, the big impact of this technology isn't going to be replacing existing vending machines. Just as Credit Card vending machines still accept coins, so too will Physical Web devices. It takes a long time for infrastructure to change and to make an existing product SOLELY depend on a new tech would indeed be very naive. 

However, as this catches on, we expect the very idea of what types of machines will be interactive to change radically. My luggage, my dog's collar, my toaster oven, my car, or a statue in the park will all sprout information, sometimes read only and sometimes interactive. The goal is to allow everything to offer additional information and sometimes interactivity. We expect that to be a much bigger, more transformative use that just replacing vending machines.

### The Pragmatic Approach
When power tools were first introduced, craftsmen kept with hand tools as power wasn't common or reliable. Over time that changed. I'm completely sympathetic to your concern that there will always be areas that won't have coverage but that is changing. It's not unrealistic to think that in a fairly short period of time, most areas will have coverage. It seems reasonable to considers services that use this new capability, especially if the value offered is so high.

### Final point
When transitioning over to a new type of infrastructure, you indeed have to be cautious. The statue in the park will clearly has a plaque, as always, but the physical web beacon will point to a video and allow memorial messages to be posted. The new can build with the old, it doesn't have to replace it.
