### ISSUE TITLE
Remove alphabetical sorting in regions.

### ISSUE THREAD

**Issue by g-ortuno** [google/physical-web#267]
Since alphabetical sorting per region was added to improve stability and the app is no longer constantly refreshing the results, it might be worth considering removing alphabetical sorting in regions. That way we wouldn't have to worry about differences between antennas when it comes to ranging.

**Comment by dinhviethoa** [comment]
I think it doesn't solve the issue since there's a distance where the RSSI measurement becomes unreliable and it will probably vary across device.

**Comment by g-ortuno** [comment]
RSSI unreliability at long distances seems like a different issue. 

Image you have a phone whose antenna constantly returns really low values. The returned RSSI for things nearby is still reliable and should be used for ranking.

**Comment by matthewsibigtroth** [comment]
Good point. However, we're moving to proxy server sorting, and hence abandoning region/alphabetical sorting altogether.

**Comment by roywant** [comment]
Matt - I don't think you want to abandon region sorting,  even with a proxy.

The region/distance should be one of the inputs to the proxy. Physical Web
would still use region/distance as one of the major signals in the sorting
process.

That's the "Physical Web"  aspect of the project, or else its just the Web.

--Roy

On Wed, Jan 28, 2015 at 2:08 PM, matthew sibigtroth <
notifications@github.com> wrote:

> Good point. However, we're moving to proxy server sorting, and hence
> abandoning region/alphabetical sorting altogether.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/physical-web/issues/267#issuecomment-71926960>.
>



-- 
__________________________
*Roy Want*
*Google Research*
MTV-1225-2R1D
Cell: 650 691 3600
www.roywant.com/cs

**Comment by matthewsibigtroth** [comment]
Agreed. Forgive me, I wasn't clear enough. What I meant was that we are
abandoning local (on the client) region sorting. The proxy server will
receive and include beacon txPower and rssi when computing a sorting score.
We definitely want to consider physical regions when sorting. It's just
that when we use the proxy server to sort, the region resolving will be
computed remotely (relative to the client) instead of locally.

**Comment by roywant** [comment]
Very good - thanks for clarifying.

On Wed, Jan 28, 2015 at 2:33 PM, matthew sibigtroth <
notifications@github.com> wrote:

> Agreed. Forgive me, I wasn't clear enough. What I meant was that we are
> abandoning local (on the client) region sorting. The proxy server will
> receive and include beacon txPower and rssi when computing a sorting
> score.
> We definitely want to consider physical regions when sorting. It's just
> that when we use the proxy server to sort, the region resolving will be
> computed remotely (relative to the client) instead of locally.
>
> On Wed, Jan 28, 2015 at 2:13 PM, Roy Want <notifications@github.com>
> wrote:
>
> > Matt - I don't think you want to abandon region sorting, even with a
> > proxy.
> >
> > The region/distance should be one of the inputs to the proxy. Physical
> Web
> > would still use region/distance as one of the major signals in the
> sorting
> > process.
> >
> > That's the "Physical Web" aspect of the project, or else its just the
> Web.
> >
> > --Roy
> >
> > On Wed, Jan 28, 2015 at 2:08 PM, matthew sibigtroth <
> > notifications@github.com> wrote:
> >
> > > Good point. However, we're moving to proxy server sorting, and hence
> > > abandoning region/alphabetical sorting altogether.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/google/physical-web/issues/267#issuecomment-71926960>.
> >
> > >
> >
> >
> >
> > --
> > __________________________
> > *Roy Want*
> > *Google Research*
> > MTV-1225-2R1D
> > Cell: 650 691 3600
> > www.roywant.com/cs
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/google/physical-web/issues/267#issuecomment-71927763>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/physical-web/issues/267#issuecomment-71931086>.
>



-- 
__________________________
*Roy Want*
*Google Research*
MTV-1225-2R1D
Cell: 650 691 3600
www.roywant.com/cs
