### ISSUE TITLE
Suggestion to advertize an IPv6 address payload instead of domain names

### ISSUE THREAD

**Issue by brandonwittwer** [google/physical-web#27]
I'm just now joining the discussion, and I hope to offer something valuable to it.  It appears that a lot of thought is going into the concern about the volume of data needed to be advertised in order to assemble a decently small domain name to the client device.

BUT: If the url isn't human readable, then why are we worried about DNS at all?  

IPv6 addresses will entirely fit within the 16 byte payload and may be compressible even further.  Already I've heard conversation suggesting that the response would not be the final webpage but rather a JSON-LD response with metadata. We'd need to suggest IPv6 since only one advertising response could be served from that address and IPv4 space is already congested.  Having a dedicated public IP address that serves only one tiny piece of JSON information is a little inefficient, but without host headers to route that request around on the endpoint webserver it's the only way to make this idea work.  There are more than enough IPv6 addresses to go around however... 

I haven't tested it in the code yet and I don't own an IPv6 address to test with, but the concept seems sound to me.  I think this will help get around many of the url concerns.  Thoughts?

**Comment by rektide** [comment]
I think this would be really valuable to have.

Related eddystone issue: https://github.com/google/eddystone/issues/28

**Comment by scottjenson** [comment]
This same issues still remain:
1. every ipv6 address would need to point to a working webpage (for meta data)
2. every ipv6 address would have to point to a public server (so the PWS can see it)

There are ways around both of these issues. Just saying that, for now, it would have to act like a URL. We clearly understand the value of local access of devices, but it does raise important security issues that we're still grappling with.
