### ISSUE TITLE
Dismissible links?

### ISSUE THREAD

**Issue by g-ortuno** [google/physical-web#273]
Just an idea; Having the option to "flag" or dismiss a link so next time it shows up, it's further down the list.

**Comment by schilit** [comment]
right swipe?

**Comment by scottjenson** [comment]
Good idea, the right swipe could expose optional actions to refine the action: e.g. not interested, spam

**Comment by mmocny** [comment]
Easy: add a filter to the app, persisted in storage.

Harder: store user settings in the cloud.

**Comment by AverageMarcus** [comment]
I like the idea of having a file on storage that contains ignored URLs (as a regex). 

This then allows for ad-block style lists that could be shared to help prevent unwanted spam.

I have done something similar in [my fork](https://github.com/AverageMarcus/physical-web/commit/2e15ae47023c99dbcf3e705c9dd7e8ba106cf2b5) but as I'm not an Android developer It's likely a horrible implementation (so I'm not gonna submit a PR).

@mmocny does it need to be saved in the cloud? If so, on Android you have the [Backup API](http://developer.android.com/training/cloudsync/backupapi.html) that might be suitable?

**Comment by cco3** [comment]
Sure, we could use the backup api if available on the device.  I don't think it'd be as hard as @mmocny might have imagined.

I think there's a lot of things to rethink here in terms of UX.  Right swipe doesn't feel as persistent as what we are talking about.  When I right swipe a notification, that doesn't keep notifications of the same variety from coming back.  Why should it keep a URL from coming back.

Furthermore, if we think of this as a search problem, giving people the option to have a personal set of blocked results might be too complicated.  Maybe they should just have a way to flag that affects the results for all.

Anyway, all that to say that I don't think we have clear idea of how we would want this to work yet.

**Comment by AverageMarcus** [comment]
The use case I had that prompted me to add my own solution was I have a beacon that I keep in my backpack that broadcasts my details (for things like confs, meetups, etc.) and was sick of it constantly popping up on my own device.

Obviously I don't want to 'flag' this as a bad URL for other people so I'd like a way of filtering out results on my own device only.

**Comment by cco3** [comment]
Hm, interesting and valid use case.  We should probably also consider other ways we can be less noisy.

**Comment by stephrieger** [comment]
From a UX perspective, offering a way to "mute" as opposed to block might
be a way to position it. I've heard of this use case already a bunch of
times in facilities that have set up beacons and where staff got tired of
always seeing them pop up. This was a traditional iBeacon scenario, so "pop
up" would mean a notification and got annoying extremely quickly...but I
could foresee the same issue being annoying even with user-initiated
search, as Marcus suggested.

**Comment by AverageMarcus** [comment]
My main annoyance is constantly seeing it pop up on my Android Wear watch. While its not a disturbing notification it does display on the screen when I take a look at the time.

**Comment by scottjenson** [comment]
I agree with you. We are discussing this and trying to come up with a simple way for the notifications never show up on wear. However, keep in mind that eventually, we'd like to have some notifications have actions to them (e.g. unlock door) so you could use the Physical Web right from your phone. We have a ways to go in order to do that safely, but it's very much on our roadmap. This 'never on the watch' solution is only for the current UX.

**Comment by AverageMarcus** [comment]
'Never on the watch' would be a mistake I think. I like getting the beacons show up on my watch as its easier to check. I just don't want to always see the one I carry around.

**Comment by scottjenson** [comment]
I appreciate your use case but that's a LOT hard to figure out. Given that you can't do anything with the notification on your watch, it's hard to image it's value. Yes, it alerts you to something that actually is broadcasting, but that is a very temporary situation. I've we're successful, in a few years you'll ALWAYS have  beacon nearby so the alert is nearly useless. 

At this point we want to build the system slowly and a bit conservatively. We don't want to piss users off and nearly useless notifications is one way to do that.

However, I'm not against this, just for now. As I said earlier, the idea that each beacon can have it's own ranking raises very interesting possibilities. I'm very much in favor of this idea. I'm just saying let's try hard not to be annoying as we get started.

**Comment by scottjenson** [comment]
Clearly this issue has covered a lot of ground, pointing to many possible issues. Closing for now. However, if there is a specific feature/bug you'd like to see addressed, please create a more precise issue. For the record, we *do* want to have more personalized results but that is a much bigger issue and involves lots of potential directions. We're very much supportive of more personalized results.
