### ISSUE TITLE
Issues with 0.1.823

### ISSUE THREAD

**Issue by g-ortuno** [google/physical-web#275]
From @tolson2000:

Beacons will now at least show up sometimes, albeit, can take several swipe attempts. When another app is in the foreground, the little icon at the top left of the screen will indicate the correct amount of beacons in the area. Howevver, bringing the PW to the foreground will not immediately show those though and sometimes not all of them.

I get a lot of "PW has stopped responding" notices.

Sometimes the screen will go BLACK and I can not bring up any other apps until it decides to come back. I've had to kill the app several times. Total power down and reboot once. Something is still amiss in the overall functioning since the last reliable version of 1.737.

Today, my Nexus 7 has a notice that a System Update downloaded and read to install 5.0.2.
I am not sure I want to do this if it leads to additional difficulties. Will upgrading Nexus 7 to 5.0.2 from 4.4.4 fix whatever problems PW is having with Kitkat?

**Comment by g-ortuno** [comment]
@tolson2000 I copied your problems here so we can track them separately.

From what you mentioned these are the problems:
1. Beacons don't show up sometimes.
2. The notification shows correct amount, but app doesn't show all of them when opened
3. A lot of crashes
4. Black screen that needs total reboot.

I have a couple of ideas, but first: are you having all these problems on the nexus 7 (2013) you mentioned?

1. The reason you were not seeing the beacons in the previous version was that the metadata was taking too long to arrive when the list got drawn, so the beacons weren't ready to be shown and were not drawn. To solve that problem now you should see a "Loading..." message for each beacon near you. Do you at least see the "Loading..." message? If not then there is something wrong with the scanner that we need to investigate.

2. This one is related to (1). The background process finds all the beacons and shows them but when you open the app it has to scan for them again and that might take a while.

3. & 4. When it stops responding could you send us a crash report? There should be an option if you downloaded the app from the Play Store.

**Comment by tolson2000** [comment]
Yes, Nexus 7 (2013). The good one!

Black screen doesn't always require reboot. But may come back to white screen. Sometimes back to black after a few seconds. Odd!

Sent several reports. Don't know what to enter into the description field though.

**Comment by g-ortuno** [comment]
Great! Thanks a lot. We'll look into the issue.

What about (1)? Do you see the "Loading..." message?

**Comment by tolson2000** [comment]
No "Loading..." message!

**Comment by g-ortuno** [comment]
Wow. Just to be safe, can you confirm you're on 0.1.823 in the "About" screen?

**Comment by tolson2000** [comment]
Right now, I can't even see that. Stuck with black screen. Killing app several times. No dice. However, going to settings-apps it says version 0.1.823. Powering off. Powering up. PW white screen.. no beacons.. Menu About says.. Version 0.1.823.. Swipe.. beacons found and displayed. Go to different app, Come back to PW... "Searching for beacons"... NADA. Swipe... Beacons found and displayed. Go to webpage. Select PW again. "Searching for beacons"... NADA.. Swipe..Beacons found and displayed.

**Comment by g-ortuno** [comment]
Ok. We'll look into it. Thanks!

**Comment by g-ortuno** [comment]
@tolson2000 We just released "0.1.830" to the play store. Please try it out and let us know if you have any issues. Regarding Lollipop: The Android version shouldn't cause any regression for the Physical Web App, feel free to update.

**Comment by tolson2000** [comment]
Installed the new version. Thanks. Looks pretty responsive. Only thing
is.. as beacons come in and out
of range (simulated by turning them on and off) they do not show up or
leave the screen until a swipe refresh.
Is this the new intended working approach? I prefer the original where
as long as the screen is in view beacons appear and disappear as they
come in and out of range.

**Comment by g-ortuno** [comment]
Yes, that is the intended behavior. Although right now the old way might seem okay it doesn't scale well. Imagine you're about to tap a web address but suddenly a beacon goes out of range. That would change the whole list and force you to tap the wrong address. For this reason (and many more) we've decided to only refresh the list when the user wants to refresh the list.

**Comment by tolson2000** [comment]
OK, I see. Now what I guess I want to do is set up 50 beacons in an area
and see
what happens when I go to swipe up and/or down the list. Will swiping
down suddenly cause a refresh.
What will be or is the swiping rules for moving up and down the list
without causing it to refresh. Perhaps a README usage page can be
created somewhere. Thanks.

**Comment by g-ortuno** [comment]
No, swiping up and down the list won't cause a sudden refresh. You can read about the swipe to refresh patter here:

http://www.google.com/design/spec/patterns/swipe-to-refresh.html#swipe-to-refresh-swipe-to-refresh

**Comment by tolson2000** [comment]
Thanks, that helps clarify the usage. I'm thinking I'm on my self-guided
tour through the zoo, museum, bus depot and I am wanting to watch the
results on my screen of the strongest beacons in the area.. assuming
those are the ones that are most likely in front of me and the ones I am
most wanting to know the descriptions of. So I guess I am still voting
for strongest beacons should auto sync to the screen on most use cases
without me having to swipe in front of each possibly beaconized item.

**Comment by tolson2000** [comment]
Probably what a user really would want is a configuration option that effectively says just show me the top X strongest (closest) beacons. Obviously, in an area that might have 1000 beacons it is totally unmanageable unless there is such a choice the user can make.
