### ISSUE TITLE
How a Physical Web app locate beacons in configuration mode in "Edit URLs" ?

### ISSUE THREAD

**Issue by valterforesto** [google/physical-web#284]
I'have implemented the URI Beacon specifications GATT characteristics tree for configuring a Bluetooth Low Energy module BEACON using the Configuration Service described on  https://github.com/google/uribeacon/blob/master/specification/ConfigService.md.
I'm using the last Physical Web version 0.1.830 app on an Android 4.4.2 Samsung Galaxy S4 to discover and attempt configuration of my module BEACON.
I'm not able to enter "Edir URLs" configurations also if the Lock State characteristic of my module BEACON is 'unlocked' (0).

So, my question is: how a Physical Web app locate beacons in an unlooked state when "Edit URLs" is entered on the app ?  

Thanks, Valter.

**Comment by scottjenson** [comment]
As you've moved this question to the URIBeacon repo (which makes sense), I'm going to close this one
