### ISSUE TITLE
Should I expect mDNS to work on iOS?

### ISSUE THREAD

**Issue by AKAMEDIASYSTEM** [google/physical-web#287]
Hi, I'm developing my application mostly on Android but am hoping to support iOS as well.

Right now, I see my mDNS "beacons" just fine on my Nexus 5, but not at all on my iOS device. When I power up a BLE beacon, the iPhone see it as expected. Per https://github.com/google/physical-web/issues/169, I was hoping to see mDNS beacons in the iOS app.

...is mDNS functionality not in the version of this app that is in the app store? I.e., I'd have to compile it myself for now in order to see mDNS beacons? This would be fine, I'm just a little worried I'm not implementing my mDNS beacons correctly...

Thanks very much for any help you can provide!

AKA

**Comment by dinhviethoa** [comment]
The iPhone app is supposed to see those beacons.

Could you double-check with that the following app is seing the mDNS beacons?
https://itunes.apple.com/us/app/discovery-bonjour-browser/id305441017?mt=8

**Comment by AKAMEDIASYSTEM** [comment]
Thanks for the quick reply!

I installed the other app and am still not seeing my beacons (though they're still visible in the latest Android app)

I'm attaching two screenshots of the android and iOS devices, so you can see that the iOS device is definitely seeing _some_ mDNS stuff on my network. I'll also attach the full .service file I am using; I'm not sure I've implemented it perfectly, so it's sounding like I've discovered an edge case ;-)

Here's the .service file's contents:
```    
<?xml version="1.0" standalone="no"?><!--*-nxml-*--><!DOCTYPE service-group SYSTEM "avahi-service.dtd"><service-group>
  <name replace-wildcards="yes">http://bender.local?smell=weird</name>
  <service>
    <host-name>http://bender.local</host-name>
    <type>_http._tcp</type>
    <port>80</port>
    <txt-record>path='?smell=weird'</txt-record>
  </service>
</service-group>
```
![2015-02-10 21 58 57](https://cloud.githubusercontent.com/assets/407323/6137469/2f7215ec-b147-11e4-97ab-e4ab63810d35.png)
![2015-02-10 16 58 46](https://cloud.githubusercontent.com/assets/407323/6137472/369ff64a-b147-11e4-86f0-09e64f2978a8.jpg)


...thanks again for your help!

AKA

**Comment by dinhviethoa** [comment]
Can you remove `http://` from the `host-name` property?

The config file should look like that:

```
<?xml version="1.0" standalone="no"?><!--*-nxml-*--><!DOCTYPE service-group SYSTEM "avahi-service.dtd"><service-group>
  <name replace-wildcards="yes">http://bender.local?smell=weird</name>
  <service>
    <host-name>bender.local</host-name>
    <type>_http._tcp</type>
    <port>80</port>
    <txt-record>path='?smell=weird'</txt-record>
  </service>
</service-group>
```

**Comment by AKAMEDIASYSTEM** [comment]
Hey, that worked! Thanks for the tip. I must have missed that on the wiki page...

Thanks again for the quick help!

AKA
