### ISSUE TITLE
Notification shows shortened url rather than expanded url.

### ISSUE THREAD

**Issue by g-ortuno** [google/physical-web#292]
![shortened](https://cloud.githubusercontent.com/assets/3117611/6311654/e24eb622-b91a-11e4-8a30-44bd2c21a3c0.png)

**Comment by scottjenson** [comment]
This is clearly a bug. Thanks for reporting

**Comment by cco3** [comment]
When does this happen?  Anytime two beacons are in the list?

**Comment by g-ortuno** [comment]
The change shouldn't be too hard. You can see an example of the problem in this [line](https://github.com/google/physical-web/blob/master/android/PhysicalWeb/app/src/main/java/org/physical_web/physicalweb/UriBeaconDiscoveryService.java#L485). Should be something like:

```java
String siteUrl = mUrlToUrlMetadata.get(url).siteUrl;
remoteViews.setTextViewText(R.id.url_firstBeacon, siteUrl);
```

You just have to track down all instances where `url` is being used instead of `siteUrl`.
