### ISSUE TITLE
Browsing link in getting_started.md results in 404 error 

### ISSUE THREAD

**Issue by Asterisk14** [google/physical-web#293]
Browsing link under section physical-web/documentation/getting_started.md results in 404 error.

Exact line:
If you want to hack a bit, there is also a growing list of maker devices that support the broadcasting of URLs in this directory

[this directory] points to following url: https://github.com/google/physical-web/tree/master/firmware

which results in 404 error.

![image](https://cloud.githubusercontent.com/assets/5764666/6315952/09c49dd6-ba13-11e4-9281-f06e95050405.png)

**Comment by scottjenson** [comment]
Excellent catch, thank you! Fixed
