### ISSUE TITLE
Limit beacon range

### ISSUE THREAD

**Issue by dermike** [google/physical-web#294]
After setting up a dozen beacons in the library where I work today, I started thinking about the range. I'm not sure I agree with myself, but throwing this in for discussion. The range of the beacons were really good in terms of distance, and I can think of a few occasions where I don't want it to be that great... like limit it to a smaller area. 

I'm no Bluetooth expert, but for future beacon hardware it could be useful to be able to set the advertisement strength somehow.

**Comment by g-ortuno** [comment]
What beacons are you using? If you are using V2 beacons you should be able
to set the broadcasting power.

**Comment by dermike** [comment]
Oh, great, these are V1.

**Comment by scottjenson** [comment]
The v2 beacon spec has been out a few months but the v2 hardware is JUST
coming out. Sorry we couldn't send you the latest.

Scott

**Comment by dermike** [comment]
No worries @scottjenson! Much appreciated, thank you!
