### ISSUE TITLE
Logo in a vector format

### ISSUE THREAD

**Issue by gmarty** [google/physical-web#295]
Where can I find the physical web logo in a vector format (preferably SVG)?

**Comment by scottjenson** [comment]
I'll upload it later today when I get into work. Can you say what you'd be using it for?

**Comment by gmarty** [comment]
I'd like to experiment an app for Firefox OS, using mDNS first and then BLE when support becomes available later this year.

**Comment by chrisblanz** [comment]
@scottjenson - Are there any Physical Web logo usage guidelines documented anywhere?

@gmarty - I made this one that you are welcome to use. I don't know if it is "official", meaning it does not include any type treatments, but it is a proportional representation of the mark itself. https://www.dropbox.com/s/igf92w0u8m4h1jl/UriBeacon%20Physical%20Web%20Vector.svg?dl=0

**Comment by scottjenson** [comment]
Added logo in .ai format (adobe illustrator) and three colors of png format in documentation/images/logo

https://github.com/google/physical-web/tree/master/documentation/images/logo
