### ISSUE TITLE
Run Android app in background across reboot

### ISSUE THREAD

**Issue by gmarty** [google/physical-web#298]
I'm using the Android app but I noticed that I have to restart the app manually after a reboot to keep it scanning in the background. It looks like it's being killed when the phone restarts.

I'm not familiar with Android development, but is there a way to register a background task or wake up the app at regular interval? The scanning should start as soon as the app is installed, without the need to launch it manually.

**Comment by scottjenson** [comment]
Thanks, thats a good point. We're looking into this to see what it would take to update the app.

**Comment by cco3** [comment]
https://github.com/google/physical-web/pull/303

**Comment by scottjenson** [comment]
Is this merged? If so, can we close?
