### ISSUE TITLE
Physical web and manifest

### ISSUE THREAD

**Issue by kenchris** [google/physical-web#301]
Currently the physical web is said to transmit a URL. Would it make sense to transmit JSON instead with a start_url as defined in http://w3c.github.io/manifest/ ? That way we can get a more web app like experience. Another option would be to transmit the URL referring to a manifest.

@marcoscaceres @anssik

**Comment by scottjenson** [comment]
Interesting. So to make sure I understand you. The beacon still contains a URL but it points to a server that returns a JSON manifest instead? I'm sure you know this, but the ad packet is so small that the manifest couldn't fit in the ad packet, it would have to be a URL pointer to it instead.

If so, how would the scanner on the phone change? How does this change the experience from just taking them to a URL?

Scott

**Comment by kenchris** [comment]
Yes, I understand that we can only store an URL (and they are limited in length). The scanner should be able to fetch the manifest which provides additional info, like name, short_name, and always an actually URL (start_url) with additional information which can be used when launching the URL, like display-mode, orientation etc. - basically allowing launching a web app with a real app experience.

**Comment by jyasskin** [comment]
I think the UriBeacon's URL should be thought of as (potentially) a deep link into an application. It shouldn't be limited to targeting the `start_url` mentioned in the app's manifest. The web page it points to can include a `<link>` to the manifest, which provides the additional information you're interested in.

**Comment by kenchris** [comment]
@jyasskin the problem with that is that the manifest is fetched async and the information will not be available at the time the web app is launched, unless it is pointed directly to the manifest.

I need to think a bit more about this, maybe @marcoscaceres have ideas.

**Comment by scottjenson** [comment]
@kenchris Keep in mind that we've received very strong support from companies that would like (as @jyasskin says) a URL that takes you to a web page OR deep links into a native app. ZipCar is a good example of this where they really want to capture users when they are curious and the web is perfect for this. As they use the service more, they would also like to use the native app.

If this manifest can still maintain this ability, we're in good shape. Just letting you know the value of the the URL working for both native and web.

That being said, we currently scrape for things like title and description and using the manifest as a robust, easily parseable list of meta data seems quite interesting. We were also toying with using JSON+LD as it was a bit more low key and very easy to drop into any web page. Interesting in exploring the pros/cons of both approaches.

**Comment by jyasskin** [comment]
@kenchris When a user clicks a link on the ordinary web that goes into an application, the manifest is also fetched asynchronously, and the information is delivered some time after the page is initially launched. Is there a reason to treat links from Bluetooth devices differently?

**Comment by kenchris** [comment]
@jyasskin, the manifest data is usually only applied when the user for instance "saves the site to the homescreen". Then when launched from the homescreen it will be applied.

That is because we don't want to delay loading of regular web pages for use cases where the manifest is not relevant. As @scottjenson pointed out, they do scraping already, and just fetching the manifest resource immediately for Physical Web seems like an OK solution.

**Comment by kenchris** [comment]
@scottjenson if anything is missing from the manifest, we made it extendable on purpose. But please file any issues or feature requests to the spec itself and we will have a look at it.

If it is not in scope (like considered a special case), you can extend it http://w3c.github.io/manifest/#proprietary-extensions

For instance @slightlyoff suggested some Chrome extensions here https://github.com/slightlyoff/AppInstallImprovements/blob/master/explainer.md some of which we have already incorporated.

**Comment by scottjenson** [comment]
OK, now that we seem to be focusing on the manifest as a means of caching website information for the Physical Web, I'd like to return to my JSON+LD comparison. Both can accomplish the same caching task (with the manifest clearly being more specified) Are there pros/cons for either one? Should we support both?

**Comment by kenchris** [comment]
The manifest can be extended with the JSON+LD. We actually had a section about that at some point but @marcoscaceres removed it for some reason. Comments Marcos?

**Comment by anssiko** [comment]
For the rationale for dropping JSON-LD from the Manifest spec, see https://github.com/w3c/manifest/issues/313

**Comment by g-ortuno** [comment]
One of the reasons we added JSON+LD support was for us to experiment with "Actions" similar to the ones in [Gmail](https://developers.google.com/gmail/markup/actions/actions-overview). Is there a way for a website to declare possible "Actions" in a manifest?

I like the idea of opening a URL and seeing a website that looks a lot like a native app which I believe is what `manifest` is pushing towards. Please correct me if I'm wrong.

**Comment by scottjenson** [comment]
We've discussed it a bit here on the team and the manifest seems like a great, standard way to get title, description, icon info so it seems like a great way to get that info without scraping the page.

The only remain issues, as Gio says, it how we'd extend the manifest to get new types of things, especially things that many not be in the manifest. That is why we considered JSON+LD as it was so wide open and easy to add something to.

**Comment by kenchris** [comment]
You are definitely allowed to mix the two, like extend the manifest with JSON+LD.

Still, we would be very interested in hearing what is missing from the manifest for your use-cases and see if that is within scope of the spec, so that we avoid people doing similar things in different ways.

Could you explain a bit more about your "actions"? Is this something similar to web intents or something entirely different?

**Comment by tolson2000** [comment]
Cool, getting the manifest can be done by the PW app itself instead of
having to rely on hi-power scraping server to get the job done
efficiently. Letting the PW app get the info directly from the website
enhances a users privacy in that all the beacons they pass by are no
longer accumulated by the owner of the scraping servers.

**Comment by g-ortuno** [comment]
@tolson2000 Keep in mind that the Proxy server serves two functions:
1. Save bandwidth, because the user's phone doesn't have to download each webpage
2. Isolate the user's IP from the website the beacon points to

**Comment by tolson2000** [comment]
Yes, but if it is getting manifest info, it has to get that from the
scraper anyways.
So no gain there.
IMHO getting a title, description and icon doesn't cause any privacy
issues when
gotten from independent  web sites server. But, having it cached in the
scraping server
allows that service to accumulate boat loads of info about the users
movement activity
which can definitely lead to more serious privacy issue.

**Comment by scottjenson** [comment]
There a few issues being floated here. The main one is @tolson2000 saying that having the server do less is considered better and protects the user. We actually added the server to *protect* the user as the users device is never contacting web sites directly, it is always done from the proxy server (and cached as well) This buffers the user from every contacting the website and even prevents the website from knowing *when* the user asked for the info (at least within the cache timeout) As Gio says, as we only need a fraction of the manifest, it also save bandwidth.

Now we realize that having a single server concentrates access into a single server. The whole point of the Physical Web is to be like the web and decentralized. This is why we use URLs which rely on DNS to resolve the beacon. It's also why we've open sourced our server to openly encourage others so users can pick alternative clients/servers. It's even possible to make a client that uses no server at all of you 're willing to do all the work on the client. In fact, we feel strongly there should be other servers in this ecosystem.

Given this argument, we'd still have the server fetch the manifest for the simple reason that some sites support it and some don't. By having the server always return the same info regardless, it makes the client's job much simpler.

**Comment by tolson2000** [comment]
Interesting. I didn't know the PW scraper server side of the project was
open source.
Where is the link to that?

I understand that the manifest is not generally available yet and your
argument makes sense.

I am working on the concept that the people that design the web page
that goes with their beacon
will include whatever is needed. Pointing to random website are for sure
an issue. They don't even
necessarily have description meta data or title or even an icon. So a
developer of a website specifically
for a beacon will include those metadata and likewise, if supported, the
manifest concept.

**Comment by g-ortuno** [comment]
Link to the proxy server code:
https://github.com/google/physical-web/tree/master/web-service

**Comment by marcoscaceres** [comment]
Just a tiny thing to add, for manifest, we are currently cooking up a way to allow developers to indicate "[preferred/related apps](https://github.com/w3c/manifest/issues/326)" (which can include native app handlers). This may allow this to work with both web pages/apps, as well as providing the ability to access a service through a native app. We haven't settled on what this looks like yet, but something like:

```JSON 
{
"preferred_platforms": [{
  "vendor": "play",
  "id": "foobar"
}, {
  "vendor": "web"
}]
}
```
(@mounirlamouri is putting together a proposal)

It would be good to explore possibly making all this work together with the physical web proposal.

**Comment by scottjenson** [comment]
As the web manifest is an open part of the web, it makes sense for us to support it.

**Comment by mmocny** [comment]
My 2cents:  We should take advantage of a manifest whenever possible (as would a browser, its a great source of truth, esp. for page description), but should not encourage linking directly to manifests.  Beacon owners can link to whatever they want, and I think we could easily support the url-directly-to-manifest use case on the server (using start_url), but it seems unlikely that would be a good default for most cases.

**Comment by scottjenson** [comment]
So I'd like to 'wrap up this thread' if I could by making it a clear enhancement request that the PWS (the Physical Web Server) support the manifest file it exists. As this
1) a MUCH cleaner way to get the meta data needed to list the nearby beacons
2) a clear web standard

Scott

**Comment by mmocny** [comment]
Sounds good.  Should we file a new issue tracking the feature request?

**Comment by scottjenson** [comment]
Yeah, I just wanted to make sure there weren't any other comments. I'll close now and open an issue/enhancement
