### ISSUE TITLE
Favicon through proxy

### ISSUE THREAD

**Issue by cco3** [google/physical-web#305]
All the needed metadata of a site is grabbed through a proxy, but then (at least on the android app), the favicon is fetched directly from the app.  This seems to negate the point of using a proxy in the first place.  It seems like the proxy should actually give us the favicon instead of just the url to the favicon.

**Comment by scottjenson** [comment]
Agreed, this shouldn't happen. There are two paths to fix this, a) make sure the server gets it and b) give the server more options to find it robustly (see #301) by using manifest. Both are being filed as bugs/feature requests, thank you!

**Comment by g-ortuno** [comment]
Yes!! I even opened a bug #220 about a possible implementation...

**Comment by mmocny** [comment]
Fixed!
