### ISSUE TITLE
Demo/prototype

### ISSUE THREAD

**Issue by tvvocold** [google/physical-web#320]
Hi there,
Is this [thing](https://www.blesh.com) close to your prototype? If not, are there any one?
And i am wondering why not use WiFi (free WiFi) ?

Regards,
Ray

**Comment by scottjenson** [comment]
Yes it is. We list a range of compatible devices on [our home page](https://github.com/google/physical-web) just scroll to the bottom. There are even more coming. We *do* support Wifi in that we support mDNS. But we are suggesting you use it over a protected wifi so you can control access to who sees the beacons (but of course, you could still do it over protected free wifi if you wanted)

Scott

**Comment by scottjenson** [comment]
Closing but feel free to reopen
