### ISSUE TITLE
Consider expanding short-urls using api's instead of HTTP

### ISSUE THREAD

**Issue by mmocny** [google/physical-web#322]
According the the [goo.gl url-shortener docs](https://developers.google.com/url-shortener/v1/getting_started#expand), discussing why use the API to expand urls instead of just making the request:

> Of course, you could also just fetch http://goo.gl/fbsS and inspect the Location header in the response, but using the API has two advantages:

> 1. It won't update the short URL's click stats, so you can fetch a bunch of long URLs without worrying about messing up analytics.
> 2. If the URL fails to redirect (for example, if Google believes it points to malware), you'll get a machine-readable explanation of why.

**Comment by mmocny** [comment]
..thinking through it, the URL which is returned may still redirect, so this doesn't fully alleviate the problem.

**Comment by dinhviethoa** [comment]
The reason why it's using redirect is because we want to support other URL shorteners.

**Comment by mmocny** [comment]
Yes, and ordinary server redirects, so this is never going to be a full solution.

However, if we wanted to not impair the analytics of the urls we shorten, this is an option.

**Comment by mmocny** [comment]
Closing since I think there is no action item.
