### ISSUE TITLE
Using bluetooth both to advertise and to connect to the server ?

### ISSUE THREAD

**Issue by probar** [google/physical-web#324]
I really like the idea - could be really helpful for interaction with objects.

But what about cost constrained devices, where every cent count  - demanding 2 links(one to the server and an advertising beacon) isn't ideal. Also in some cases the added complexity/size/power isn't ideal. And usually those cases are interactions between a single person to single device - so no bottleneck of many to many. 

In those cases, shouldn't there be some proxy in app that relays messages between the device and the server, using the Bluetooth channel ?

**Comment by scottjenson** [comment]
But we don't demand two links. There are many use cases where the device is *just* broadcasting a URL (e.g. a poster or a luggage tag) My vending machine example needs some connectivity so in that case you are correct but I would argue that if you have a big device like a vending machine, that extra cost is minimal.

Another point is that the cost of things like GSM modems are falling quickly so the additional cost (even a vending machine) will likely fall quickly.

Final point is that when we get Javascript BLE in the browser (still a working spec, it's not done yet) that massively changes things as you could have a device that is exclusively BLE, which is both low power and low cost.

**Comment by probar** [comment]
My use case was for something like a toy, a cheap appliance(say toaster), a lightbulb, etc. GSM won't fit. There are plenty of other such use cases where GSM isn't viable. 

But sure, javascript BLE API could solve this well. 

But why wait? there are a few javascript ble libraries available - why not integrate one in the prototype - just to speed up the physical web research/adoption ?  you could always call that API experimental , and depreciate it when needed ,no?

**Comment by scottjenson** [comment]
We can't integrate a ble library into our prototype for the simple reason that we open every URL into the browser, not us. We want our scanner to be as thin as possible. We are very much trying to be built on top of the web, not next to it

**Comment by probar** [comment]
True , if you want to build on top of the web, you need to wait for web-bluetooth API. Any idea when it will be ready ?

**Comment by scottjenson** [comment]
It's already being worked on and has been announced. As a web standard though, it'll likely take many months to get through the standards body. I realize this is frustrating. If you're in a hurry you use various plugins to get started and experiment of course. We just feel this is the best way for the community to make sure we get this done through standards bodies.

**Comment by scottjenson** [comment]
Closing but feel free to comment/reopen if necessary
