### ISSUE TITLE
mdnsd not properly shut down on some devices

### ISSUE THREAD

**Issue by cco3** [google/physical-web#340]
A user has reported that mdnsd is not being properly shut down on his device (Moto X, KitKat).  This persists even after an uninstall of the app until reboot.

Someone seems to have a similar problem here:
http://stackoverflow.com/questions/29628181/nsdmanager-doesnt-stop-service-discovery

We should gather some more data -- specifically, see if we can get the program to keep running after uninstall with a small demo like the one linked -- and put this on the AOSP issue tracker for help.

**Comment by cco3** [comment]
Duplicated on a Nexus 7 (flo) running 4.4.4 (KTU84P)

**Comment by cco3** [comment]
Could not duplicate on 5.0.2

**Comment by scottjenson** [comment]
Now that pre-M devices dont' turn on mDNS, can we close this? @cco3

**Comment by cco3** [comment]
Someone can reopen if they see the problem on M
