### ISSUE TITLE
PWS should handle certain redirects differently

### ISSUE THREAD

**Issue by sowbug** [google/physical-web#341]
http://goo.gl/yRcWu0 points to http://www.randomwebsite.com/cgi-bin/random.pl, which redirects to a random website. The physical web server will cache the site it redirects to the first time, and then vend that same site over and over. What we really want is for the link to identify itself as a random-website redirector. Can we do that?

This is a somewhat silly example of a legitimate use case, where people might be redirected to substantially different content depending on various factors, and what you want to index is not the final destination, but the redirecting page's content.

**Comment by mmocny** [comment]
The `goo.gl` link returns a 301 (Moved Permanently), while `randomwebsite.com` returns a 302.

However, `goo.gl` also retuns a cache-control headers of `Cache-Control: no-cache, no-store, max-age=0, must-revalidate`, so, perhaps we should not be storing either of them.

**Comment by mmocny** [comment]
Redirects are no longer cached!

`curl -k -s -H "Content-Type: application/json" -d '{"objects":[{"url":"http://goo.gl/yRcWu0"}]}' http://url-caster.appspot.com/resolve-scan`
