### ISSUE TITLE
uribeacon-sample-debug.apk scan problem

### ISSUE THREAD

**Issue by ucxpresso** [google/physical-web#359]
Hi,

I found, some smartphone can dynamic change the distance after scan, but some smartphone are not and need to REFRESH to update the result.

Is it bug in the app ?

Regards,
Jason

**Comment by scottjenson** [comment]
Sorry Jason but I'm not understanding your question. Are you wondering why the items in the beacon list don't dynamically change as you get closer/farther from beacons?

**Comment by ucxpresso** [comment]
Hi Scottjenson,

Sorry for question without clear.
Yes, beacon list don't dynamically change for closer/farther from beacons.

Samsung Note 3 (Android 5.0) / ASUS zenfone (Android 4.4): The beacons list can dynamically change for closer/farther from beacons.

HTC one (Android 5.0) / MI (Android 4.4): The beacons list don't dynamically change for closer/farther.

Regards,
Jason

**Comment by g-ortuno** [comment]
Do they all have the latest physical web version?

**Comment by scottjenson** [comment]
We have tried to make the list dynamically sort but no matter what we tried (and we tried VERY hard) it always created a rather large UX problem: as the user tried to tap result A, result B would slip under their finger and they would tap the wrong button.

So we have a compromise. We listen for a few seconds, to make sure we get a proper reading on the beacons and then we display a stable list. If the user moves, they have to refresh the list. This is not idea but in all of our testing an auto sorting list is just too irritating and creates far too many selection errors.

Besides, in the long run, we feel the correct solution is to have the target website do the sorting for us. For example, a museum. It would be far better for you to see a single beacon "SF Moma" and when you pick it, it find all SFMOMA beacons using javascript (this is being worked on) this would allow the museum to provide a much better, tailored experience for museum goers. The Physical Web should just provide a simple list that allows the user to pick the broad category.

**Comment by ucxpresso** [comment]
Version is 1.4.

I think, the problem is from Android kernel of smartphone manufactories.
Good smartphone, do one startLeScan with many onLeScan callbacks and frequency are the same beacon's adv. interval, so beacons list can dynamically change for closer/farther from beacons.

**Comment by mmocny** [comment]
@scottjenson I see.. some *sometimes* it will refresh, if conditions are right?

Perhaps we should link the body of code that handles this for @ucxpresso so that its clearer when this happens.

**Comment by scottjenson** [comment]
Well, to be honest, each client is slightly different. The basic hand waving rule is "wait 2 seconds then display" If you were to list them as they were to come in, it would be a very jumpy display as things would be constantly resorting.

We fully expect there to be other, better approaches, we're just saying that for now, the wait and display approach seems to be the most stable and useful. Happy to discuss alternatives.

**Comment by g-ortuno** [comment]
The current Physical Web app should never refresh automatically. If it does then that's a bug.

@ucxpresso I see the title of the question says "uribeacon-sample-debug.apk scan problem" so maybe you're posting on the wrong Github repo. The UriBeacon Sample App does refresh automatically, and there could be variations between phones. Feel free to open an issue on the [UriBeacon Github repo](https://github.com/google/uribeacon) and we can continue the discussion there.

**Comment by scottjenson** [comment]
Assuming this is a URIBeacon issue, closing. Feel free to reopen if necessary
