### ISSUE TITLE
PWS tests.py fails on `test_redirect_with_rssi_tx_power` when auto-starting server 

### ISSUE THREAD

**Issue by mmocny** [google/physical-web#365]
The `test_redirect_with_rssi_tx_power` test is supposed to only work with `app.yaml` set to `-dev` (because it hits the `experimental/` endpoint of the PWS), but it isn't working with the server auto-starts (by running `./tests.py`), even when I change the `app.yaml`.

If I start a `dev_appserver.py` manually and run `tests.py -e LOCAL` it works fine!

**Comment by mmocny** [comment]
Ideally we can skip all the `-dev` tests if app.yaml is not set for it.

**Comment by cco3** [comment]
> with app.yaml set to -dev

What field is that?

**Comment by mmocny** [comment]
App name.  You can check helpers.py if I recall correct where it checks for
"experimental" mode.

**Comment by cco3** [comment]
Skip them because that functionality isn't yet in prod?  Or does the distinction go beyond that?

**Comment by cco3** [comment]
Also, do you have a quick fix for: "OperationalError: database is locked"

**Comment by mmocny** [comment]
I've not seen that error before, sorry..

**Comment by mmocny** [comment]
Yeah just skip them. Would be nice if test suite could display they were
skipped, but it's fine either way.
