### ISSUE TITLE
We have completed the physical website. References are as follows:

### ISSUE THREAD

**Issue by cgj531** [google/physical-web#369]
https://play.google.com/store/apps/details?id=com.adist.drivethru&hl=zh-TW
http://youtu.be/C-cLDUhitAc

**Comment by scottjenson** [comment]
Sorry but this appears to be spam. If it is a legitimate product that uses the Physical Web, please provide some comment and don't just drop in two links

**Comment by mmocny** [comment]
Sadly I watched through the video, and didn't see any beacons.  Description
even says "without internet".

**Comment by cgj531** [comment]
We are innovative applications, the 2014 Gold Medal Exhibition of Inventions of Taipei affirmed.
