### ISSUE TITLE
We have completed the physical website. 

### ISSUE THREAD

**Issue by cgj531** [google/physical-web#370]
physical web is not enough. We have to further complete physical website architecture, for to consider and use.References are as follows: 
https://play.google.com/store/apps/details?id=com.adist.drivethru&hl=zh-TW 
http://youtu.be/C-cLDUhitAc 
So, you can better physical web concept.

**Comment by scottjenson** [comment]
Ok, please tell us what you suggest. what improvements are you proposing?

**Comment by cgj531** [comment]
google is a good company, but in this concept at least 2 years behind us.
Because it is innovation and invention, so there are some new word must be explained:
physical website / a site is placed on the location. without the Internet, only when necessary, and then connect IoT exchange of information.
WiFi LBS physical website / geographically through WiFi way to provide all the known sites of Web services, without the Internet.
physical website URL / use the local language name of the store or service through WiFi broadcasts.
physical website browser / only a App, you can see all the physical website, or wearable equipment operators and physical website specifications.

 

Cloud application site is now mainstream, very suitable for people in the home or business, do some virtual trading or centralized management areas, conditions for large-scale systems and the high rate of flow, and I want to try to solve the real trading, so use integrated application solutions O2O do the actual situation. In fact, to solve real application, not only the connection or not, there is an important issue is the operating cost.

 

Application entity is when we are not home or business, but out in the real world environment in a region or businesses, the number of traffic usage is low, can only operate with a low cost way. Today all the web servers are concentrated in cloud, is the concept of concentration. in order to solve the physical environment of the application, we will move directly to a web server each entity store business is decentralized concept application in the physical world does not need a large centralized server , but scattered small server to each store.
Using solid way to achieve offline web server can also connect the O2O, but should be offline to online, in order to really solve the problem of substance use e-commerce.

 

Alibaba e-commerce bottleneck logistics, physical stores over the counter, using the system after phone / tablet, you can store in the physical electronic orders, O2O (offline to online) will become the bottleneck in the kitchen, you and Like Alibaba, delivery speed problems in the background, so the physical store efficiency in the use of the system after Alibaba achieve equivalent results, it can save manpower reception, kitchen manpower increase and accelerate the meal rate / rate increase turn tables.

 

The same Apple is a good company, but ibeacon not a good way to solve the problem of the physical environment.
My English is not good, hope you can understand my consciousness.

**Comment by cgj531** [comment]
The most important is a physical web server, the production cost of less than US $ 100, and no other fixed expenses. Entity store can use very low-cost and simple system to join the business. In the prior art methods are way is to use the web server operation cost at least US $ 10000 or more. use the cloud network to pay a very high cost and maintenance, and also has a high risk.

Our technology is the Wi-Fi base station and sites combined and placed in the actual location, to reach the site information service, location and integrated WiFi connection, and make special arrangements designed on SSID, become a new and innovative service system and the cost is only one-tenth or less of the old methods. the product service systems can help a physical store, use WiFi LBS concept of network technology, do e-commerce and marketing advertising (POP mode), but without the Internet and network use of fixed costs, and maintenance and operation is very simple. easily could have its own website and e-marketing advertising trading capabilities, increase revenue / reduce manpower and provide better service.

**Comment by mmocny** [comment]
Sounds like you are creating something very exciting, but you've misunderstood the concept of what we mean by "The Physical Web".

From our main readme:

> "Our core premise is that you should be able to walk up to any “smart” physical object (e.g. a vending machine, a poster, a toy, a bus stop, a rental car) and interact with it **without first downloading an app**."

and

> "At its base, the Physical Web is a discovery service: a smart object broadcasts relevant URLs that any nearby device can receive. This simple capability can unlock exciting new ways to interact with the Web."

By definition, we explicitly **want** to interact with the web.  From there, its up to the web app developer to create experiences.

Perhaps you can adapt your payment processing system for this use case.. but if you think you think you have created something better.. truly best of luck to you!

**Comment by cgj531** [comment]
You do not understand, Physical web is not a complete thing,

You're pathetic!

There must be physical website.

**Comment by mmocny** [comment]
Glad I took the time to answer nicely.

**Comment by mmocny** [comment]
(I've now blocked this user.)  I believe this should prevent his ability to interact with these repos.
