### ISSUE TITLE
Add support for displayUrl to clients

### ISSUE THREAD

**Issue by mmocny** [google/physical-web#391]
As per #388, the PWS will return a `"displayUrl"` key as part of `"metadata"` from a resolve-scan.

We should change the Android and iOS client applications to use these values in the UI.

@dinhviethoa and @cco3, care to take a stab?

**Comment by dinhviethoa** [comment]
I'm taking care of it on iOS.

**Comment by cco3** [comment]
I'll try to get to this soon.
