### ISSUE TITLE
When we're not able to resolve the metadata, hide the beacon

### ISSUE THREAD

**Issue by dinhviethoa** [google/physical-web#403]
Because we won't be able to reach the server anyway.

**Comment by dermike** [comment]
Is that really the desired outcome when the proxy can't resolve the metadata? I've been getting a lot of unresolved url's lately which work fine on my end, so there's probably gonna be many situations where the url is reachable for the user and not the proxy. 

If I'm expecting a url at a certain place I'd rather see it anyway. To know it's there, and to be able to at least try it and maybe save for later if it's something temporary.

**Comment by mmocny** [comment]
Agree with @dermike.

`unresolved` was meant to differentiate resolved-but-invalid specifically because clients may be able to access local-only or auth-only urls.

How we resolve the situation (no pun intended) is up for debate.  We could provide a UI affordance perhaps, or separate out the list entirely.  Or we could try to "resolve-scan" in the app itself, but that has all the [usual issues](https://github.com/google/physical-web/tree/master/web-service#why-do-we-use-a-physical-web-service)..

**Comment by scottjenson** [comment]
Fair question but please see #402 where we discuss why the meta data is valuable/required. Given that a URL could be invisible/spam/malware it seems unwise to show it if it should be removed/demoted.

Certainly in these early days when 
1) you're only looking at beacons you've personally setup
2) there are Physical Web bugs that make entries not resolve
I totally appreciate the 'just let me use it' desire but both of those conditions should hopefully change rapidly.

Or is there another meaning of 'unresolved' that I'm missing here?

**Comment by mmocny** [comment]
Local URLs are not uncommon even today.

Perhaps we can just not advertise these unresolved URLs but still provide a
"hidden" section within the app itself for those who want to manually scan
for them?

**Comment by dermike** [comment]
The protection and security thinking is great, but I personally is not 100% comfortable with being completely in the hands of the PWS. It may be temporary bugs, but right now I have a url that is returned unresolved 8 times out of 10. There will most likely be technical difficulties with the PWS from time to time that will just break the basic concept if the PWS is down.

**Comment by scottjenson** [comment]
@dermike that is 100% the issue, I agree. Failing 80% of the time is completely unacceptable. If we can't fix this then the resolving URLs before showing them is meaningless. If you don't mind, can you send us more info on this? We're seeing issues on slow networks now, but that would affect all beacons. You seem to have a single beacon that fails which is unique. Can you send any information that would help us understand what is happening (we're considering a better debugging version that would make this easier)

**Comment by dermike** [comment]
Sent you a mail with details @scottjenson

**Comment by mmocny** [comment]
FYI, we implemented this with patch c6ae6bf6ff6eb7f732f98a4fa3be739ec40df646.

If there are more detailed examples of failing cases which shouldn't be, please do send them our way.
