### ISSUE TITLE
Github pages 302 redirects returns unresolved by PWS

### ISSUE THREAD

**Issue by dermike** [google/physical-web#408]
I mentioned I had problems with a URL in #403 returning unresolved 8 times out of 10, or very inconsistent at least. I think I've isolated the issue to be caused by http status 302 which GitHub Pages uses for redirection for custom domains (and possibly in combination with using DNS A-records). Github doesn't return 302 every time for some reason beyond my knowledge, but 302 makes the pages uncached if I interpret the code correctly, which would explain the inconsistency in being returned unresolved/resolved.

I have no idea if this method for hosting pages is common outside of GitHub, but if browsers can reach the URL, the PWS must also be able to, especially if there's plans on hiding unresolved URL's in the client.

URL's I've been able to replicate this issue with are:
* http://librarian.codes
* http://fredrikthalberg.com
* http://harleykwyn.com

**Comment by scottjenson** [comment]
AH, this would possible explain things (It's still a bug of course, but even if working, it would be very slow as it would have to refetch the page each time) Excellent sleuthing. We'll look into this, thank you.

**Comment by dermike** [comment]
This was also not a problem until a month ago maybe.

**Comment by scottjenson** [comment]
That also helps as we've been making lots of PWS changes recently

**Comment by mmocny** [comment]
You can isolate PWS tests by asking it to resolve outside of the PWS app.  E.g.:

```
$ curl -k -s -H "Content-Type: application/json" -d '{"objects":[{"url":"http://librarian.codes"}]}' https://url-caster.appspot.com/resolve-scan
{"unresolved": [{"id": "http://librarian.codes"}], "metadata": []}

$ curl -k -s -H "Content-Type: application/json" -d '{"objects":[{"url":"http://fredrikthalberg.com"}]}' https://url-caster.appspot.com/resolve-scan
{"unresolved": [{"id": "http://fredrikthalberg.com"}], "metadata": []}

$ curl -k -s -H "Content-Type: application/json" -d '{"objects":[{"url":"http://harleykwyn.com"}]}' https://url-caster.appspot.com/resolve-scan
{"unresolved": [{"id": "http://harleykwyn.com"}], "metadata": []}
```

curling the first url directly shows an oddly configured server.  Sometimes we get:

```
$ curl -v "http://librarian.codes/"
* Hostname was NOT found in DNS cache
*   Trying 192.30.252.153...
* Connected to librarian.codes (192.30.252.153) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.37.1
> Host: librarian.codes
> Accept: */*
>
< HTTP/1.1 302 Found
< Connection: close
< Pragma: no-cache
< cache-control: no-cache
< Location: /
<
* Closing connection 0
```

and sometimes we get:

```


$ curl -v "http://librarian.codes/"
* Hostname was NOT found in DNS cache
*   Trying 192.30.252.153...
* Connected to librarian.codes (192.30.252.153) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.37.1
> Host: librarian.codes
> Accept: */*
>
< HTTP/1.1 200 OK
* Server GitHub.com is not blacklisted
< Server: GitHub.com
< Date: Thu, 28 May 2015 14:37:50 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 24471
< Last-Modified: Wed, 27 May 2015 13:57:47 GMT
< Access-Control-Allow-Origin: *
< Expires: Thu, 28 May 2015 14:47:50 GMT
< Cache-Control: max-age=600
< Accept-Ranges: bytes
<
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
... more page content
```

So basically, it looks like there are two issues:
1) We aren't correctly handling relative redirects (good catch!)
2) Some of the urls are hitting different server which are configured differently (perhaps behind a load balancer) and that is causing your "80%" observation.
