### ISSUE TITLE
BLE tag acting like NFC tags storing NDEF information

### ISSUE THREAD

**Issue by mofosyne** [google/physical-web#418]
Not sure if this is still considered physical web but here it is: 

NDEF :~ NFC Data Exchange Format

You know how you have passive NFC eeprom memory tags that can emit NDEF messages? I
wonder if there is any advantage to implementing something similar but at a
non contact distance like BLE etc...

I was imagining one that emits a beacon message where their advertisement
packet is a manifest of the message it contains (e.g. NDEF). Or it can
transmit the full message over a period of time (But you need to hang
around to get the full message). Of course if interested, you can poke to
broadcast the full content.

What's the use of such tags? Well I imagine it is similar to how NFC tags are used in real life.  Sharing phone numbers, webaddresses, contact details, small text files, small html pages (Maybe a person want to have like a "portable home page?"), etc... Basically stuff you can shove into under 1kb NFC tag. (Could be bigger for BLE tag, upon request)

Only issue of course, is getting everyone to recognize such tags. Which is where maybe the physical web project could help.

**Comment by scottjenson** [comment]
The answer to this is very similar to the thread on #413

**Comment by pzboyz** [comment]
Agreed the answer is very similar.

The 'portable home page' idea has been in existence for a very long time, remember when phone use to have IR ports on them? Well IrOBEX is the basis for OBEX over Bluetooth, see GOEP. Essentially you have a .vcf file which has all your 'portable home page' information in it.

**Comment by scottjenson** [comment]
Yes but this all feels a bit academic. The issues involved in 'local caching' (described previously) are still there. Our goal with this project is to get something simple working. While these new technologies are possible, it's still not clear they are desirable/convenient/useful. Again see my previous answers.

**Comment by scottjenson** [comment]
Happy to keep discussing this but as comments have stopped, closing for now. Please feel free to reopen.
