### ISSUE TITLE
Desktop Beacon Scanner?

### ISSUE THREAD

**Issue by derekshull** [google/physical-web#420]
Is there a chrome extension or an application that can detect beacons around your laptop?

**Comment by don** [comment]
Try https://github.com/sandeepmistry/node-uri-beacon-scanner

**Comment by ukBaz** [comment]
@derekshull if I understand your question correctly you might be looking for this:
https://github.com/WebBluetoothCG/web-bluetooth/blob/gh-pages/implementation-status.md
There is a demo at:
https://youtu.be/4WYB6mL4AMY

**Comment by derekshull** [comment]
I believe the node scanner should work.  The web bluetooth feature is great though.  I believe that's the API used to create the URiBeacon remote controlled car.  Thanks all!
