### ISSUE TITLE
Build failed - iOS 

### ISSUE THREAD

**Issue by tenente22** [google/physical-web#464]
I have the following problem in the file UBUriBeaconScanner.m:

physical-web-master/ios/PhyWeb/uribeacon/UBUriBeaconScanner.m:165:23: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

```
  BOOL applicationActive =
      [[UIApplication sharedApplication] applicationState] ==
      UIApplicationStateActive;
  _bluetoothOnOrConnected =
      [_beaconsCentralManager state] == CBCentralManagerStatePoweredOn;
  if (applicationActive && _bluetoothOnOrConnected) {
    _state = STATE_IDLE_ON;
  } else if (applicationActive && !_bluetoothOnOrConnected) {
    _state = STATE_IDLE_OFF;
  } else if (!applicationActive && _bluetoothOnOrConnected) {
    _state = STATE_INACTIVE_IDLE_ON;
  } else if (!applicationActive && !_bluetoothOnOrConnected) {
    _state = STATE_INACTIVE_IDLE_OFF;
  }

  [[NSNotificationCenter defaultCenter]
      addObserver:self
         selector:@selector(_didBecomeActive:)
             name:UIApplicationDidBecomeActiveNotification
           object:[UIApplication sharedApplication]];
  [[NSNotificationCenter defaultCenter]
      addObserver:self
         selector:@selector(_willResignActive:)
             name:UIApplicationWillResignActiveNotification
           object:[UIApplication sharedApplication]];
```

What can I do? Thanks.

**Comment by dinhviethoa** [comment]
Thanks for the report. We're taking a look at it.

**Comment by dinhviethoa** [comment]
Are you embedding the code of UriBeacon inside your own app?

**Comment by tenente22** [comment]
Yes, soon. 

For the moment I just wanted to test the code on my device! I had to manually import the project SDWebImage and UriBeacon, since they weren't included in PhyWeb.xcodeproj

I await news! Thanks a lot!

**Comment by dinhviethoa** [comment]
Could you try to run these after you cloned the repository?

```
$ git submodule init
$ git submodule fetch
```

**Comment by tenente22** [comment]
OK done.

Now cloning the repository instead of downloading it, I do not have that problem and I can launch the app on the simulator.

But I can not launch the app on my device because I don't have the iOS developer account and I can't do it either with Xcode 7 beta as I have the following problem:

Failed to sign code "today".

No valid signing identities (ie certificate and private key pair) matching the team ID "A2PMJ2T6DQ" were found.

Xcode can attempt to fix this issue.

I tried to do fix this issue, but it didn't work, of course:

Unable to find a team with the given ID Team 'A2PMJ2T6DQ' Which you belong to. Please contact Apple Developer Support Program.
https://developer.apple.com/support

For the moment, thank you very much!

**Comment by dinhviethoa** [comment]
It's not a Physical Web issue. It's an issue related to Xcode and signing. Here is not the right place to ask.
Please take a look at stackoverflow.
Closing this issue now.
