### ISSUE TITLE
Restaurant Number Github? 

### ISSUE THREAD

**Issue by derekshull** [google/physical-web#470]
saw the YouTube video of using service workers to notify the user when then number is called for a restaurant. Is there a repo with that code? I'd love to see an example of using the service worker. Thanks!

**Comment by mmocny** [comment]
@matthewsibigtroth has been working on this demo (I really like it, too!).  I'm not sure where it is hosted at the moment.

**Comment by dermike** [comment]
Where is the video @derekshull ? :)

**Comment by derekshull** [comment]
https://www.youtube.com/watch?v=b0GDk-53fTo

**Comment by scottjenson** [comment]
This was the original demo that motivated us to build "Bob's Deli" example:
https://github.com/sandropaganotti/no-queue

**Comment by scottjenson** [comment]
We done here? Closing. Please reopen if needed.

**Comment by NicolasMatus** [comment]
Hello! Is this code still available?

**Comment by IvesFNC** [comment]
@scottjenson Hello!!, Is this code still avaible?.. Greetings from Chile.
