### ISSUE TITLE
Support WiFi SSID containing URLs

### ISSUE THREAD

**Issue by jonasevcik** [google/physical-web#477]
It would be useful to use SSID of a WiFi AP to be in a form of URL, or in a form containing a URL. In that way, shops or restaurants can turn their existing APs easily into beacons.
It will be more approachable to people, since they don’t need to have Bluetooth activated, the only thing needed is just a passive WiFi scanning.
A little drawback may be that this approach wouldn’t probably work on iOS.

**Comment by scottjenson** [comment]
Supporting wifi is indeed a very interesting idea and we're looking at it. As you say, the biggest downside is that it doesn't work on iOS which is really a drag as we're trying to do something that works for everyone.

The only other issue is that there would be no encoding possibilities so the URLs would need to be fully enumerated so you'd need "https://www." in each one which burns up a bit of space (and we're encouraging https for URLs if at all possible)

**Comment by jonasevcik** [comment]
For iOS, there is at least a possibility to get the SSID for the network the device is connected to: http://stackoverflow.com/questions/5198716/iphone-get-ssid-without-private-library

Well, the "www." part could be omitted, if you use URL shortener for encoding the original URL.

I created a sample project to demonstrate "WiFi beacon" capabilities. APs can be used entirely in a Bluetooth beacon fashion. You can check it out at: https://github.com/jonasevcik/Android-WiFiBeacon-demo

**Comment by scottjenson** [comment]
Very cool! Thanks for sharing. I agree with you that the length issues are fairly trivial. I hadn't thought that you could use signal strength as a rough relative comparison tool. 

As to the iOS issue of getting the network you are connected to, I agree of course, that would easily work but it feels very limited. For any public use case, it's not as useful as you wouldn't be connected to anything first.

If we proceed with this we should be clear: we'd be doing this only for Android as that's the only version where it actually works properly. We can make a hack for iOS but it would be a pale shadow of the primary implementation.

**Comment by dinhviethoa** [comment]
Also, I think that choosing the AP we want to connect to on iOS via an app is an other issue.

**Comment by jonasevcik** [comment]
@dinhviethoa sadly, iOS is overrestrictive in this matter.
@scottjenson even only on Android, it can give an added value to its users. If it makes sense, I can prepare a new branch with its implementation.

**Comment by bramvdh** [comment]
How about supporting the recently announced Wi-Fi Aware for beaconing?
They claim it will work on iOS as well

http://www.wi-fi.org/beacon/rolf-de-vegt/wi-fi-aware-a-platform-for-proximity-based-wi-fi-innovation

**Comment by scottjenson** [comment]
Any standards based tech that we can use is alway interesting. My concern with Wi-Fi aware is that, at least according to this (http://p2pkit.io/blog.html) it requires a chipset upgrade and changes to the OS. So it's still aways out.

One of the reasons we picked BLE and mDNS (for our initial tech to use) was that they were open, and well supported. We're happy to explore new approaches/technologies but, like any project we need to stay focused. Both wifi aware, and even the original wifi scanning that started this issue, are very much worth looking at, but they aren't as widespread as BLE/mDNS.

**Comment by scottjenson** [comment]
@jonasevcik Thanks so for raising this issue. It has spurred quite a discussion within the team. Given that we already support mDNS, we already have a strong solution that works over wifi. It has the added benefit of carrying not only the URL, but TITLE and DESCRIPTION information as well (well... not just yet, we're adding it soon). This is especially important for devices broadcasting a local URL. None of that is really possible with an SSID solution.

An additional concern is that the SSID solution pretty much kills a wifi device from using the wifi radio for outbound data (it can only pretend to be an AP so can only accept connections). This SSID idea is very clever and it allows you to setup wifi beacons easily but with mDNS you can broadcast AND use your wifi to connect the device. 

We've discussed this internally quite a bit and we were very impressed that not only did you post the idea but you also did a pull request! Very much appreciated but we're going to keep wifi to mDNS for now.

Scott

**Comment by jonasevcik** [comment]
@scottjenson I was afraid you would write that:) I guess, we can close this issue now.
Let me know, if I can be of any (hopefully relevant) assistance.
Jonas
