### ISSUE TITLE
Weird concatenation of title+description

### ISSUE THREAD

**Issue by cco3** [google/physical-web#486]
http://headlabs.tumblr.com/post/125427766244/testing-the-physical-web-with-eddystone
See: "Head Sorry, your browser is not supported…"

I can't find exactly where this would happen, so we're going to have to duplicate the issue and debug.

**Comment by dermike** [comment]
Isn't that because of the:
´<span class="offscreen-text">Head</span>´?

**Comment by dermike** [comment]
´<span class="offscreen-text">Head</span>´

**Comment by dermike** [comment]
Isn't that because of the:
<span class="offscreen-text">Head</span>

**Comment by dermike** [comment]
Isn't that because of the:
```html
<span class="offscreen-text">Head</span>
```

Sorry for the fails of pasting the code :P

**Comment by cco3** [comment]
Yes!  You win!  Now I'm not really sure what we should do here.

**Comment by cco3** [comment]
Nm, let's just close this.

**Comment by scottjenson** [comment]
Yeah, it's a pretty odd case that doesn't happen that often. Interesting that it showed up on Tumbler, where they may not have much choice. However, that markup is.... less than ideal.

**Comment by cco3** [comment]
Well, their url was some other site, not tumblr.
