### ISSUE TITLE
Link in the repository description doesn't work

### ISSUE THREAD

**Issue by tarikozket** [google/physical-web#493]
It needs to be changed with "http://www.physical-web.org"

**Comment by scottjenson** [comment]
It's actually a valid URL. I just tried the link w/ multiple browsers and it worked fine. Is it failing for you?

**Comment by tarikozket** [comment]
Yes it's failing somehow. Here is the video: https://www.youtube.com/watch?v=_-LsGpU5GRA&feature=youtu.be

- Checked with Safari and fails there too.
- Checked with my iPad on the same Wi-Fi and it failed too.
- Checked with my iPhone with cellular network and it failed too.

When I try to ping "physical-web.org" it outputs like the below:

`Request timeout for icmp_seq 0`
`36 bytes from any-in-2015.1e100.net (216.239.32.21): Destination Port Unreachable`
`Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst`
` 4  5  00 5400 2bf4   0 0000  3e  01 9578 192.168.1.144  216.239.32.21`

**Comment by tarikozket** [comment]
I'm in Turkey for a couple of weeks and I think there is a nationwide issue with the 216.239.32.21 IP address. As "www.physical-web.org" goes to another IP address, it works. :no_mouth:

**Comment by cco3** [comment]
That's super weird.  Do you have an estimate on how many people are actually effected?  If this is just a temporary issue, I'd rather just leave it as is.

**Comment by scottjenson** [comment]
We've tried this from a range of computers and it works just fine. It certainly looks like your router (or something similar) is acting up. Closing for now but if you have any more information on this, please let us know.

**Comment by tarikozket** [comment]
I researched and found that Government of Turkey has blocked that IP with some other IP's because a website was streaming a live soccer match illegally using Google Services. So, it's a nationwide problem in Turkey.
