### ISSUE TITLE
Changing URL in Android App

### ISSUE THREAD

**Issue by coomby** [google/physical-web#495]
Using CSR1010 Tag board with Physical Web - proven working with Eddystone Android authenticator app.
Using Android 5.1 this is the workaround i have use to change the URL:

This is the only way I can program a URI into the beacon and have it show:-

1. Run Eddystone Android Authenticator App first. This ends up putting a https://www. weblink in the beacon which is picked up by the Physical Web Android App...
2. Downoad Blesh Physical Web App - https://play.google.com/store/apps/details?id=com.blesh.physicalweb&hl=en_GB
3. Continue as Guest then use their Config Uri button to enter new Uri into Beacon
4. Revert back to "standard" Physical Web App to view Beacon Uri being shown.

If ever you try to program Url with the Physical Web App alone it ends up not being discovered.

So yes looks like a bug in the Physical Web Android App..

**Comment by g-ortuno** [comment]
The Physical Web app doesn't do the configuration itself. It uses the UriBeacon library. I opened an issue on that repo to track it there:

https://github.com/google/uribeacon/issues/258
