### ISSUE TITLE
Minimum and maximum advertising rate

### ISSUE THREAD

**Issue by 079krutarth** [google/physical-web#499]
I am designing a custom URI beacon it would help a lot if i can know the limits of the app for the advertising interval. How slow or how fast  one can advertise and still get the app to work with the beacon.
Although this is not an issue i could not find any documentation regarding this so had to post it here.
Thanks for the help in advance.

Thanks and Regards,
Krutarth

**Comment by cco3** [comment]
This is highly dependent on the device and OS being used.  Our current recommended interval is 700ms.  Is there something in particular you are trying to accomplish?

You may also want to check out:
https://github.com/google/eddystone/tree/master/eddystone-url

**Comment by cco3** [comment]
I'm closing this issue, but feel free to follow up with more comments.

**Comment by 079krutarth** [comment]
Yes I would like to have advertising interval of 1000ms if possible. Can
you tell me would it be feasible for latest IOS and Android OS.

Thanks and Regards,
Krutarth Rami

**Comment by cco3** [comment]
1000ms is what we were using for a while, so yes, it's feasible.  It's just not ideal if you want the device to notice the beacon quickly.

**Comment by 079krutarth** [comment]
Thanks a lot for your prompt reply. Will see if this works out for my
application.

Thanks and Regards,
Krutarth Rami
