### ISSUE TITLE
Point to new node.js Eddystone scanner 

### ISSUE THREAD

**Issue by scottjenson** [google/physical-web#502]
@dermike I just found this [Eddystone-scanner](https://github.com/sandeepmistry/node-eddystone-beacon-scanner) which feels rather complete. Would you mind us modifying your nodejs/read.me and just point to this repo instead?

**Comment by dermike** [comment]
I didn't create it, so I wouldn't call it mine. :)

**Comment by scottjenson** [comment]
I'll take that as a "don't mind" then ;-)

**Comment by dermike** [comment]
Yeah, it definitely needs an update after Eddystone

**Comment by scottjenson** [comment]
Cool, I'll make the changes now.
