### ISSUE TITLE
Concept

### ISSUE THREAD

**Issue by ihmunro** [google/physical-web#504]
Hi There

You mention this is just going to be a concept, does that mean you will pull the App from the App Store ? and use Chrome on a go forward basis ?

Iain

**Comment by scottjenson** [comment]
The app is for developers. It's also our open source implementation for others to use and learn from. We're hoping that many other versions of the app, on other platforms will get written.  So no, once we ship Google's version, we will keep the 'github version' up

Scott

**Comment by ihmunro** [comment]
Perfect - thanks Scott and keep up the good work with the Physical Web - things are looking good and I am excited to see where you take us. 
I also emailed Hoá this morning as I cannot get this project to build. 
I love in Calgary, so if you are ever up this way, let me know. 
Iain

Sent from Outlook




On Fri, Sep 11, 2015 at 7:49 AM -0700, "scottjenson" <notifications@github.com> wrote:












The app is for developers. It's also our open source implementation for others to use and learn from. We're hoping that many other versions of the app, on other platforms will get written.  So no, once we ship Google's version, we will keep the 'github version' up



Scott
