### ISSUE TITLE
crash in PWBeaconManager.m:331

### ISSUE THREAD

**Issue by ihmunro** [google/physical-web#505]
Hi There

I have added in the 2 of the three projects missing from this project - MBProcessHUD and SDWebImage, however, when trying to add the Uribeacon project, the Physical Web App for IOS will still not build.

Does anyone have any ideas as to how to get this working ?

Iain

**Comment by mmocny** [comment]
I just tried this from scratch for sanity:

`
$ cd physical-web
$ git pull --rebase --prune && git submodule update --init --recursive
$ open ios/PhyWeb.xcodeproj/
`

Then when XCode opens (I'm using 6.3.2) I select the `PhyWeb` build target and build.  There are a few warnings, but runs fine with no additional steps.

May you check your build target, check your xcode version, and check the output of `git submodule status`, please?

**Comment by ihmunro** [comment]
Hi Michal

Many thanks for the response.

Apologies, but I have no clue with the git stuff.

I also started from scratch - deleted the existing files, redownloaded, then went to terminal and am now sitting at:

Iains-iMac:physical-web Iain$ 

I did do a git init to get the repository setup, but I get nothing but errors when trying to get things going, which means I am probably doing it incorrectly.

As I said, I have never really used any of the git commands - I typically just download the zip file - the most I have done with git is over the last two days trying to get this App up and running, so if you could spare the time to spell it out, I would really appreciate it.

Iain

**Comment by ihmunro** [comment]
Hello Michal

Spent some time looking around and have got this far now:

Iains-iMac:physical-web Iain$ git pull git://github.com/google/physical-web.git 
remote: Counting objects: 6988, done.
remote: Total 6988 (delta 0), reused 0 (delta 0), pack-reused 6988
Receiving objects: 100% (6988/6988), 8.38 MiB | 1.85 MiB/s, done.
Resolving deltas: 100% (3485/3485), done.
From git://github.com/google/physical-web
 * branch            HEAD       -> FETCH_HEAD
Iains-iMac:physical-web Iain$ ls
CONTRIBUTING.md	LICENSE		android		ios		travis
CONTRIBUTORS	README.md	documentation	nodejs		web-service

this piece is giving me grief:

--rebase --prune &&


Iain

**Comment by ihmunro** [comment]
Hi Michal

Have been getting somewhere at least lately, but still not complete, as the three xcode projects are still missing.

I did a status check and got the following:

Iains-iMac:physical-web Iain$ git submodule status
-28c44be41399e474ed959269e2364be0047ad8eb ios/PhyWeb/third-party/MBProgressHUD
-0aa9b61bcca20ef3e389bc46aee3ebfbbca362bd ios/PhyWeb/third-party/SDWebImage
-b6576878d5e2a207e0122dae3663979ebf0e1d1f ios/PhyWeb/third-party/SVPullToRefresh
-11616693b00e4edeba3f9eac9f39cdc7baf4fffd ios/PhyWeb/third-party/uribeacon
 0b65609dc06ec4681daeb5a8db3f59ac241f3b0d uribeacon (uribeacon-final-3-g0b65609)

**Comment by ihmunro** [comment]
Hi Michal

Got it working - all is good now.

Wow, those git commands are powerful.

Thanks so much for the pointers.

Iain

**Comment by mmocny** [comment]
Awesome, so glad you have found success.

Yes, `git` is powerful and worth taking a bit of time to learn.  It looks liek github has a cool little git course: [try.github.io](https://try.github.io/), which I suggest you try out.

Good luck!

**Comment by ihmunro** [comment]
Thanks again - I will definitely take a look at the course for sure.

I got the App to build in the Simulator with no issue - eventually got it running on the App - but it crashes. I did upgrade to Beta 7 Five, with IOS 9, so that may be an issue.  

Will the project be upgraded to IOS 9 ?

The crash occurs at line 331 of PWBeaconManager.m with signal SIGABRT.

2015-09-13 11:32:35.299 PhyWeb[447:1917450] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 1 beyond bounds [0 .. 0]'
*** First throw call stack:
(0x1866f5a94 0x19b04ff80 0x1865dba48 0x100057490 0x10004df58 0x10004e38c 0x185fa29c8 0x185fa2958 0x185fa2acc 0x185e0e6ec 0x185efcd1c 0x100185dcc 0x10018f4f8 0x185dfaed4 0x1865d92cc 0x185dfadb8 0x185dfac78 0x185dfaaa4 0x1866ad0dc 0x1866acb70 0x1866aa870 0x1865d98a0 0x191634088 0x18bc6e0d4 0x100050b1c 0x19b89e8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

Iain

**Comment by dinhviethoa** [comment]
Thanks. I'll fix it tomorrow.

**Comment by jeffprestes** [comment]
Hi Michal,

I had solved the dependencies manually because I didn't know the projects were linked to their github repo. It's great! Can I submit a pull request to the README.md to let this information more explicit? I am a Git user but I didn't know this feature was set to this project.

And one more thing, when I've tried your command I got this error:

Cloning into 'Vendors/libwebp'...
fatal: http://git.chromium.org/webm/libwebp.git/info/refs not valid: is this a git repository?
Clone of 'http://git.chromium.org/webm/libwebp.git' into submodule path 'Vendors/libwebp' failed
Failed to recurse into submodule path 'ios/PhyWeb/third-party/SDWebImage'

Thanks!

**Comment by dinhviethoa** [comment]
I also fixed the issue with the submodule.

**Comment by ihmunro** [comment]
Thanks Hoà

Do I run the github stuff to download everything or are there specifics 
I need to update ?

Thanks for fixing.

Iain

**Comment by jeffprestes** [comment]
Hi Hoà,

it brought the source code from the dependencies however the project itself
has the old references. So, I had to remove project referencies and add the
files to the project (you can see it here:
https://github.com/jeffprestes/physical-web/blob/master/ios/PhyWeb.xcodeproj/project.pbxproj
)

I wonder how is it on your environment and I'd like to know if there's
another alternative to it.

Thanks in advance!

-Jeff

2015-09-14 15:56 GMT-04:00 ihmunro <notifications@github.com>:

**Comment by dinhviethoa** [comment]
Could you also try to clone the repository from scratch? It sounds like submodule support in git doesn't work perfectly.
Also, could you give more specific details about what doesn't work for you?
