### ISSUE TITLE
Hardware compatibility

### ISSUE THREAD

**Issue by rafaellopes** [google/physical-web#510]
Is it compatible with Gimbal beacons? I'm trying to use it with Gimbal, but isn't finding any.

**Comment by christopherdro** [comment]
Gimbal beacons are based off Apple's iBeacon protocol. As far as I know, Gimbal doesn't currently support the Eddystone protocol.

**Comment by scottjenson** [comment]
Correct, you can't use an iBeacon with the Physical Web

**Comment by g-ortuno** [comment]
From their site:
`Gimbal beacons with iBeacon™ technology, and soon-supporting Eddystone™...
