### ISSUE TITLE
Support for non-http/s links?

### ISSUE THREAD

**Issue by edent** [google/physical-web#520]
I'm aware that this is the Physical **Web** project, but I was curious about support for URI schemes other than `http:` and `https`

For example, I tried adding a `mailto:` URI to the Android app, it was shortened to http://goo.gl/NbFVqx which ([as you can see](goo.gl/NbFVqx+)) adds `http` to the start and rather mangles things.

Similarly trying to add `bitcoin:`, `ftp:`, `sms:` etc. all break.

I assume that if I want my cat's collar to point to a phone number, I should point the URI to `http://example.com/lost-cat` and then 302 that to `tel:+447700900231`?

Is that the case for all these "exotic" protocols?  Send the user to the web and then redirect them?

I'm aware that there are [dozens of registered URI schemes](http://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml) and not all can be supported.

**Comment by scottjenson** [comment]
This is a very fair question and one which we've thought about quite a bit. We too initially thought that it could be ANY URL and expected a wide range of URLs could be used. The problem we discovered, and we're still happy to discuss this, is that these URL contain no user level information. What do you actually show people in the scanner app? For example, if I point to a bus stop web page, if it's a web page, I can show it's Title and a snippet in the scanner. If I have a bitcoin address, I can ONLY show the address. What if I see 4 bitcoin addresses at the same time? How can I tell which one to choose?

For this reason, we've been suggesting that for non web page URLs, point to a simple web page that contains that link. This lets you wrap it with descriptive information. It's a quick page to load and the link there can indeed be (for example) a tel: link and can dial the phone.

So we are hoping that you CAN have any URL scheme you want, it's just a bit better to wrap it in a simple webpage so it's a bit more descriptive. If there is another way to get this metadata for each URL, we're happy to discuss it. We'd just rather not reinvent something when a simple open web standard exists.

Scott

**Comment by edent** [comment]
Those are very fair points.  In addition (and how I *hate* arguing against myself) not every device has a telephone (tablets) or email client (non-configured phones) or BitCoin wallet (99% of devices!).

While there may be some merit in offering URls for non-data services for devices out of data coverage (WTAI USSD, phone, SMS) those are likely to be minority pursuits.

Yes, pointing to a website and then offering a choice / automatically launching an app via intents makes more sense.

**Comment by scottjenson** [comment]
OK, then I'll close this topic for now. However, this topic is always open for discussion. If you have any additional thoughts, feel free to open another issue.
