### ISSUE TITLE
Can physic web app scan in background of android and ios 

### ISSUE THREAD

**Issue by zentechthaingo** [google/physical-web#560]

**Comment by scottjenson** [comment]
No. We talk about this on our [FAQ page](https://github.com/google/physical-web/blob/master/documentation/introduction.md) We want users to be in control so they will only see devices when they ask. This is in strong contrast to the iBeacon model, which *does* scan in the background (mostly for the purpose of notifying users)

However, the critical difference is that with iBeacon, you must install an app first which is an opt-in to that group of beacons. With the Physical Web, as you see EVERYTHING, it would not be wise to opt users into that as it would quickly escalate into a horrible spammy model and everyone would turn it off.

However, with things like service worker, it's possible to have the equivalent of this opt in. Once you are on a page you can activate the service worker which can offer push notifications and eventually background beacon scanning (but we are waiting for better BLE background scanning efficiency before turning that on)

That being said, the whole purpose of making the Physical Web open source was to encourage experimentation. If you feel there is a way to do background scanning and not create a horrible spammy mess, you are encouraged to give it a shot. Once the Physical Web ecosystem gets going, we hope many different scanners are built and tried.

**Comment by zentechthaingo** [comment]
Thank you very much, I will try that :)

**Comment by derekshull** [comment]
I'm torn on this but I really lean towards what Scott says, because it's very true. I don't want things buzzing me every time I come close to a beacon. Our beacon app, is scanning in the background but isn't buzzing or notifying people. It simply puts something on the users lockscreen that says "There are X beacons around you" just so the user knows that there is something if they want to check it out. 

No buzz, no dings, but it still let's the user know they can do something. This is our compromise for now.

**Comment by scottjenson** [comment]
Thank you Matt that is an important distinction. I assumed the reason for background scanning was to interrupt. If you were to do a silent notify, that clearly calms the issue.

However, if you are only doing silent notifications you then need to discuss the likely battery drain you'll incur.

We scan only when the phone wakes up as the user can only use the notifcations if the phone is awake. This saves significant battery. This isn't perfect of course but we're trying to be a bit conservative, we don't want to be labeled as a battery hog. As it stands, our current battery drain is negligible.

**Comment by derekshull** [comment]
True, thanks Scott!  I'm going to check with our developers to ensure that's happening.

**Comment by scottjenson** [comment]
closing as this seems to have reached a natural close
