### ISSUE TITLE
Native physical web support in Android

### ISSUE THREAD

**Issue by febinsathar** [google/physical-web#563]
Can anyone provide any information regarding when physical web will be supported natively in android. When I read around people are speculating it might release via Chrome browser, Play store or it can even be released along android M. But after android M launch I didn't find any further update. I also found that  Opera R&D had released a labs build of Opera for Android (APK, 30 MB) with URL beacon detection. But if we need to put out a product in physical web in production how long should the developers need to wait such that physical web would be available in android natively.

**Comment by scottjenson** [comment]
As there are changes to Android happening to make the scanning more efficient, it's taking a bit longer than we'd like but it's definitely coming. I'm sorry but we can't give exact dates, just know that we're working very hard on getting this out as fast as we can.
