### ISSUE TITLE
Related link, er, discovery

### ISSUE THREAD

**Issue by danbri** [google/physical-web#564]
There have been a few Physical Web -related articles/papers/projects recently e.g. 

* http://arxiv.org/pdf/1510.04951v1.pdf
* http://www.slideshare.net/yiibu/imagining-the-physical-web
* http://beaconintelligenceblog.com/2015/09/the-4-massive-advances-you-will-make-with-the-physical-web/
* http://beaconintelligenceblog.com/2015/10/5-ways-the-physical-web-will-move-beyond-beacons/
* https://passkit.com/physical-web/
* https://dev.opera.com/articles/release-the-beacons/

It would be great if these kinds of thing were more discoverable via https://google.github.io/physical-web/ than they are now, without creating a maintenance burden. Any suggestions? Should we send pull requests against the gh-pages branch https://github.com/google/physical-web/blob/gh-pages/index.html ... or scribble in the Wiki? Buffer them in the issue tracker as I'm doing here? The homepage doesn't do justice to the traction this thing is getting...

**Comment by scottjenson** [comment]
We're starting to push every article we find to the [Physical-Web-Discuss email list](https://groups.google.com/forum/#!forum/physical-web-discuss). This is a public google group that anyone can join. What I like about this approach is that it can turn into an interesting discussion after the article is posted. That work?
