### ISSUE TITLE
Split packet for longer urls?

### ISSUE THREAD

**Issue by mofosyne** [google/physical-web#566]
Wonder how practical it is to split a url over multiple advertisement packets, broadcast in a cyclic fashion.

It means you have to hang around a bit longer to receive the full url, but that may not matter in certain use cases. (what's the advertisement detection speed?)

Perhaps it also provides other opportunities to send extra description packets to describe the url as well (e.g. a key value list of metadata)

**Comment by cco3** [comment]
It's possible, but as you noted, it takes a while for the client device to pick up the advertisements.  A lot of packets get dropped depending on the environment and distance of the beacon.

Redirectors handle the problem of long urls.  Schema.org, html metadata, and manifest.json solve the problem of adding extra metadata.  Sticking with only needing one BLE advertisement is the way to go for now.
