### ISSUE TITLE
Physical Web and the GeoWeb

### ISSUE THREAD

**Issue by prushforth** [google/physical-web#578]
Hi, 

I notice things have gone quiet here, but I was wondering if there might be some collaboration opportunities between the Physical Web project and the Maps for HTML concept.

In a merged Physical Web - [GeoWeb/Maps4HTML](http://maps4html.github.io/Web-Map-Custom-Element/) world, I could see the URL of a device returning an HTML page with (among other things) a map element which identified its location.  That would be pretty cool, I think.

Nice idea here guys.  I especially like the Web concept, as it is a standard we can all rely on.  Hopefully it will include maps one day. 

Cheers,
Peter Rushforth

**Comment by cco3** [comment]
Could you explain why this can't be done now with the Physical Web as is?  You can already tap on a URL that goes to a page with your map element.

**Comment by prushforth** [comment]
I replied by email but something must be awry... here's my response.

Hmm.  Don’t want to waste your time, I’m looking around for use cases for maps for html.

I guess I don’t understand the Physical Web architecture right now.  It’s an app, right?  I guess
the eventual target environment is a web browser?    Web / Browsers span platforms, therefore
the Web is ideal.

I was thinking a Physical Web thing would have a web server in it, that would be available 
only to devices that were near it.

A phone could connect to a nearby Physical Web device, and the Web browser on the phone
could be used to access the device.  Today’s web browsers don’t support HTML with a Web map,
they only support JavaScript which delivers maps to them.  Currently there’s no standard way to encode
a location in a web page.  A new map element would achieve that.  But yes, it would also
be possible today with the prototype web-map custom element.

The Physical Web thing, whatever it is, could encode its ‘original’ (or any other) location on a map
in a web page.  The map could reference any standard map service, which had context appropriate
to the device (could be google or any other MapML map).  If at the time of  Physical Web connection, 
the device was not at its original location,  the difference would / could be shown on the map 
on the user’s phone ( via geolocation api).

**Comment by cco3** [comment]
Currently we don't have any Physical Web devices that also run a web server...there's a lot of issues there that need to be solved there (how do you establish a network connection to a device without losing your current wifi internet connection?).

What I think you are describing can be handled just fine with shorturls that link to a specific location on a map.  There doesn't need to be a standard way to encode a location in a web page...any URL format will do.  When the user accesses the map in the browser, the location api can correct the location if it's wrong.

**Comment by prushforth** [comment]
> how do you establish a network connection to a device without losing your current wifi internet connection?

No good advice from me there.  If the target env is Web, maybe would have to be mediated by the user's browser. Maybe the browser could proxy the Physical Web network / http into current wifi / cell connection in the browser app.

> shorturls that link to a specific location in a web page...any URL format will do
URLs are opaque, semantics only understood by the author/owner. Therefore such locations can't be understood by crawlers, so the Web site of the Physical Web device would not geolocate.  I appreciate we will have a different point of view on this.

> on a map

MapML supports global WGS84 coordinates, not just coordinates between +/-85 lat, as well as different projections and different map sources.  Again, possibly something that won't be resolvable for this conversation.

Thanks for your time!
