### ISSUE TITLE
Using PWS makes broadcasting URLs redundant

### ISSUE THREAD

**Issue by pipacs** [google/physical-web#581]
As discussed in #488, the Physical Web Service is used to filter out spam/fishing/malware sites. But what's the point of broadcasting an URL then in the first place? 

Instead, PWS could just return a safe URL based on the beacon UUID.

This approach could give the following benefits:

- Closes the security vector of rogue URLs
- Beacon deployment would be quicker: no need to set the URL by re-flashing
- Physical Web would gain compatibility with simpler, non-Eddystone beacons

**Comment by mmocny** [comment]
Our use of a PWS is just a policy decision, not a requirement.  We just do it to give some protection to users who use our app.

Other clients are free to show the raw URL (I do this for debugging or local-intranet-only content), or use their own PWS concept.  By broadcasting the raw URL value in the beacon, and not relying on an central service for lookup, we solve an important problem: interop with other clients, and do so without introducing a new protocol.

Also, I think that your three bullets are not at all solved by UUID usage:

* Still requires security review of URLs on the UUID server, which would use the same systems as a PWS.
* Updateable beacon deployment can also be accomplished with mutable short-urls for redirection (See #575 which just brought this up recently), which is just as quick.
* How are other beacons simpler?  We are totally open to using other formats for URL embedding, and have already prototyped mDNS and wifi beacons.

That said, there are certainly some benefits to leveraging UUID, and we are open to discussing them, but I personally am not convinced about the above three.  You should also mention any tradeoffs.
