### ISSUE TITLE
Physical web native on android when?

### ISSUE THREAD

**Issue by BleMot** [google/physical-web#582]
When it will be available natively the physical web on android?

I find myself developing a product for the physical web and beacons.

Thank you.

**Comment by scottjenson** [comment]
We are working as fast as we can! We're getting close to releasing this on Chrome for Android and hope to give you good news soon but as with any software project, there can be unexpected delays so, if you don't mind, we're being a bit conservative. We are VERY aware that people would like us to ship ASAP and we're doing our best to get it out.

**Comment by WebDoin** [comment]
Thank you very much for your reply. 

Just a question, It will be a native application on android or be included in chrome?

**Comment by scottjenson** [comment]
Our plan is to release it in Chrome for Android, just like we did for for iOS. We'd like to encourage other browsers to be released as well. Opera Labs has already come out with support for the Physical Web and we're very excited and supportive of work like this.

**Comment by tolson2000** [comment]
@scottjenson Did I miss something along the way. Originally, the PW APP function was proposed to be part of the operating systems. A browser wouldn't come up unless someone clicked on a link. Now it will have to be an integrated part of browsers to make it work. Shoot. For that I don't see a problem with it remaining an independant APP then. But, I don't know everything that you do. What happened to change the philosophy?

**Comment by scottjenson** [comment]
No, we never mandated that. There was blog post recently (no longer have the link) pointing to our wording on the GitHub page 'proving' that we wanted it to be in the OS. That was a very overly enthusiastic reading of the text. That phrasing was never meant to be literal. It certainly *could* be part of the OS, and we're not against it, but it just as equally could be part of an app. I'm going to go edit that right now just to make sure that misunderstanding doesn't keep happening.

I thought us shipping the Physical Web for Chrome on iOS was a pretty clear sign that we think it's a good approach to be part of the browser. It's a more open approach as it encourages others (such as Opera) to come join the party. Just as Android doesn't restrict other browsers being installed on it's OS, the same is true for the Physical Web. Having more Physical Web scanners on a device will likely encourage more experimentation and choice. This is how good open systems evolve and learn.

This could change over time, but we've always targeted Chrome as our initial release target.

**Comment by tolson2000** [comment]
Hey, thanks for the explanation Scott. I just figured the integration into a browser was the easy way to provide the PW on workstations OS's like Linux, Windows, OSX, etc. But the PW on smart mobile devices like cell phones, pods, and pads would still be built-in. I do hope if it is in Chrome/Opera/etc that it is in the workstation versions and not just in the mobile versions.
thanks again,

**Comment by mmocny** [comment]
Also keep in mind that while the feature may be implemented in a browser (or other app), the actual UI surface area will be working with the available capabilities of the platform.

What I mean is that e.g. Physical Web for Chrome on Android shows an Android notification when beacons are nearby, opens a dedicated Android Activity when tapped, and only opens a browser tab when the URL is clicked.

Users will not typically notice or care where the feature is integrated, whether built in to the system or as part of an app, though for us deployers there are some interesting technical tradeoffs.

@tolson2000 we do intend to add the feature for all OS targets, but our priority is certainly mobile (which should hopefully make sense given the feature).

**Comment by MaggieLeber** [comment]
Well, Chrome 49 is here on Android, and after enabling the enable-physical-web flag,I got my Eddystone-URL beacon to wake up Chrome. Once.

It still shows on the Physical Web and Eddystone Validator Android apps, but Chrome is ignoring it, even when I change what it's sending.

**Comment by mmocny** [comment]
Closing.  I think the content of the last message is captured in other, newer bugs.
