### ISSUE TITLE
regarding GSoC 2016

### ISSUE THREAD

**Issue by amanbeniwal** [google/physical-web#605]
Hello,
I am a second year student from Indian Institute of Technology,Kharagpur. I have been through the idea page (http://google.github.io/physical-web/cookbook/) . I am really interested in the concept of physical web. 

I wanted to know what is the current status of the project?

As a student how can I contribute to the project?

Thank you

**Comment by kanodia** [comment]
http://physical-web-project.github.io/

**Comment by amanbeniwal** [comment]
Hello,
  
Dear mentor, Thank for replying to my query mail.
I have been through all the suggested links and the ideas mentioned in them.  They were very inspiring and I personally want to contribute to this project. I even have had idea which I thought I can work. 

But I have a small question.

As a student(aspiring for GSoC -2016) how do you want us to work on this project?
 Take one idea and work on it as a hobbyist. or 
Create an api or library which others can use to create there own projects.

Regards 
Aman Beniwal
