### ISSUE TITLE
Chrome 49 on Android only displays Eddystone-URL beacons once?

### ISSUE THREAD

**Issue by MaggieLeber** [google/physical-web#609]
Well, Chrome 49 is here on Android, and after enabling the enable-physical-web flag,I got my Eddystone-URL beacon to wake up Chrome. 

Once.

It still shows perfectly on the Physical Web and EddystoneValidator Android apps, but Chrome is ignoring it, even when I change what it's sending.   

Anybody seeing similar? 

My beacons are being sent with https://github.com/google/eddystone/tree/master/eddystone-url/implementations/linux-url-advertiser from a NextThingCo C.H.I.P.

**Comment by scottjenson** [comment]
Did you swipe away the notification? If so, Chrome assumes you don't want see it any more. It will eventually come back (if you leave the area with the beacon and return)

**Comment by MaggieLeber** [comment]
Pretty sure I tapped on it...But that may have been the initial "physical web" notification instead of the notification for the actual beacon. I took both my mobiles far from home today so we'll see what happens when I get home. If you change the URL is that considered a different beacon?

**Comment by scottjenson** [comment]
Unfortunately not as it likely has the same MAC address. We've got a pending bug fix that will indeed show it when the URL is changed. The sure fire, make sure everything is perfect flow is to 1) open/close chrome 2) Sleep/wake your phone. Keep in mind (at this point) that we only scan on screen wake up to save battery.

**Comment by MaggieLeber** [comment]
Thanks...that's all good info. I'm really excited to explore this tech...and a $9 computer that can host it'its own web services seems like a natural.

**Comment by scottjenson** [comment]
Could not agree more! One of the key differences between the physical web and qrcodes/NFC is that you can interact with the device in front of you. Love to see what you come up with

**Comment by MaggieLeber** [comment]
See https://goo.gl/2t5hBX

**Comment by MaggieLeber** [comment]
@scottjenson Do you happen to have that bug number handy? I'll start tracking is do so as to the know when the fix gets out there...

**Comment by scottjenson** [comment]
That bug is internal to GMSCore (not Physical Web) so not publicly viewable, sorry.
