### ISSUE TITLE
Difficulty in understanding chrome android physical web scanning behavior?

### ISSUE THREAD

**Issue by kanodia** [google/physical-web#610]
Given: Physical web flag is enabled on chrome i.e., chrome on android is ready to scan for physical web

Do we have any certain rules or on the discoverability behavior of physical web on chrome?

For example, chrome on android discovers physical web from an eddystone beacon named as beacon1 . Now say a user has swapped off the physical web notification.

Q1| Will the user discover physical web from the same beacon1 again?
Q2| If yes, are there any conditions, i.e.,
     » if he is in the range of beacon1 more atleast for a specific amount of time?
     » or any time duration in which URL from same beacon will not appear?
_____________________________________

I have faced this issue, so say I have discovered physical web and I have then swapped it off? I have no idea when will I get the URL back again? I keep on opening my chrome, closing it, check for location, turn on/off my bluetooth, switch my screen on/off, and then after all this, somehow magically I discover physical web again.

Hence, these things are important to know, that is the logics behind it's descoverability.

**Comment by scottjenson** [comment]
This is moving target and the rules will change and evolve as we learn more. Presently, we respect if the user swipes away the notification and will not bring it back. If the user leaves that area (all beacons are 'lost') and they return, the notification will return. If however, you have just one beacon near you and you swipe it away and just stay there, it will never come back.

**Comment by kanodia** [comment]
Ah! That clears a lot of doubts. Thanks Scott!
