### ISSUE TITLE
Chrome beta 49 on Android can't seem to detect my URLs

### ISSUE THREAD

**Issue by leopck** [google/physical-web#611]
I'm currently trying the Chrome beta 49 on my Asus Zenfone 2 Lollipop, but I can't seem to get the Physical Web on the Chrome to detect my URLs however, if I use the Physical Web android app version I can detect my URLs.

My beacons are implemented using [https://github.com/google/eddystone/tree/master/eddystone-url/implementations/linux-url-advertiser](url) and I also tried [https://github.com/don/node-eddystone-beacon](url) neither of them are showing anything on my Physical web Chrome version.

So far the only links I managed to see the output on the Physical web Chrome is from these two links
"https://goo.gl/SkcDTN" or "https://www.google.com". If I attempt to send "http://www.google.com" or "http://www.engadget.com", the Physical web Chrome doesn't show it.

I've also tried to use Google URL shortener, but doesn't seem to work either. Am I missing something?

**Comment by dermike** [comment]
@leopck Chrome only shows links over https at the moment

**Comment by leopck** [comment]
I see, is there any plans on supporting http? If yes, when would the support be in?

**Comment by scottjenson** [comment]
There are no plans on supporting HTTP as the Chrome team sees this as a security risk. Most of the web is moving to HTTPS for the same reason.

**Comment by leopck** [comment]
Alright, it's an understandable reasoning. Thank you very much.
