### ISSUE TITLE
Chrome 49 on Android doesn't show detected Urls in the Physical Web view

### ISSUE THREAD

**Issue by torbjornvatn** [google/physical-web#613]
I've installed the new version of Chrome on my Nexus 5.
Then I enabled the Physical Web setting in `chrome://flags` and the widget said it had detected a beacon, but when I clicked the widget the Physical Web view didn't show anything.

See this screenshot for a side by side comparison with the iOS version.

![img_0098](https://cloud.githubusercontent.com/assets/4453/13772673/ae8b4564-ea95-11e5-84c0-274708adee1a.JPG)

Is there some way I can debug this, or something I can reset to get it working?

**Comment by nondebug** [comment]
Hi Torbjørn, thanks for bringing this to our attention.  There's a known issue that can sometimes cause the URL list to be empty on first opening the activity.  Sometimes refreshing works, sometimes you need to turn the screen off and on again to trigger a new scan.  If that doesn't work, try force-quitting and reopening Chrome.

There's a fix in Chrome Dev that we believe addresses the issue you're seeing.  If you have the time, could you install it and see if the beacon shows up reliably?

Starting in the current Chrome Dev build we've added a diagnostics page (chrome://physical-web) that can help determine why a detected URL isn't being displayed.  Occasionally a beacon that was previously close enough to trigger the notification will be out of range by the time the activity is shown.  On the diagnostics page, a URL in this situation is tagged "LOST".  We also check that a URL can be resolved through the Physical Web service before we display it.  If the URL is still nearby but can't be resolved, it's tagged "UNRESOLVED".

**Comment by torbjornvatn** [comment]
I actually got it working in "regular" Chrome, I had to change the URL broadcasted by the Eddystone beacon from [our own site](https://www.proxbook.com) to [facebook](https://www.facebook.com) :confused: 

So I guess that proxbook.com is stopped by the Physical-Web service somehow, because when I looked at chrome://physical-web in Chrome Dev it said UNRESOLVED. Is there any way I can find out why the service marks it as UNRESOLVED.

**Comment by scottjenson** [comment]
Does your website have a robots.txt file that specifies 'no crawl'? If so, we respect that directive

**Comment by oahziur** [comment]
Hi Torbjørn,

I think this is because your website has meta fragment redirects in the `<head>` section. The crawler we use does not follow the meta fragment and treat it as an error (to avoid meta fragment target url permanently redirects to the original url).

The temporary fix for the site is removing `<meta name="fragment" content="!"> ` from the `<head>` section, but I will update this once I have more information on this.

Thanks,
Rui

**Comment by oahziur** [comment]
@torbjornvatn A recent update on Physical Web Service should fix your site problem. Thanks.

**Comment by torbjornvatn** [comment]
Cool :sunglasses:

**Comment by Chintanp038** [comment]
Hello sir,

I am testing on url send by eddystone beacons and it is detected by android phone by physical web in google chrome.
it's working fine in iphone but struggling with the android phone.

I have:
1> Nexus 5X android phone with 6.0.1 version
2> updated google chrome with on physical web (on bluetooth and location)

Problem is that my device does not recognize the any URL and there is no such a option for  "SEE NEARBY OBJECT " in Physical Web on page in my phone and also no getting any notification about the physical web

**Comment by scottjenson** [comment]
We should be rolled out to ALL android phones by end of the day (I know,
this has been a confusing process for all, sorry about that but Chrome
always rolls out big features slowly). Everything should be on by end of
today. Other things to check:

* Is your URL HTTPS? Android only shows HTTPS (IOS Shows HTTP and we're
changing that soon)
* Try installing Chrome DEV, it has a few bug fixes (coming soon!) that
shows beacons more reliably

**Comment by koustubhavachat** [comment]
Facing same issue , I am using HTTPS playstore link via google url shortner.  Yesterday got following questions  from client 
1. "When will user get notification if eddystone is broadcasting URL continously ?  "
2. "How can normal user will understand how to activate physical web using chrome ? "
3. "Why can't google keep physical web ON by default in chrome ?"
4. "How to implement security/authentication ? "

**Comment by mrquincle** [comment]
Is it still the case that HTTP cannot be RESOLVED?

**Comment by ferencbrachmann** [comment]
@mrquincle If the final destination URL is HTTP than it will not be resolved. If the forwarder is HTTP and the final destination is HTTPS than it will be resolved. As I'v suggested in Vienna, use a Beeem landing page for your beacons ;)

**Comment by scottjenson** [comment]
Agreed, the FINAL URL must be HTTPS for security reasons. Please use verify.physical-web.org to test any URL to make sure it works if you have any problems with a URL
