### ISSUE TITLE
Physical web Turn ON Alert without bluetooth ON

### ISSUE THREAD

**Issue by princecharmx** [google/physical-web#621]
Hi,

Currently user don't know how to enable physical web. Bluettoth, Location, Chrome browser setttings are required. If either on one is enabled, user should know physical web object presence. Currently, its complicated for user to take advantage of physical web devices.

**Comment by mmocny** [comment]
These requirements are necessary by Chrome as a policy.  We are working on ways to make it easier to turn on and educate users, but we cannot workaround some of the requirements.

If you have specific suggestions, please file requests at [crbug.com](http://crbug.com) and use the `Internals>PhysicalWeb` Component label, please!
