### ISSUE TITLE
URL broadcasts not visible in Chrome but on App

### ISSUE THREAD

**Issue by saifrais** [google/physical-web#622]
I am working with 6 beacons (Eddystone-URL: blesh, estimote, minew) which are visible in the native Physical Web app. They do not show up in Chrome. They are HTTPS pages. Is this the PWS filtering out the URLs or a broadcasting issue?

**Comment by saifrais** [comment]
Chrome does show 1 phyiscal web page which is being simulated by an Eddystone broadcasting app

**Comment by mmocny** [comment]
Hi @saifrais.

If you have Chrome m50 Installed (currently in Beta), you can try using the `chrome://physical-web` diagnostics page.  That page doesn't auto-refresh but will give you a snapshot of the beacons around and their current state.

**Comment by saifrais** [comment]
Thanks. The diagnostic page is very useful! #613 also raised a similar issue (which I read later!). The problem I am facing seems to happening specifically on the Blesh beacons (Estimote n the app is being found on the diagnostics page). I will be closing this issue.
