### ISSUE TITLE
PWS handling URL

### ISSUE THREAD

**Issue by russellmorton** [google/physical-web#623]
I am setting up a beacon with the URL - http://m.grandcentralmotors.mercedes-benz.co.za.

The URL when typed directly goes to the mobile site, however when putting this URL in the beacon it is returning the desktop site via the PWS. 

I don't know what is happening here, could someone please provide some insight and a possible resolution?

**Comment by mmocny** [comment]
Chrome only supports `https` URLs with a valid certificate.  Today the standalone Physical Web app will work, but we may be adjusting that soon.

Unfortunately, it looks like your https endpoint does not have a valid certificate, so even after I switch to https it doesn't work.  I suggest you contact your webmaster and look into the situation.

**Comment by jamieconyngham** [comment]
Hi @mmocny

Was wondering if you could help me. I can't get Physical Web Services  to recognise URLS from shorteners like bit.ly or goo.gl on Android. Diagnostics say unresolved but it works on ios. Our URLs are too long so wecneed to go via a shortener.

Cheers

**Comment by cco3** [comment]
And you are sure that the endpoint URL is an https URL?

**Comment by jamieconyngham** [comment]
It goes Goo.gl then to our platform as an http then to an https endpoint.
Ie it goes through our redirector platform. Works on PWS IOS but not
android.
