### ISSUE TITLE
Clearing URL Name And Description Shown In Notifications

### ISSUE THREAD

**Issue by Uhnnohn** [google/physical-web#624]
I set up a new new URL,   programed my beacon,  and realized that I wanted a different Title and description for the page, so I updated the web page.

But the original information seem to be permanently attached to the beacon.
Is there a way to clear that out?

**Comment by A024806** [comment]
I am a little bit of a new one of the day

Mathias <notifications@github.com> 於 2016年4月14日 星期四寫道：

**Comment by mmocny** [comment]
@Uhnnohn Mathias there are several layers of caching, but you should see the updated metadata in about 5 minutes.

Is it working now?

**Comment by Uhnnohn** [comment]
After being unplugged all night, still showed original URL Title & Description
Viewing in Android Physical Web app 0.1.856
After clearing data and cache from app and doing a force stop
It then showed the updated info

Thanks!

**Comment by mmocny** [comment]
Thats really odd, thats certainly not what was expected.

Did you try pull-to-refresh from within the PW Activity in chrome, and it still gave stale results?

We will investigate, thanks for the report!

@cco3 @nondebug

**Comment by nondebug** [comment]
In the prototype app we don't re-resolve URLs if they've already been resolved and the page metadata is cached.  In Chrome on Android, the metadata cache is cleared when the activity is refreshed so the behavior should be closer to what you expect.  Thanks again for bringing this to our attention.

**Comment by A024806** [comment]
google/physical-web您好：

誠摯邀請您加入我的人脈網。

- 鄭文仲

我認識鄭文仲: https://www.linkedin.com/e/v2?e=0-iq4rirkx-jn&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=thlrwbLm&invitationId=6154886765468540928








有人邀請您建立關係。LinkedIn 將使用您的電郵地址來為您提供更佳使用體驗，如透過「您可能認識」來為您建議聯絡人。按一下 https://www.linkedin.com/e/v2?e=0-iq4rirkx-jn&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEkPqIBCrD12QAAAVWqNBjr4J2HHt6yBZrMz9LTOyFxM1AG4ucbEYIyKMrzKsWJ_TsZ8XqQtLAtA3CYBrEPk4Rdsckmf2rzLHp7_u9GXTjMOlO2jfHnOTS4_N81PWpyPUweEprxr5ujIb1Yx7gDy7zTxwI0kiwgCgy5r-e7hVuHO1S9HZ5rNq8rUBGBmJIhzXkO&eid=0-iq4rirkx-jn，取消訂閱。


郵件已傳送到reply@reply.github.com。

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iq4rirkx-jn&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043.LinkedIn 和 LinkedIn 標誌為 LinkedIn 的註冊商標。
