### ISSUE TITLE
PWS shows UNRESOLVED on Android for shortened URL's

### ISSUE THREAD

**Issue by jamieconyngham** [google/physical-web#625]
Hi

Was wondering if you could help me. I can't get Physical Web Services to recognise URLS from shorteners like bit.ly or goo.gl on Android. Diagnostics say unresolved but it works on ios. Our URLs are too long so we need to go via a shortener.

Cheers

**Comment by cco3** [comment]
Is it an https URL that the shortener points to?

**Comment by jamieconyngham** [comment]
No its an http which then points to an https

**Comment by cco3** [comment]
We no longer support that on Android and soon it will not be supported on iOS.  You will need to point to an https URL.

**Comment by jamieconyngham** [comment]
Ok thanks.

**Comment by cco3** [comment]
No problem!

**Comment by mmocny** [comment]
Wait -- was it actually http shortener pointing to a https resolved URL?  That is actually supported fine.

**Comment by jamieconyngham** [comment]
It was shortner then http redirector url then https url. So it didnt like
the redirector http url.

**Comment by mmocny** [comment]
Would it be possible to get the URL value so we can test?

**Comment by jamieconyngham** [comment]
So use this example;

http://goo.gl/JLjLQ4

Which points to 

http://tagtap.tapit.com.au/Tap?tagid=TPT0000030

which redirects to 

https://au.linkedin.com/in/jamieconyngham

**Comment by dermike** [comment]
I have a similar problem with the URL https://bit.ly/kibquiz which redirects to https://tools.kib.ki.se/quiz/examen/
Shows as unresolved in Chrome, nowhere else.

**Comment by jamieconyngham** [comment]
How did you go with this example ?

So use this example;

http://goo.gl/JLjLQ4

Which points to

http://tagtap.tapit.com.au/Tap?tagid=TPT0000030

which redirects to

https://au.linkedin.com/in/jamieconyngham

On 14 April 2016 at 14:30, Michal Mocny <notifications@github.com> wrote:

> Would it be possible to get the URL value so we can test?
>
> On Thu, Apr 14, 2016 at 12:24 AM jamieconyngham <notifications@github.com>
> wrote:
>
> > It was shortner then http redirector url then https url. So it didnt like
> > the redirector http url.
> > On 14 Apr 2016 2:21 pm, "Michal Mocny" <notifications@github.com> wrote:
> >
> > > Wait -- was it actually http shortener pointing to a https resolved
> URL?
> > > That is actually supported fine.
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub
> > > <
> > https://github.com/google/physical-web/issues/625#issuecomment-209754798
> >
> > >
> >
> > —
> > You are receiving this because you commented.
> >
> >
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/google/physical-web/issues/625#issuecomment-209756088>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/google/physical-web/issues/625#issuecomment-209756909>
>



-- 
*Jamie Conyngham*
CEO & Co-Founder



mobile: +61 438 002 495

Lvl 1, Suite B, 17-19 Alberta Street
Sydney, NSW 2000
Australia
web: www.tapitww.com <http://www.tapit.com.au>
