### ISSUE TITLE
Unresolved HTTPS URL hosted using AWS Cloudfront

### ISSUE THREAD

**Issue by saifrais** [google/physical-web#627]
I have a url https://buzzinspots.com which is hosted using a Cloudfront distribution on AWS. For some unexplained reason, the Chrome dev page for physical-web shows it as UNRESOLVED. The app shows the webpage, although it is unable to load the favicon, description or title.

**Comment by scottjenson** [comment]
It appears that web page is not loading properly, even for a normal web browser. When I try to access that page from Chrome I get:

ERROR
The request could not be satisfied.
CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection. 
Generated by cloudfront (CloudFront)
Request ID: 0WIcQtXTsr4p9OSJtXNY5knwp7XXGoYMrDOgz8GjWqPhL0ZyajoPNg==

**Comment by saifrais** [comment]
This actually helps!!...because CloudFront cached a version of the webpage in my geography (during an earlier HTTP request) and was serving me the same during my HTTPS requests. From your location, the page load failed as there was no cached version of the webpage. 

While CloudFront can allow an SSL connection to the same page, it seems that the S3 bucket (storing the web page) can be accessed ONLY through an HTTP protocol. PWS seems to be picking up information for the webpage now.

I am attaching the troubleshooting link for anybody facing the same problem:
http://stackoverflow.com/questions/22282137/cloudfront-error-when-serving-over-https-using-sni
