### ISSUE TITLE
Blesh URIbeacons do not show up in Chrome

### ISSUE THREAD

**Issue by saifrais** [google/physical-web#628]
I have been working with a bunch of vendors and their compatability with Eddystone-URL. I have a box of older Blesh URIbeacons which couls be configured to broadcast URLs (in the same manner as the Eddystone-URL). But, Chrome does not seem to be detecting them. Are the protocols different?

**Comment by scottjenson** [comment]
Yes, they are different. When we moved from the URIBeacon standard to Eddystone, it required changing to a new service ID. I can't be sure, but I'd contact Blesh as they likely have a firmware update that will let reconfigure the URIBeacons.

Scott

**Comment by saifrais** [comment]
Got it..Thanks!

**Comment by saifrais** [comment]
I recieved word from the beacon manufacturer Blesh that they are not supporting an OTA firmware update from uribeacon to eddystone-url....quite disappointing when some peers are allowing toggling between protocols.
