### ISSUE TITLE
Chrome + ios

### ISSUE THREAD

**Issue by ishmeetahuja** [google/physical-web#630]
Hello, 

I have reinstalled Chrome on my iphone 6 (9.3), added chrome as a widget but I do not see the "Scanning for Physical Web Objects" message. My Chrome on ioS cannot detect any beacons. Is the chrome with physical web objects still experimental on ios ?

**Comment by scottjenson** [comment]
It's official and should work.
 
Do you have Chrome 49 or higher?
Do you have Bluetooth turned on? 
Do you have any beacons nearby?

**Comment by ishmeetahuja** [comment]
Yes Scott

I have Chrome 49.02623.109
Bluetooth is turned on and yes 
there is a beacon . 

But my issue is it doesn't even say **Scanning for physical web objects**  

Please Look at the screenshot attached ..

[http://s31.postimg.org/akmfjbapn/Screen_Shot_2016_04_19_at_1_21_12_PM.png](url)
thanks for your help

**Comment by scottjenson** [comment]
Sorry, then I don't know what to do at this point. I hate to keep asking basic questions, but is the beacon an Eddystone beacon with a URL programmed in it?
