### ISSUE TITLE
Observation of unstable scanning of physical web in Android, Chrome 49

### ISSUE THREAD

**Issue by kanodia** [google/physical-web#631]
> Does physical web wakes only when google.com has the permission allowed or it also needs to be able to fetch the location?

Yes, you need to have a location provider enabled.

> Does physical web need permission specifically for google.com or any other website will also do?

You just need to have granted the location permission to chrome.  The most common way that users do this is by visiting a site (like google.com) that requests it.  You could also enable the Physical Web in privacy preferences -- we will request location permission if you go through that flow.

> Will the physical web wake up if the location permission is disabled on google.com?

We can't scan without the location permission.

> If there is absence of internet, will physical web even wake up, though it may not be able to fetch metadata and instead just show loading?

We may scan, but we will not show results or send you a notification.

> Does slow internet affects the scannability of chrome to wake physical web?

You should still see results, even with a slow connection.

> Are there any other permissions that the user needs to grant?

No.

> What is the best procedure and condition for a user to get physical web notification when he comes in the range of an URL broadcasting beacon?

Chrome 50 will have a diagnostics page at chrome://physical-web to diagnose these issues.  For now, the best way is to go through the settings -> privacy settings -> physical web -> enable flow to ensure we request location permission.

> How can we reach to a stage where the user just turns on bluetooth and gets physical web?

Right now, we need the location permission, a location provider, and a data connection.  If you have suggestions on how to expedite any of these, we are open to ideas.

**Comment by kanodia** [comment]
Thank You for the answer here.

Few observations here:

1| I saw a lot of smartphones with chrome 49 but there is no option for physical web under privacy setting.

2| In smartphones where there is physical web option in privacy, when I switch it on,it does not asks for location permission. I had to manually open google.com and get location permission.

**Comment by kanodia** [comment]
I did a fresh installation of chrome 49.
Then I went to privacy setting and I could not see physical web there.
![img-20160420-wa0000](https://cloud.githubusercontent.com/assets/8614465/14667530/63bbcb88-06fd-11e6-852f-2f3e4219fa15.jpg)

**Comment by kanodia** [comment]
Then I went to chrome flags and changed the state of physical web flag from default to enable, and immediately upon relaunching chrome, I could see physical web.

If this works out, then why haven't we made the physical web flag to enable instead of default.

I think can help us detecting physical web easily.

**Comment by kanodia** [comment]
One reason I could think of for why in chrome 49 we cannot see physical web in every phone is because it is still not rolled out to everyone.

Are we still rolling it out or Google chrome has completed physical web roll out to everyone?

**Comment by scottjenson** [comment]
This is a bug, we're fixing it in Chome 50

**Comment by kanodia** [comment]
Thank You Scott. It is such a big relief to know this :)

**Comment by kanodia** [comment]
Hey Scott,

W.r.t, your previous comment about chrome 50. Does that mean the physical web flag will be set to enabled by default when a user update chrome or the physical web option will be present in privacy settings
