### ISSUE TITLE
Security aspect w.r.t. BLE?

### ISSUE THREAD

**Issue by kanodia** [google/physical-web#632]
Hello

I have heard from a lot of people. They are worried about the security aspect of a user turning on bluetooth. 

The feedback is, the smartphone becomes susceptible to malwares and viruses when bluetooth is switched on.

Is that the case, can an android or iOS smartphone receive viruses through bluetooth or it is just a hoax?

Also, as beacons(BLE) work in 2.4 Ghz  frequency spectrum which is an allowed spectrum everywhere. Thus is there any legal issue that needs to be taken care of to be able to deploy beacons?

**Comment by scottjenson** [comment]
We only use BLE to scan for advertising packets which can't transport viruses or malware. There is also no legal issue with deploying beacons.

**Comment by kanodia** [comment]
Thank You Scott
