### ISSUE TITLE
Can the app send push notifications to users?

### ISSUE THREAD

**Issue by Jay-Web-Feet** [google/physical-web#633]
We are looking at using the beacons for a nightlife experiment and want to test bits and pieces. 

Question: If a user has the app, and is within the range of beacons, without manually accessing the app can you send notifications to the user?

**Comment by saifrais** [comment]
No. This might help you understand the concept behind the initiative.
https://www.youtube.com/watch?v=1yaLPRgtlR0

**Comment by mbrevda** [comment]
While I understand the privacy goals in making notifications unobtrusive and requiring user feedback, I'm wondering if there aren't specific use cases that may benefit from some automated action taking place when the user is in proximity. Here are some examples:

1. Auto open the garage door when the user is in proximity
2. Pop up a notification (including on Wear) allowing the user to open the front door in a single tap
3. Turn on lights when a user enters proximity

(as an aside, if service workers could have listeners for a given url, it would allow for these apps to be totally web based)

I'm not suggesting **forcing** these actions on a user (a one time opt in is appropriate), but I'm wondering if there isn't a middle ground between bombarding a user with ads every time they walk by (presumably the original motivation for this limitation) to forcing a manual interaction even after a beacon was detected?

**Comment by mbrevda** [comment]
I see that my points was mostly addressed in #307.

While I understand that TPW doesn't want to be handling things like actions, I think it's important to allow _something else to handle the beacon_ (after the user has opted in, obviously). For example, allow a service worker to register as the handler for a given url. The flow would look something like this:

1. User enters beacon proximity, turns on their phone and seens current PY notification
2. User selects notification and goes to website
3. Website service worker kicks in (perhaps with a web manifest) and requests user permission to always allow this site to handle beacons with a given url/domain/scope/etc
4. If the user agrees, website will be called next time beacon is detected
5. If the user doesn't agree, the current behavior (of chrome showing a silent notification) will continue unabated

Next time a user enters the beacons proximity, the website - not chrome - will handle the notification. In this case, all the regular website rules would apply. In this scenario, the website could, optionally, display actionable and/or audible notifications which would allow for behaviour like those in the video on #307, including pushing notifications to other types of devices (like Wear or Auto). The site can also use run actions automatically - like any site today -  which could be used to control things like IoT devices. 

From a security point of view, this "flow" does not enable anything that can't be done today, as the user MUST opt in to allow the site to be the handler for a given url/domain/scope/etc.

**Comment by scottjenson** [comment]
I *think* we have a roadmap that covers your issue. As you say, i'd like to approach my house, have the phone detect the garage beacon and just 'do the right thing'. Building on the web (and the big push behind Progressive Web Apps) it's clear that having the beacon create a ServiceWorker event is a very simple and elegant way to handle this. The problem of course, is that scanning while the phone is asleep in your pocket takes considerable battery at the time. iBeacon apps do this and can, depending on the phone, can chew up to 10% of your battery.

We'd like for there to be someway for the system to be more battery efficient at scanning for beacons so we could turn this on and enable this scenario. However, we're hampered not by the web but by the OS being able to scan efficiently. We're watching this space carefully and are looking for solutions, but until then, this is on the back burner. If you have any alternative suggestions as to how we could scan for less power, please let me know.

**Comment by mbrevda** [comment]
Geofencing comes to mind? Once a servicer worker is enabled to take over handling the beacon, it can need to specify the location of the beacon. The system will only wake to look for the beacon when the user in the given area. (In this scenario, we pretty much using the beacon as a fine grained gps supplement). 

Alternatively (and beyond the scope of this project) allow service workers to register for geofencing and wake them when in location (irrespective of the whole beacon thing)

Finally, perhaps a slower scan mode might be ideal for "known" beacons. Scan, say, once per minute when the screen is off for known beacons, and then always when the screen is turned on. In this case, the OS can (optional) handle geofencing and only search when ti _think_ the beacon is in the area. How does WiFi work in this regard?

**Comment by viviancromwell** [comment]
http://www.aislelabs.com/reports/ibeacon-battery-drain-iphones/.

For iOS, it does this range set which restricts you to a specific range (
it does have other drawbacks which I am going to skip now) so it is not
doing scanning in the background all the time.  Also, the app has a few
seconds - while in the range - to wake up and do certain things such as a
notification, then the process is killed by iOS.  We ended up doing tons of
optimizations within that few seconds.

When the app isn't running in the foreground battery consumption has been
very minimal (1 - 2% for a charging cycle) for us. When it's running in the
foreground and the device is within our beacon's range (note that if it's
out of range this doesn't apply) we're actively ranging, so it will consume
slightly more.

- Vivian





al:  www.angel.co/viviancromwell
tw. www.twitter.com/viviancromwell
li.   www.linkedin.com/in/viviancromwell

**Comment by csuwildcat** [comment]
I would suggest folks on this thread follow the issue we are discussing here: https://github.com/google/physical-web/issues/634, it could enable the push scenarios you have mentioned.

**Comment by mbrevda** [comment]
#634 is definitely trying to cover some of the use cases described here. It might be good to separate the ability to handle a beacon locally (e.g. via service workers, etc) from authentication part, so that the ability can be described while the merits of the blockchain are still being discussed.

**Comment by scottjenson** [comment]
Agreed, I think the thread here is "detection while asleep". I think we have the architecture in place: use service worker with a Physical Web event. The only thing we're missing is to have the background scanning occur to fire off the event. There is clearly not enough data to say anything clear on battery drain. It's wise to be worried but it could be on modern phones, scanning a bit slower (or using Android Auto as @mbrevda suggests) could be the answer.

I'm worried that geo-fencing is a lot of work for a very narrow win. Yes, it would work for my house, but not for a city bus stop app, or for anything that may be mobile. As long as it doesn't kill the battery, I'd like to have the most flexible solution we can.

Sounds to me we could take an early step and build something into the Android Physical Web prototype  app. It could scan in the background and either a) beep every time it finds something and have some way of marking a beacon as a 'favorite' and only beep when close to that.

It would be crude to be sure but we could start to play with the idea and at least learn about the rough battery mechanics to inform our next decision.

**Comment by mbrevda** [comment]
Thanks @scottjenson and good point regarding geofencing being a narrow win. I might add that if the Service Worker was doing the scanning, and it passed a (rather long) list of geo locations to the OS (which presumably can handle geofencing efficiently, like [FusedLocationProviderApi](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderApi)) geofencing might work even in the bus stop scenario.

 It might be interesting to separate scanning from handling. Scanning frequency/triggers seems to be a bit of a more difficult question. In the meantime, service workers can be updated to be able to support beacons - irrespective of how they were notified of the beacon. Even if the former is not immediately solved, once a beacon _was_ detected - even via the current battery conscious approach - it can be handled locally via a service worker.

**Comment by scottjenson** [comment]
> It might be interesting to separate scanning from handling. Scanning frequency/detection seems to be a bit of a more difficult question.

Exactly. There is a lot to learn here, which I why I'm warming up to some experiments in the prototype app as a way to learn a bit more. However, 'an app' can only do so much. To *really* get power efficiency, we'll likely need some variation on your suggestion that the Service worker 'registers' a URL/domain with the OS. That way, the scanning can be pushed down into the BLE chipset itself and only wake up the main CPU when necessary.

However, there is also quite a bit to learn about over triggering and noise. If I'm in the backyard, just out of range of my garage door beacon I don't want my service working firing and opening the door randomly. More subtly, I don't even want it waking up and doing nothing every minute either and just draining the battery. 

So given this conversation I'm seeing several things that likely need to happen:

1. Use the prototype app to do primitive background scanning to learn about battery drain
2. Hook up Service Worker to these events to learn about filtering/'debouncing' the events
3. Integrate with the OS to be super efficient w/ scanning

#1 is very easy but 2 and 3 are obviously much harder: they involve changes to low level App/OS apis.

**Comment by mbrevda** [comment]
👍 

One partial way to mitigate (but not alleviate) # 3 might be to add scanning ability to Wear. I.e. scan when a user raises his hand (or some given gesture). This will allow a more 'controlled' scenario for scanning while still being (almost) hands free.

**Comment by LadyBird1960** [comment]
Immersrnce ly.
I agree. Except for exuse In Danmark we call i t Undskyld! 🍀 👌
Undskyldninger etc.  Including.
At least I find you 'r discus here quite equiellient expressed.
Hvad-ved-jeg.
Depends how al the from My point of Wien: socalled pronounced expressed
format y end up formatting it i in?
I specially have Him the now Long dead comik marker Who made his choice to
liv his officielle life i n USA.
Some her perhaps know what I Mean.
Hej call Him self.... ? 😭 right now it's Simply sleept out of my mind? 😭.
His corrctly socalled Danish name was somelike this; Rosenbaun?. ⏰
On Any matter the point i d want to higligt here is 🍦
Ruels: about,.,. :;/)(#@?!'".#+_- etc.
Attest about writing with Caritas lettere's? I N first pf.examce
ReadAndWrite for ther better understanding both way communikation
Rules for Usage of the keyboard;kCaps.lock..? Otherkey.s key. Caps.
It make No sense When thi speling control' er is in his need for freely to
express
That he Simply need to event his own New wirdbook in the misty tryance to
be under stood of other than her self M/K.
Q Venus Tegnet ér ikke lige på mit tastatur her på Min Smarte Sony med
finger touch ⏰.
Sorry.  My Lifes time counter is out of time today.
I change over to egg timer min. Counter.
Imidlertid for Nu.😊. #-#\'
But I ' m
Not in Any hurry to dismis my subschribtion in this newsletter forum.
Im i n a way glad 😁 y let my speak out my words here.
Y are Welcome to give me Any feedback wanted i n your intrest.
In that case :
I recieve coment via my Home-page ;
Honeyfortheworld.org.
Gladly 😁 expressed with a touch of our equiellient sense for humor :-* >:)
:-P B-)
Den 1. maj 2016 7.09 PM skrev "Moshe Brevda" <notifications@github.com>:

**Comment by saifrais** [comment]
Wearables may have some time to reach critical adoption levels (at least in developing nations)...may be simper triggers like 1) screen unlocks and 2) gesture sensing events like pulling your phone out of your pocket could be more scalable. If the objective of PWS is to be unobtrusive, then scanning while your phone is 'activated' could be a quick fix solution. 
In the example of the garage door, we may trigger an event every time we step out to mow the lawn. Considering the door WILL open if we reach for the phone to receive an incoming call, no golden rules here obviously!

**Comment by scottjenson** [comment]
That's a clever approach. I do hope we aren't too far from the BLE chip having the memory capacity to do continual scanning at a reasonable power level. That would unlock the most potential. However, it *is* possible to consider scanning only when active. Compared to the power of the screen, that draw is trivial and it would unlock several use cases.

**Comment by saifrais** [comment]
Actually, that makes perfect sense! The Link Layer already has a provision for a whitelist (of addresses) and a filter policy to facilitate the 'handling' part. We can use the filter policy in the background...and we can toggle the filter policy as the phone changes state (between active n dormant)...

**Comment by scottjenson** [comment]
Well it was *your* idea ;-) The only issue here is simply logistics. This is something that would have to occur at the OS level. We can start discussions here at our end but a deep change like this is going to take quite a bit of discussion and review. It's important to get started, just saying it won't show up next week :)

**Comment by saifrais** [comment]
Another possible issue, as the background filtering gets pushed down the stack, is handling the security features like random address generation. The Controller will need to take charge of resolving these addresses. I am assuming that the URL registration in the Link layer would be done by adding the approved beacon's (URL) MAC address to the white-list? We would not want the Host being called every time we need a device's resolving identity key (IRK) as it will defeat the purpose of the filtering policy. In such a case, _device filtering becomes possible ONLY when address resolution is performed in the Controller because the peer’s device identity address can be resolved prior to checking whether it is in the white list_(Bluetooth Specification v4.2 5.4.5, pg.95 ).

**Comment by scottjenson** [comment]
Not sure we need to go down to that level. If we assume we're only scanning for a progressive web app that's already been installed, we can just look for its URL. There is no need to filter through our PWS (it's been pre verified) This means you can search for the URL directly and pass the event the the cached JS from the Service Worker. The host doesn't even need to be involved.
