### ISSUE TITLE
Error building iOS app 

### ISSUE THREAD

**Issue by jrthom18** [google/physical-web#635]
There is probably a basic solution to this problem but cloning the repository and building the project for the iOS app in Xcode results in the error `'SDWebImage/UIImageView+WebCache.h' file not found` in `PWBeaconCell.m` on the import line `#import <SDWebImage/UIImageView+WebCache.h>` -- wondering if anyone else has seen this.

**Comment by jrthom18** [comment]
Found a solution elsewhere. This can be fixed by running `git submodule update --init --recursive` in the physical-web directory immediately after you clone.

**Comment by princeskittles** [comment]
hi please explain how this is done.. do I have to clone it or can I just download it first?
Also how do I run the command posted
thanks for your help

**Comment by princeskittles** [comment]
Hi, did you ever get this working or ios? If so can you share?

Thanks
