### ISSUE TITLE
cannot find Physical web option under Privacy settings in chrome 50 Android

### ISSUE THREAD

**Issue by kanodia** [google/physical-web#636]
Hello

I got an update for chrome 50. My location and bluetooth was turned on 
I waited for long for my phone to scan for physical web but nothing happend.

I went ahead and checked for physical web under privacy settings and found nothing.

![img-20160426-wa0001](https://cloud.githubusercontent.com/assets/8614465/14814008/ff9b55c8-0bc1-11e6-91ce-05b330a72ba4.jpg)

After that, I enabled physical web flad manually, and immediately after the relaunch I could see physical web notification. Also, after that, I could find physical web under privacy settings.

My observation here is, if a user does not have physical web under privacy, then he is not able to see physical web notification even if his bluetooth and location is on.

A lot of users even in the updated version of chrome cannot see physical web under privacy. Then the only way left is to manually enable the physical web flag.

Am I missing anything here. 

How should we counter this problem?

**Comment by mmocny** [comment]
Hi, could you help me understand better?

1. Did you already have the feature working in m49, and it stopped working in m50?
2. Have you been using this device & Chrome regularly, or is this the first time in a while?

If you were already using m49 and Physical Web was enabled, nothing should have changed after the update to m50.  If this is a new device, or the first time you have used it in a while, it may take a few hours and a Chrome restart for the Physical Web feature to become available automatically.  The chrome:flag is a manual way to force this to happen.

Thanks!

**Comment by kanodia** [comment]
Thank You mmocny.

I already had physical web running in m49. I cleared y cache and hence could not find physical web. It later was available. I as unaware of the chrome new feature release behavior.

I could resolve the issue.
Thanks again :)
