### ISSUE TITLE
Formatting Web Page For Similar Chrome Notifications

### ISSUE THREAD

**Issue by Uhnnohn** [google/physical-web#640]
For iOS notifications - Looks like the notification shows
        The Page Title & Link Under That

For Android notifications - Looks like the notification shows
        The Page Title & Link Under That
        The first 100 characters of the page under that

Any tips/suggestions for formatting the contents of my URL page so they both see the same thing?

**Comment by scottjenson** [comment]
The iOS app came out first and we appreciate that it's not quite kept pace with the Android app (doesn't restrict to HTTPS, doesn't show the description OR the favicon, etc) We're working on a revamp of the iOS app that will have it catch up to the Android app in these ways. It's still a few months out but I'd hate for you to do something special for your web page only to have to change it again. 

If you can hold on a few more months, you should be fine.

**Comment by Uhnnohn** [comment]
It's all new and fun.
For this we can be flexible.
Thanks for the info
