### ISSUE TITLE
Cannot find physical web devices

### ISSUE THREAD

**Issue by AlexanderLea** [google/physical-web#641]
Hi,

Using OnePlus Two, with Bluetooth, Data and Location all turned on.

Using the Physical Web browser, it displays "No nearby Physical Web pages found".

Viewing chrome://physical-web, I see the attached page. It appears as though Bluetooth isn't enabled (which it is because I can see the icon in the notification bar, and can scan and connect to other BT devices).

Any suggestions about how to debug the issue?

Cheers,
Alex

![screenshot_2016-04-30-17-28-11](https://cloud.githubusercontent.com/assets/1569481/14937246/9f0a0066-0ef9-11e6-96e0-c975a48f894d.png)

**Comment by scottjenson** [comment]
The OnePlus has had a spotty record wrt BLE. We had a OPO in the office and it could hardly find anything. That "UNKNOWN" strongly implies there is a problem with your Bluetooth stack. You could try loading the Physical Web prototype app from the Play store and see if that works. It uses a different API and might give us another way to track down the proglem.

**Comment by dermike** [comment]
Getting the same thing on a Galaxy S7... I'm advertising https://www.google.com, but the chrome://physical-web says t's http://... : unresolved.

**Comment by dermike** [comment]
@AlexanderLea Try advertising https://www.google.com instead. Chrome PW only supports https links.

**Comment by scottjenson** [comment]
Good catch @dermike I should have seen that

**Comment by AlexanderLea** [comment]
Changing to advertise https (good spot - thanks!) didn't help it appear in Chrome, but it downloading the app I can discover the beacon. I blame dodgy OP2 BLE! Thanks for your help guys :)
