### ISSUE TITLE
Error while building android app  : package org.physical_web.physicalweb.PwoMetadata does not exist

### ISSUE THREAD

**Issue by itsyash** [google/physical-web#642]
While trying to build the app in android studio (2.0), I am facing this error : 

`Error:(19, 48) error: package org.physical_web.physicalweb.PwoMetadata does not exist`. The error is in `BeaconDisplayListTest` file. How to resolve it? I can't see this package in the project explorer.

**Comment by scottjenson** [comment]
We auto build on every change. Here is the link to our [last build](https://travis-ci.org/google/physical-web/builds/116788852) which worked just fine.

**Comment by itsyash** [comment]
@scottjenson : Thanks for the response. I am build it now.
