### ISSUE TITLE
How add PW on apk???

### ISSUE THREAD

**Issue by aloparz22** [google/physical-web#643]
Hi guys, i need add PW on apk, i have little experience about android, and i need do it to my university, just need create a apk that have PW inside of this. Thanks Guys  :)

**Comment by scottjenson** [comment]
I'm sorry but you're asking a very general question that involves giving you a tutorial and support on how to program an Android app. I appreciate this isn't easy. However, we've had lots of folks fork an build the source so far. It's unfortunately not practical for us to support/train/debug users who are new to android programming.
