### ISSUE TITLE
Nexus 6p Chrome Status Bar Notification (Icon) Not Showing

### ISSUE THREAD

**Issue by Uhnnohn** [google/physical-web#646]
This is probably not direct a physical web issue

Nexus 6p Chrome Notification (icon) does not show in status bar
        But Physical Web notification is there if you know to pull down

Nexus 5 Chrome Notification (icon) DOES show in status bar when near a beacon

Same notification settings for both device and app

Anyone else use a 6p and see the Chrome Icon in the status bar when near a beacon?
(without pulling down)

**Comment by nondebug** [comment]
It sounds like this is working as intended.  Physical Web in Chrome for Android will show at most one PRIORITY_HIGH notification.  This occurs the first time you are near a beacon, and only if you haven't already enabled the Physical Web via the settings toggle.  All subsequent notifications are PRIORITY_MIN and will not appear in the Android status bar.

Physical Web notifications are typically of low importance to the user, and Android guidelines recommend using low or min priority notifications for such events.

http://developer.android.com/design/patterns/notifications.html#guidelines

**Comment by Uhnnohn** [comment]
So you will only see the Chrome notification (icon) in the status bar ONCE:
1. The first time you ever see any physical web beacon?
2. The first time you see a new beacon UUID?
3. The first time you see a new beacon URL?
4. Other?

And after that you will need to check (pull down) to see if there are any

**Comment by nondebug** [comment]
1.

**Comment by Uhnnohn** [comment]
Thanks!
