### ISSUE TITLE
Will physical web show up if google chrome is not running in background?

### ISSUE THREAD

**Issue by kanodia** [google/physical-web#648]
Hello

My google chrome has location permissions enabled.

I restarted my Android phone, which would mean that no app is running in background.

I switched on an eddystone URL beacon broadcasting an https URL and turned on phone's bluetooth.

My expected behavior: physical web notification should appear.

Observed behavior: I could not see physical web notification.

Then I opened google chrome and then checked the notification panel, I could find physical web pages nearby.

Hence my question is, will a user needs to run google chrome or open google chrome at least once to be able to detect physical web page?

Follow up question: will the behavior be same for a first time user whose physical web is in off state in privacy settings. Will the user needs to open google chrome to be able to get a physical web notification?

**Comment by cco3** [comment]
> will a user needs to run google chrome or open google chrome at least once to be able to detect physical web page?

Yes.

> Will the user needs to open google chrome to be able to get a physical web notification?

Yes.

In order to begin scanning, the user needs to open the application.  Otherwise we have no opportunity to begin scanning.  As to the title question:

> Will physical web show up if google chrome is not running in background?

No, it does not need to be running in the background.  It just has to have run once.

**Comment by kanodia** [comment]
Q| Will physical web show up if google chrome is not running in background?
No, it does not need to be running in the background. It just has to have run once.

>>> Will this mean, that I open chrome once and say close it. Now if I come near a beacon, i will see physical web pages nearby?

**Comment by kanodia** [comment]
@cco3 : My observed behavior is, if I close google chrome then I am not able to detect physical web.

**Comment by scottjenson** [comment]
There is a bug in Google Play services that when Android kills chrome, it kills Physical Web scanning. For bigger device with more memory, this can be delayed quite a while. For smaller memory devices, this can happen quickly.

Fortunately, this fix is rolling out very soon, within a week or so...

**Comment by kanodia** [comment]
Thank You scott.

Will be see this fix in the stable version of chrome 50 or in the next stable release of chrome, i.e. chrome 51?

**Comment by scottjenson** [comment]
It will be in Google Play Services so should roll out independent of Chrome.

**Comment by kanodia** [comment]
Any estimate date that google has planned out for the release of google play services?
