### ISSUE TITLE
Read the advertisedId from beacon with Chrome Physical Web

### ISSUE THREAD

**Issue by BleMot** [google/physical-web#649]
Hi, its possible read the advertisedId with the physical web chrome support. 

I manage beacon with Proximity Api and i need read the Eddystone-url and the eddystone-uid from beacon.  It is possible?

Thanks.

**Comment by cco3** [comment]
Sorry, could you please provide some more context?  Are you trying to get the URL from the beacon in a web page?  From an Android app?  Through the proximity API?

**Comment by BleMot** [comment]
Hi, I am developing an web app to manage beacons eddystone with google proximity api.
I have one beacon that sends an eddystone-url and eddystone-uid frame.
I need chrome read the eddystone-uid frame, the eddystone-url frame its ok with physical web feature.
It's possible that chrome read the eddystone-uid frame with the physical web feature?

Thanks.

**Comment by cco3** [comment]
No, the physical web feature currently only notifies the user.  We don't have an API in chrome to access that data yet.
