### ISSUE TITLE
Launching android app shows github 404 page

### ISSUE THREAD

**Issue by maplemuse** [google/physical-web#659]
Launching the Physical Web android app for the first time shows a Github 404 page that I'm supposed to accept and continue. Looks like some assets may have moved.

![screenshot_20160519-111418](https://cloud.githubusercontent.com/assets/1189823/15398869/5f09dad6-1db3-11e6-9479-17b133ead7ea.png)

**Comment by scottjenson** [comment]
We're on it. We refreshed the website and changed the URL for the about screen. Fix coming soon

**Comment by scottjenson** [comment]
This should be fixed now. Closing
