### ISSUE TITLE
Physical Web and Instant App

### ISSUE THREAD

**Issue by leopck** [google/physical-web#662]
Hi I saw from the Google I/O 2016 regarding the Google Instant App. 
Physical Web's interaction has always been using a website like Web Bluetooth to interact with the Bluetooth devices all of which leverages on the Web technology(HTML, JS) but now with Instant App which, correct me if I'm mistaken, leverages on the native SDK. According to the parking demo for Instant App, the interaction is very similar to the demo of Physical Web for the parking demo except for the NFC part.

How would this impact the Physical Web?

Would we be able to see a demo that combines Physical Web and Instant App since Instant App is also from a URL?

Would this make the website interaction obsolete?

**Comment by kanodia** [comment]
Great Point. Even I have the same question.
With nearby notifications and android instant apps coming, UX will improve a lot as nearby notifications are customizable and native apps have wide more possibilities to provide usability.

**Comment by scottjenson** [comment]
We don't work on instant apps sorry, but not much for us to offer. However, the web isn't going anywhere and the Physical Web will continue to recommend standard web pages.
