### ISSUE TITLE
Beacon not detected

### ISSUE THREAD

**Issue by tevey** [google/physical-web#663]
I built a beacon using the Redbearlab Blendmicro and this library https://github.com/sandeepmistry/arduino-BLEPeripheral. The beacon is detected in the app Toy Beacon (screenshot https://goo.gl/photos/Mp4TfF6aCGaNmQJs6) but not i the google Physical web app and not detected by chrome.

Here is the arduino code https://github.com/sandeepmistry/arduino-BLEPeripheral/blob/master/examples/Eddystone/EddystoneURL/EddystoneURL.ino

The device i'm using to test is an Nexus 5X fully updated and with latest chrome.

**Comment by scottjenson** [comment]
Two possible issues:

What URL are you using? If it's not HTTPS, it won't show up (Physical Web only uses HTTPS to protect users)

**Comment by tevey** [comment]
as you can see in the screenshot i use https://www.google.se

**Comment by nondebug** [comment]
The URL is fine, I was able to configure a beacon with that URL and find it in Chrome 50.

Have you been able to find any beacons in Chrome?  If not, check to make sure you have Location enabled, and that Chrome has been granted the Location permission.  There's a diagnostics page at chrome://physical-web that can help you verify these settings.

**Comment by adriancretu** [comment]
Is there a PWS black-list for specific web-sites, or what could be the reason for a beacon's URL to be detected and displayed by the Physical Web app, but not by the latest Chrome? If there is a anti-spam mechanism, how does it handle shorteners (since they are not responsible for a redirected web site's content)

On another note, goo.gl has recently started to deny shortening requests for youtu.be links. It might think they don't need to be shortened? It would be cool if goo.gl would re-shorten the actual long YouTube URL instead of erroring-out.

**Comment by rosesrob317** [comment]
GYPSY

**Comment by scottjenson** [comment]
We are working on a URL tester (should be release real soon now) to give you more feedback. The problems we see with things not showing up are:
* Not HTTPS
* Too many redirects
* Restrictive robots.tx
* Spam/phishing site (unlikely)

We usually find the first 3 catch the majority of the problems. We'll announce as soon as we have the testing site up. Feel free to reopen if needed

**Comment by rosesrob317** [comment]
I've shared an item with you:

Group intitled folder
http://drive.google.com/drive/folders/0ByeMI_oJLtnqY084VHpmZ2wtOFU?usp=sharing&invite=CJXMst0M&ts=5898600e

It's not an attachment -- it's stored online. To open this item, just click  
the link above.

**Comment by rosesrob317** [comment]
Hi!

ChiefSmakaHoe78@gmail.com has sent you some files with Degoo.

View the files now by following the link below
https://cloud.degoo.com/drive-h9hUC9HSaxqC7


Best regards
The Degoo Team


Copyright 2017 Degoo Backup AB
