### ISSUE TITLE
Question: Physical Web Roadmap/Next steps?

### ISSUE THREAD

**Issue by nicooooolas** [google/physical-web#665]
Hi !

I like a lot PW, thanks to promote this. Can you share few potential next features? 
- maybe PW inside Google Maps?
- direct notification on iOS (like Android)?

Good luck for the next releases!

**Comment by scottjenson** [comment]
Sorry, but we can't comment on future roadmaps. We're doing a lot of work in the prototype app (like supporting mDNS). Most of our energy is focused at that level: finding URLS.
