### ISSUE TITLE
chrome android physical web not working

### ISSUE THREAD

**Issue by viligaga** [google/physical-web#667]
Hello,

anybody else with this problem? I tried everything to make it work. Set up a beacon with a different HTTPS websites. I enabled bluetooth, location and physical web (experimenting with flags, diagnostics, permissions, settings) on my smartphone. I installed the latest version of Chrome, beta, dev. I tested for at least 100 times. I was able to get a notification only a few times, only sometimes when transmitting a new website or when manualy searching in Chrome. With Opera Labs I allways get a notification, even on the fly but I really need this in Chrome, because it is a standard browser. I really need this thing to work, because my web service depends on that. Thanks.

There is also article about this issue posted two months ago:
https://mobiforge.com/design-development/eddystone-beacon-technology-and-the-physical-web

Two weeks ago:
https://github.com/google/physical-web/issues/648

...

Greetings,
V.G.G.

**Comment by cco3** [comment]
I'm sorry you are not being notified reliably.  I'm curious as to what the specific behavior is on the most recent Dev.  Do you get any notification?  If so, when isn't it notifying you when you expect it to be?

In the future, please file chromium bugs at crbug.com.

**Comment by beaufortfrancois** [comment]
For info, which smartphone do you have and which version of Android is running?

**Comment by viligaga** [comment]
thanks for reporting this bug.

I tried the latest Chrome dev but it seems no different than Chrome. I expect notification for every PW available, when somebody comes close to the beacon. I'm experimenting with different HTTPS websites and with Chrome it is very unreliable. Mostly but not so often it is detected, when I restart my smartphone and after I open/close Chrome. Today I managed to detect it once, with no restart after a while, but this is very rare. With Opera Labs it gets through easely, it doesn't have to be HTTPS and it has a special tab just for PW.


Smartphone: Xiaomi Redmi 3 Pro
Android: 5.1.1 LMY47V

Play store: 6.5.08.D-all [0] 2792142


chrome://physical-web

Physical-Web is ON
Android SDK version: Compatible
Data connection: Connected
Location services: Enabled
Physical Web privacy settings: On
Bluetooth: Unknown
Nearby web pages
https://...

**Comment by kanodia** [comment]
Try this combination.
Make sure your google chrome is closed( i.e., not even running in background)

First switch on bluetooth, then your location and then open google chrome.

If there is a beacon nearby transmitting a HTTPS URL, you will definitely see physical web notification.

Let us know your observations.

**Comment by viligaga** [comment]
kanodia, I can get PW if I follow these steps. There is no notification icon, but if I check, it is there. This could be OS related or maybe not. As you would have to know, if the beacon is available. If somebody would like to check manually, he would have to find a PW scanner in the settings, and even this option is not always available, as If you would have to enable some things first.

**Comment by kanodia** [comment]
Physical web notifications are currently low priority notifications. Android does not show notification icon on the status bar if it is a low priority notification.

**Comment by MatthewWilkes** [comment]
I'm seeing the same thing, which is unfortunate. I'd been hoping to use virtual physical web beacons for a very time-sensitive thing (UK European Referendum 'remain' campaign), but they seem to rarely show up to people not following the steps above, which makes them unsuitable as they're not discoverable.

I *really* wish I had access to Nearby Notifications already, that looks like an awesome evolution.

**Comment by scottjenson** [comment]
Separate issues: @kanodia is talking about the level of the notification (min) so it *is* there it just requires the user to pull down to see it. We don't want this to be abused.

@MatthewWilkes seems to have a separate issue: the notification not showing up at all. We get this quite a bit from devs as they don't see the notification show up constantly. As we are trying to save power, we only scan when the user wakes the phone. Once this is working, it should show up regularly.

**Comment by funkybudda** [comment]
hi Scott,

big fan of your videos on physical web, and my team is happy that we found this post, because we just started to explore this physical web technology but our experience has been that iOS experience is less of a hassle compare to Android. In fact we made a post on estimote (we purchased a set for testing):
https://forums.estimote.com/t/physical-web-on-android-not-being-detected/4130

The way to get the physical web notification on android leaves a lot to be desired, and the way we finally got it to work was follow **@kanodia**  suggestion above.

Now if we are to build an experience around that, for android we need tell the target audience that they must make sure "chrome is not running" first. If you are on android, chrome is your default browser, you might have several tabs open. Most users would not want to force-close Chrome just to engage in a physical web experience that they're not sure if they will like or not. And to ensure chrome is fully closed, you need to get to setting/apps/chrome to hit the force close button.

Edit: I just tested by restarting my phone, bluetooth is on and chrome is active when android loaded, but the physical web notification didnt show up at all. It only showed up when I quickly disable bluetooth and enable it again. Why is the notification so inconsistent with Android? Both colleague and I are using unlocked android phone (Nexus 6 and Moto X pure edition 2015) and have all the requirements met from this page:
https://support.google.com/chrome/answer/6239299?hl=en

From the above page you can see iOS have less steps to deal with it. This is also true when I ask other co-workers with iPhones to engage in the beacon test using eddystone-url. I personally think the amount of steps an android user need to do in order to make sure they are able to engage in physical web experience will turn way more user instead of garnering new ones into this exciting technology.

**Comment by kanodia** [comment]
@funkybudda : W.r.t. : "Now if we are to build an experience around that, for android we need tell the target audience that they must make sure "chrome is not running" first. If you are on android, chrome is your default browser, you might have several tabs open. Most users would not want to force-close Chrome just to engage in a physical web experience that they're not sure if they will like or not. And to ensure chrome is fully closed, you need to get to setting/apps/chrome to hit the force close button.""

_____

These were the required steps to get physical web when it was only a part of chrome. Ensuring chrome is closed, switching on bluetooth, then location and then opening chrome used to get physical web notification. Now it is a challenge to educate people about this as there will be high chances that there chrome might be running in the background and if that is the case physical web notification will not come.

Now as physical web is a part of nearby API which is a part of latest play services (version 9.2.55), physical web scanning as become better, reliable, and even the steps are reduced and simple. In Fact UI is also better and more contextual.

Now, if the phone has the latest play services, then just by switching on bluetooth and location, a notification is received if there is a beacon transmitting an https URL nearby. The first time notification reads as "website for this location found".

Hence, now physical web notification will come in just two steps, bluetooth and location needs to be on, that's it.

Hence, making people aware of this experience will be easier compared to the previous one.

**Comment by scottjenson** [comment]
As scanning has now moved to nearby, closing this issue. If there is anything new to add, please feel free to reopen.

**Comment by priyass** [comment]
Hi Scott,

     As i understand this article eddy stone android phone notification problem comes because of nearby . When i turn on all Bluetooth,location ,physical web and WiFi , as you know chrome has default browser still Im not getting notification.One mobile notification comes only one time per day ,another mobile not that much frequently per day , another mobile not able to get per day . As i understand based on testing behavior if notification will pushed if i ignore it automatically clear status bar notify after 5 or 10 mins but if i swipe to remove it will not push notification after 24 hours. can you help out to solve this problem

**Comment by scottjenson** [comment]
Sorry but I don't have enough information. If you are running on Android 4.4+, and have latest Google Play Services, all you need is Location and Bluetooth turned on. *EVERY* time you wake up the phone it will scan and show a notification. Can you confirm your phone OS and GPS version?

**Comment by priyass** [comment]
Hi Scott,

android phone version 5+,and having latest google play service ,chrome version 54,  both location and Bluetooth on. It is in wake up mode only,still facing problem to get notification frequently

**Comment by scottjenson** [comment]
OK, it looks like there may be a bug. Sorry, a bit more info. Can you give me your phone?

**Comment by yashkant** [comment]
I have a Moto G4 plus phone running on Android Nougat, the chrome has Physical Web enabled and location permissions granted, Bluetooth and location settings are also on yet I'm unable to receive a notification from a beacon emitting URL frame of https address.

**Comment by scottjenson** [comment]
Have you tried your URL in verify.physical-web.org?
Does the beacon show up in the Physical Web app?

**Comment by yashkant** [comment]
@scottjenson Yes, I am using a verified URL and the beacon does show up in the Physical Web app. I manually scanned for beacons in Chrome (See What's Nearby) and it was also there but, there wasn't any notification thrown by it.

**Comment by scottjenson** [comment]
Our notification code was originally in Chrome, but that's all moved to Android OS so the Chrome settings aren't necessary. 

The biggest issue when testing it understanding that we're only scanning on screen wake up so put your phone to sleep and see if that helps. 

however, this is why we're now moving to more deterministic approaches. YOu'll notice that you can also add the nearby scanner to the home screen. That should always work.

**Comment by yashkant** [comment]
Yeah, the beacon scanner being present into a web browser did not make much sense, this looks better to deal with physical web separately(in OS) and then extend its support to other browsers as well.

This may not be the right platform to ask but, I wanted to contribute to physical-web as a GSOC candidate, I could not find any IRC channel for these discussions(on GSOC organisations page), please provide some direction. 

Thanks for the help.

**Comment by scottjenson** [comment]
Sorry, but we're not involved with the Google Summer of Code so don't know
who to contact.

Scott

**Comment by heypiotr** [comment]
>however, this is why we're now moving to more deterministic approaches.

Any chance you could share more details about it at this point? (:

**Comment by scottjenson** [comment]
We have an experiment in Chrome for iOS (you have to turn on the Physical Web flag) that shows results in the Omnibox. That isn't as lightweight as a notification but it seems to be much easier to explain to people.

**Comment by Chri82** [comment]
Notifications of my beacons do not appear. Only when I go into "Settings" => "Google" => "Nearby" finally found the link and suddenly appears also in the pull-down notifications
