### ISSUE TITLE
Question: Url visibility logic to improve the user experience

### ISSUE THREAD

**Issue by nicooooolas** [google/physical-web#669]
Hi,

To avoid regular physical web notifications to an user, do you have some guidelines/logic to manage the url visibility to the user? 
By example: is it possible to show a PW notification by example only 1 time by day to the user after he open 1 time the url ?

Today, if someone is near of an eddystone beacon, PW notifications will be all the time present, so the user will be tired by this : he will turn off PW or will be annoyed and will stop to check the PW urls.

Thanks!

**Comment by scottjenson** [comment]
Currently the PW notifications are all on or all off. We are looking into the ability to 'swipe away' a specific domain so you can kill a specific type beacon that you find annoying.
