### ISSUE TITLE
This is the method that works the best to get physical web notification on Android

### ISSUE THREAD

**Issue by kanodia** [google/physical-web#670]
Hi I have been playing with physical web for long.

Based on my observations, I have seen that the following pattern works everytime to get physical web on android.

The steps are:

First switch on bluetooth, then location then open google chrome( if chrome was running in background then close it and then open again)

if there is beacon transmitting an https url in the range, I am 99.99% sure that physical web notification will come.

Just to be 100% sure, Can everyone please try to follow this pattern and comment if it working or not on your smartphone device.

ALso, please mention your Android phone model.

Thank You

**Comment by Timmmm** [comment]
This worked for me. I left location on the whole time. Just killed Chrome, turned bluetooth off and on again, then opened Chrome. The notification appeared after a couple of seconds.

In general I have found its detection to be incredibly unreliable. This is despite the fact that the Nordic Master Control Panel always finds the beacon nearly instantly when actively scanning for it. iOS is also very reliably at finding the beacon, but for some reason Chrome on Android sucks (or maybe it is my device?).

I have an Xperia Z3C running Android 5.1 (yeay updates /s).

**Comment by viligaga** [comment]
Timmmm, I couldn't agree more. I think they are restricting access due to their security concerns. I'm my opinion they should do PW detection more user friendly first otherwise nobody will use it.

Smartphone: Xiaomi Redmi 3 Pro
Android: 5.1.1 LMY47V
Thread: chrome android physical web not working

**Comment by scottjenson** [comment]
There are few things going on here. First, you can't really compare the speed of MPC to Chrome. MCP is returning the raw packets (which is as you say, nearly instant) Chrome is sending everything to a server which takes extra time. 

In addition, the IOS version used a much simpler PWS, we're moving over to the production version next release. This means that the iOS and Android versions will now have identical filtering.

Finally, there was a bug in GMS Core, fixed last week, which caused the notifications to not show up reliably. That version, plus the latest Chrome, should help significantly.

**Comment by scottjenson** [comment]
Anything new here? Closing for now but please reopen if you have more info.

**Comment by schildbach** [comment]
For me the notifications are still extremely unreliable. Tested on Nexus 4, Nexus 5X and Samsungs Galaxy Tab 2. Got all updates.

**Comment by enoch80** [comment]
I'm shocked that this problem. Still available untill now cause I tested to Eddystone hardware the same pattern occurred !!! Wondering what's the problem could you please anyone who knew why tell us what's the deal here !!!?

**Comment by enoch80** [comment]
My phone Nexus 6p
