### ISSUE TITLE
Physical Web in Google Search App on iOS

### ISSUE THREAD

**Issue by russellmorton** [google/physical-web#672]
I have been demoing the Physical Web to a number of potential clients and many times they do not have Chrome installed on their iOS devices which immediately makes them apprehensive to adopting the technology in their solutions. I have noticed though that many more of them tend to have the Google Search app installed (this may be pure coincidence), but it lead me to think that the Google Search app could be used for Physical Web in the form of Google Now card. 

Has this been considered before?

**Comment by scottjenson** [comment]
Yes it has and we are not against this idea. The goal for now is to show that it's possible on both Android and iOS so we're using Chrome for both. As the project grows, this may change.
