### ISSUE TITLE
Is it possible to receive or test physical web broadcasting on desktop?    

### ISSUE THREAD

**Issue by liushihyen** [google/physical-web#675]
Hi, 

I wonder if it is possible to receive physical web broadcasting in Mac's notification center? I know that we can enable Chrome's notification by using "chrome://flags/#enable-native-notifications", but I can not receive any notification from my Eddystone beacon, the push notification works in my iPhone6s and Samsung Galaxy s6

Best,

**Comment by nondebug** [comment]
The Physical Web implementation in Chrome is currently only available on Android and iOS.

**Comment by dermike** [comment]
@liushihyen try this scan app for Mac OS https://github.com/dermike/electron-physical-web-scan or the terminal nodejs version of it (which uses notification center): https://github.com/dermike/physical-web-scan

**Comment by liushihyen** [comment]
@dermike I do appreciate for your information, I will check your projects this day
