### ISSUE TITLE
Chrome shows UNRESOLVED on short url on Android

### ISSUE THREAD

**Issue by artkay** [google/physical-web#682]
Looks like there is something wrong with Chrome's beacon detection on Android.

I have a beacon that broadcasts short URL. I am able to see it on Chrome for iOS, on Physical Web for Android, but not in Chrome on Android - it doesn’t show up on the "physical web" settings page, and on `chrome://physical-web` it shows up as UNRESOLVED. 

First, after reading the issues here on GitHub a bit, I thought it could be something with my short URL having `http://` as a protocol - so I changed it to use `https://` - still nothing.

The URL shortener app is written in PHP and uses this code for the redirection:

```PHP
header('Location: http://whatever.url.is');
die();
```

Please advise.

**Comment by cco3** [comment]
Are you redirecting to an http site?  That would be problematic.

**Comment by artkay** [comment]
I'm redirecting to `https://` website - to Instagram

**Comment by cco3** [comment]
Hm, I'm not sure.  If you show us the URL, we may be able to figure it out though.

**Comment by artkay** [comment]
@cco3 btw, why `http` is problematic? We have deployed thousands of beacons in the wild and they all are `http` (for the short URL). Will it work if the short URL is `http`, but the final destination is `https`?

**Comment by cco3** [comment]
That should work.  We only require that the destination site be https.

**Comment by artkay** [comment]
Thanks for the reply, that helps.

For the problematic url - it is https://mtag.io/eic0bk

**Comment by cco3** [comment]
@mmocny or @oahziur, it looks like there are about 6 levels to this redirect, is 5 the limit?

@artkay, You could try linking to https://www.instagram.com/art_kay_/ instead of https://www.instagram.com/art_kay_ from the shortener, and that will remove one level of redirection (which may be the issue here).

**Comment by oahziur** [comment]
@cco3 Yes. It appears 5 is the default limit in the system,  but it is configurable.

**Comment by scottjenson** [comment]
Anything new here? Closing for now but please reopen if you have more info.
