### ISSUE TITLE
Is there a separate github page for nearby notifications?

### ISSUE THREAD

**Issue by kanodia** [google/physical-web#694]

**Comment by scottjenson** [comment]
No, that is considered proprietary to the platform. We've always envisioned scanners as being able to be proprietary but still playing nice with the rest of the ecosystem. The same is true for our PWS. There is an open source version but Google has it's own.

**Comment by kanodia** [comment]
So does that mean, that issues related to it can be addressed here?

**Comment by scottjenson** [comment]
Well, not officially, no. It's part of Android and you should file bugs against them. However, we are kind of in the same building so I don't want to stand on ceremony. If you find a bug in nearby, let us know. However, please give it a few weeks, it's just rolling out and things are likely to change a bit.
