### ISSUE TITLE
Tried playing with nearby notifications. Is it still not fully released?

### ISSUE THREAD

**Issue by kanodia** [google/physical-web#695]
Hi

I tried playing with nearby notifications. I configured my eddystone UUID's, registered them and added nearby attachments to it.

I used a web URL.
I could only find a nearby notification when I configured it with Google.com or Facebook.com or Uber.com. 

I tried changing the URL then to lesser known websites and I could not see a notification with them.

Am I doing something wrong here.

**Comment by scottjenson** [comment]
Nearby notifications uses the same PWS server that Chrome uses. Anything
that shows up in one, will show up in the other.

Scott

**Comment by kanodia** [comment]
Alright,  Thanks Scott :)
