### ISSUE TITLE
Will physical web taken off from chrome as it is now a part of play services(nearby api)?

### ISSUE THREAD

**Issue by kanodia** [google/physical-web#696]
As the latest services supports nearby and thus scans for physical web URL's.

Will the physical web taken off from Google chrome and stay a part of play services or will it stay at bith the places?

**Comment by scottjenson** [comment]
Chrome will notice when Nearby is turned on and back off. We've done it this way as Chrome will work more widely (to more OS releases) than Nearby will. The goal is to have Nearby do the notfications, chrome will be there as a backup.

**Comment by kanodia** [comment]
Does this mean, that chrome scanning will only begin if nearby scanning is off. If a user is seeing nearby notification, then he would not see chrome physical web notification

**Comment by scottjenson** [comment]
The two services know of each other so if Nearby is on, Chrome won't scan.

**Comment by beaufortfrancois** [comment]
@scottjenson What do you think about adding this kind of info to the Physical Web FAQ? https://google.github.io/physical-web/faq

**Comment by kanodia** [comment]
@beaufortfrancois : If I can help you with that, let me know?

**Comment by beaufortfrancois** [comment]
You can submit a PR at https://github.com/google/physical-web/edit/gh-pages/faq.html if you wish so that the Physical Web team reviews it.

**Comment by LaurenLeavitt** [comment]
I have a Nexus 5X. If I turn off Nearby, Chrome does not scan for beacons or notify when I am near a Physical Web Beacon. I have customers with different devices experiencing the same issue ever since Nearby was rolled out.

**Comment by ferencbrachmann** [comment]
I've experienced Chrome not scanning for beacons in the last few weeks myself. Nearby was not enabled yet (I think).

**Comment by scottjenson** [comment]
It should be. If not, please go into Settings>Google>Nearby Notifications and see if it's turned on. Everyone with latest GMS core should have the new Nearby scanner in place (and Chrome turned off) Sorry for the confusion, this just happens as we move from one platform to the next. Closing for now unless there is any additional info (please feel free to reopen)

**Comment by LaurenLeavitt** [comment]
@scottjenson you wrote "Chrome will notice when Nearby is turned on and back off. We've done it this way as Chrome will work more widely (to more OS releases) than Nearby will. The goal is to have Nearby do the notifications, chrome will be there as a backup." 

Could you help myself/customers understand what a consumer interaction with an Eddystone-URL beacon should be like for the first time?

I understand that a compatible phone with Nearby Discoveries should receive a low level notification that will give the user the option to opt in. 

Since Chrome will work more widely than Nearby, what should users without Nearby expect?  Will Android Chrome users still get a notification when coming in contact with a Eddystone-URL beacon for the first time?

**Comment by scottjenson** [comment]
Sorry, I didn't explain myself well. On Android, we are transitioning from Chrome to Nearby: the primary interaction will be on Nearby. We aren't trying to create/encourage both at the same time. It's simply a means for us to transition from one platform to the next.

That being said, the Physical Web is a new technology we expect to be used in many ways. There are already other scanners being built (on iOS and Android) We view the Physical Web a bit like the web: you can use many 'browsers' yet still get to the same content. At the moment, the primary browser is Nearby but we expect others to appear over time and that's a good thing.

**Comment by LaurenLeavitt** [comment]
Just for clarification: If you have a device without Nearby (yet) will that user still get a notification with Chrome the first time they interact with a Eddystone-URL beacon?

From my understanding not all Android Devices have Nearby so I'm trying to figure out what their experience will look like.

**Comment by ferencbrachmann** [comment]
Dear Scott,
We feel that it is very important for the entire concept to have a clear and consistent path in the UX of beacon discovery. At least on Google's own assets. I understand you're working towards this and hope to see it happen as soon as possible.

A few interesting questions I got over the past few weeks:
- what about the close to 500 million Android phones without Google Play (mostly in China)?
- when and how will iOS beacon discovery be improved (a lot of clients/prospects see the widget/today screen as not very user friendly)
- will other Google iOS apps incorporate beacon discovery at some point? (some clients don't feel confident that people will download Chrome on iOS and Apple is the last to adopt this concept)

**Comment by scottjenson** [comment]
@LaurenLeavitt 
Yes, if you don't have the more recent version of GMS Core, you will get the Chrome notification. This is clearly a bit odd, we understand that. We're just trying to transition over. We felt it was better to do this than to ask users to turn on thing on and the other off.

@ferencbrachmann 
China is a challenge as they may not have GMS Core *or* Chrome. Not really sure how to handle that situation. 

iOS is clearly a challenge, we've discussed this many times. There is only so much we can do.  We have several things we're trying on iOS Chrome to help but honestly, it's not going to be as seemless as Android. We have some optimism that the widgets of iOS10 will make things a bit easier.

We're always looking at other options for IOS but nothing we can comment on at this point.

**Comment by edstros** [comment]
This blog post may help clarify some things: https://www.phy.net/blog/physical-web-nearby-notifications/
