### ISSUE TITLE
Status og Google play services 9.2.55? 

### ISSUE THREAD

**Issue by kanodia** [google/physical-web#708]
Hello

This is w.r.t the status of Google play services.

Is the release process is till on? I mean not every android smartphone has received the update, right? Do we have any estimated timeliness when it will be released to every android phone?

**Comment by scottjenson** [comment]
There is not firm date as we check continuously to make sure there are no problems as we roll it out. It's on track to be on every device in a week or two, but we can't guarantee that. Sorry to be so vague, but when you're updating 100s of millions of phones, it pays to be cautious.
