### ISSUE TITLE
App intent with URL fallback

### ISSUE THREAD

**Issue by rlaudebat** [google/physical-web#717]
Hi,

We have registered Eddystone Beacons with beacon dashboard on which we want to have App intent with URL fallback as nearby notification.
Whereas the intent is working perfectly when we want to test the URL fallback it is not.
We are using nearby API from gms and not the Chrome physical web.

is there any limitation on this feature for the time being on gms?

Thanks

**Comment by cco3** [comment]
What do you mean by "URL fallback".  How exactly are you trying to achieve this?

**Comment by rlaudebat** [comment]
When Eddystone broadcast a UID, and once registered on the beacon dashboard you can add a nearby notification. 
2 types of notification can be applied, web URL, App intent with web URL fallback and App intent with web URL fallback.

We are trying to use the **App intent with web URL fallback** and it does not work as expected

**Comment by cco3** [comment]
@scottjenson, are you familiar with this feature and what it's supposed to do?

**Comment by scottjenson** [comment]
This is not part of the Physical Web but the Nearby API. You should start here:

https://developers.google.com/nearby/notifications/overview

We unfortunately, don't know much about it.

**Comment by lalittech** [comment]
Hi , we are having same problem in case of App intent.
Our Application is on Play store for the internal test only.
Does this effect or restrict Our App intent(scheme, Host, Package Name)  working.
We had tested with other application that are public in playstore (e.g [https://play.google.com/store/apps/details?id=com.facebook.lite](url) ) and we are getting notification as part of Google Nearby Notification successfully.
