### ISSUE TITLE
Nearby Showing Double

### ISSUE THREAD

**Issue by kevinahuber** [google/physical-web#718]
Is this the appropriate place to post Physical Web Nearby android bugs? 

When I change the URL of a beacon, it shows the old URL as well as the new, for a certain period of time (more than 10 minutes). It looks like it _only_ occurs in Nearby for Android- not Chrome for iOS, Open Source Physical Web app, etc. It also seems to continue to show the old if I keep switching it.

**Comment by cco3** [comment]
We aren't the team that works on Nearby, but I'll let them know your issue.

**Comment by kevinahuber** [comment]
@cco3 Thanks! I've searched around and have not been able to find a good place to file additional bugs with Nearby- is there a place specifically for that, or should I seek out bug reporting for android.

**Comment by cco3** [comment]
Bug reporting (or various support channels) for Android would be best.
