### ISSUE TITLE
Physical Web Android not showing special characters. 

### ISSUE THREAD

**Issue by LaurenLeavitt** [google/physical-web#719]
We have noticed websites's with special characters in the meta data, such as Mandarin or Japanese, do not show up in Physical Web Chrome Android. These websites DO however show up in Chrome iOS. 

https://www.boj.or.jp/en/
https://dev-bcon4local.pantheonsite.io/demo

Can this be adjusted?

**Comment by cco3** [comment]
Hm, thanks for the report.  I'll look into it.

**Comment by cco3** [comment]
It works for me in Chrome on Android, Nearby on Android, and the Prototype app (i.e. the app from this github repository).  I'm curious as to whether or not it works for you in the Prototype app (you can get it from the Play Store; search "physical web").

**Comment by cco3** [comment]
OK, some more detail: The first one works for me, the second one has a robots.txt that disallows us to get metadata, so that's why it's not being shown.

**Comment by LaurenLeavitt** [comment]
Link 1: https://www.boj.or.jp/en/

Testing on two devices: Nexus 5, Nexus 7

Nexus 5 is only showing an old link in the Prototype App. (see screen shot) 
![nexus5 - prototype](https://cloud.githubusercontent.com/assets/14206024/16666553/cbec5618-444d-11e6-896a-5be224c3f0df.png)

Returns nothing in Chrome Android or Nearby on the Nexus 5. 

Nexus 7 Prototype App shows the correct beacon. (see screen shot) 
![nexus7 prototype](https://cloud.githubusercontent.com/assets/14206024/16666622/2b1b1908-444e-11e6-863b-f19d48c4afa9.png)

Chrome Android and Nearby on Nexus 7 return no results. 
![nexus7 chrome](https://cloud.githubusercontent.com/assets/14206024/16666640/3efee576-444e-11e6-9ca2-a4be7caf7acd.png)
![nexus7 nearby searching](https://cloud.githubusercontent.com/assets/14206024/16666642/42bb64e6-444e-11e6-92d8-2219845a0663.png)
![nexus7 prototype](https://cloud.githubusercontent.com/assets/14206024/16666646/44d9775e-444e-11e6-84de-b7150bc56907.png)

Any ideas?

**Comment by cco3** [comment]
That's not expected.  You can visit chrome://physical-web and see if it appears in the list of unresolved URLs.

**Comment by scottjenson** [comment]
One more thing: you are using a redirector (BKON) so when you make a change it takes about 5 minutes for our PWS cache to refresh. 

Also, make sure your prototype apps are using the same Physical Web Service.

**Comment by scottjenson** [comment]
Anything new here? Closing for now but please reopen if you have more info.
