### ISSUE TITLE
Favicon not appearing in some Android devices in notification

### ISSUE THREAD

**Issue by macpham** [google/physical-web#736]
What dictates how the physical web notification will appear on a device? I have two Android devices here with the same version of Chrome and one doesn't get the favicon.

BTW When I go to chrome://physical-web and "Browse The Physical Web", I see all the favicons on both devices.

Samsung Galaxy S7
Android 6.0.1
Chrome 51.0.2704
![physicalweb_notification](https://cloud.githubusercontent.com/assets/1777724/17103280/8fe20508-524b-11e6-9744-959d1b810d57.png)

Nexus 4
Android 5.1.1
Chrome 51.0.2704
![physicalweb_notification2](https://cloud.githubusercontent.com/assets/1777724/17103316/c14ca17a-524b-11e6-850a-74da2a3869cf.png)

**Comment by scottjenson** [comment]
There is a bug in the Nearby scanner (not chrome) that specified the minimum size of the favicon in android DP units and not actual pixels. This means, depending on the device, some times the minimum test will fail. We're fixing that!

The solution, in the short term is to increase the size of your favicon. I would increase it to 64x64 and use PngCrush on it, it should keep the size down.

**Comment by macpham** [comment]
Thanks for the quick explanation Scott.

**Comment by holgermertens** [comment]
John, I've noticed a different behavior. On our page the icon is always correctly shown with nearby notification but sometime not shown with the physical web notification.

![no-icon-in-physical-web](https://cloud.githubusercontent.com/assets/20512817/17136630/d15ff56c-5336-11e6-925b-d19201b9b786.png)

**Comment by scottjenson** [comment]
I'm a bit confused. You shouldn't be seeing both notificaitons at once. If Nearby is running, Chrome should automatically turn off. Are you manually turning Chrome back on?

As to your favicon issue, that too is confusing as they both use the same backend to retrieve the information about your page. Could you let us know the URL so we can poke around?

**Comment by holgermertens** [comment]
Exactly, that's how I did this. For testing reasons.

The same backend? That's surprising, because sometimes both gave different cached versions of the site at the same moment.

![physical-web-different-notification](https://cloud.githubusercontent.com/assets/20512817/17141253/b8155c18-534b-11e6-922a-2160c5c19210.JPG)

For the URL you got an E-Mail to your personal account.

**Comment by scottjenson** [comment]
You're just seeing differences in how they cache results. 

As to your icon issues, I'm looking into it further. However, you have a VERY exhaustive list of favicons in your markup. Any particular reason you're working so hard? If feels a bit overkill and just adds to your page weight.

Scott

**Comment by holgermertens** [comment]
Of course.

We added them, because the app icon wasn't shown in notifications. So we tested different icons. We first thought, it's our fault.

Later they will be replaced with usable icons for the different stations, for example bus icon für bus departures, tram icon for streetcar departures,...

**Comment by cco3** [comment]
Sorry, but the current Chrome feature does not show favicons in the notification, only in the activity that lists URLs.

**Comment by macpham** [comment]
I thought it does show the favicons in the notification as seen in the first post above with my Nexus 4.

**Comment by nondebug** [comment]
@macpham: The notification in the Nexus 4 screenshot looks like it came from Nearby, which does show favicons in the notification.  The diamond-shaped badge in the corner of the notification icon is the Nearby logo.

@holgermertens: I don't see any Chrome PW notifications in your screenshots (they should be badged with a small white Chrome logo).  I think the top notification is coming from the [Physical Web app](https://play.google.com/store/apps/details?id=physical_web.org.physicalweb).  You can long-press the notification to find out which app created it.

**Comment by holgermertens** [comment]
If it's so, then there was never any Chrome Physical Web Notification.

**Comment by scottjenson** [comment]
When Nearby is active, Chrome stops notifications so the user isn't double notified. As this issue has been cleared up, I'm closing it. However, please feel free to reopen if you have further questions.

**Comment by holgermertens** [comment]
Even if i turn off nearby, there is no thing like a Chrome Notification.

**Comment by cco3** [comment]
Right, that's WAI for the moment.  If someone has turned off Nearby notifications, we assume they don't want the same notifications coming from a different app.  We only turn on chrome notifications if Nearby is completely disabled on the device (not something the user can trigger).  I know this isn't ideal, but we are still trying to figure out what the right interaction between these two clients should be.
