### ISSUE TITLE
Android Physical Web app: Unresponsive Links

### ISSUE THREAD

**Issue by retolist** [google/physical-web#748]
Currently, when we open the Physical Web app (version 0.1.857 with default settings on Android), then pull to refresh and tap a scanned link immediately, nothing happens. We have to wait several seconds until we are able to open the link in the browser by tapping it. The preceding version of the Physical Web app (0.1.856) and other apps like Decode or BKON Browser don‘t show this annoying behavior. We can reproduce the issue on two device models, and with beacons from two different brands. What’s going on here?

**Comment by scottjenson** [comment]
Well, that's embarrassing. Looking into it. Thanks!

**Comment by retolist** [comment]
No worries, thank you for looking into it!

**Comment by scottjenson** [comment]
Actually, I've been told this has been found and fixed in master. We're just lining up a few things before we do another push to the Play store. Hope to do that in a few days

**Comment by retolist** [comment]
Great news, thanks. We are looking forward to the next version.
