### ISSUE TITLE
duplicate nearby notifications for a beacon

### ISSUE THREAD

**Issue by ferencbrachmann** [google/physical-web#751]
Setup:
1 Eddystone EID beacon set up through Nearby
1 Eddystone URL beacon transmiting a URL

About 3-4 times in the last 16 hours only the Nearby notification is displayed but it is displayed twice. Mostly it's working fine though. See attached screenshot.

![2016-07-28 19 07 24](https://cloud.githubusercontent.com/assets/20400452/17246569/430ab244-558d-11e6-82f2-accec1525825.png)

**Comment by YogeshDabade** [comment]
@ferencbrachmann  I have also encountered Same Issue.It happens when we Off bluetooth,but the notification is still there and again when we ON Bluetooth ,One more Notification is seen

**Comment by ferencbrachmann** [comment]
I never have BT off, so that's not the cause for me.
