### ISSUE TITLE
Nearby is turned off, Chrome is not giving PW notification. 

### ISSUE THREAD

**Issue by LaurenLeavitt** [google/physical-web#757]
I have Nearby Discoveries turn off, Physical Web in Chrome turned on, Chrome Notifications turned on and I am still not seeing Physical Web Chrome Notification. 

I am on a Nexus 5, my colleague is having the same issue. 

Any suggestions>?

**Comment by jeffprestes** [comment]
+1

- Jeff Prestes

Em 2 de ago de 2016 1:06 PM, "LaurenLeavitt" <notifications@github.com>
escreveu:

**Comment by cco3** [comment]
This is WAI for the moment.  If someone turns off Nearby, we assume they don't want to see notifications for the Physical Web, and thus we do not show Chrome notifications.  I know it's not perfect.  We are still trying to figure out how multiple notification-based clients are supposed to interact.

**Comment by LaurenLeavitt** [comment]
Okay, thanks for that info. 

Trying to have a better grasp on what consumers should expect.  

Since Chrome will work more widely than Nearby, what should users without Nearby expect? Will Android Chrome users still get a notification when coming in contact with a Eddystone-URL beacon for the first time?

**Comment by cco3** [comment]
If Nearby is not on the device, Chrome will send a notification (when it's in a state where it has location permission, a location provider, BT is turned on, and a beacon is around).

**Comment by ferencbrachmann** [comment]
@LaurenLeavitt If by "widely" you mean in terms of penetration it might not be the case. Google Play is on about 1.5bn Android phones, 78.5% of that is 4.4+ so that's close to 1.2bn phones. Chrome had a total of 1bn MAU on iOS+Android, in April, about 850 million of that is on Android.

**Comment by LaurenLeavitt** [comment]
@ferencbrachmann Scott Jenson had made the comment about Chrome working more "widely" than Nearby so I was just referencing that. But he made further clarification here: https://github.com/google/physical-web/issues/696

Thanks for the info. though!
