### ISSUE TITLE
Chrome Physical Web problem

### ISSUE THREAD

**Issue by gconno3** [google/physical-web#777]
I have multiple beeks beacons and have programmed them through the beeks app. However, when I go to the chrome physical web widget, I do not see the beacon and/or the URL. It just says the physical web is on and shows nothing else. I am on the latest version of IOS and all of my apps are updated. This is also happening for my coworker, we have the same phone (iPhone 6). Any feedback is appreciated.

**Comment by ferencbrachmann** [comment]
I suggest you try these steps from my blogpost on this subject:
http://blog.beeem.co/2016/03/top-4-things-to-watch-out-for-on-chrome-for-android-with-beacons/

Let me know if you still have issues!

**Comment by scottjenson** [comment]
We are very close to releasing a developer page that will diagnose problems
like this. However, 99% of the problems are solved by checking the
following things:
1) Does your website use HTTPS?
2) Does your website block google.com w/ robots.txt?
3) Is your website behind a login prompt/firewall?

On Wed, Aug 10, 2016 at 12:25 PM, Ferenc Brachmann <notifications@github.com

**Comment by gconno3** [comment]
Thanks, I'll try those ideas out!

**Comment by jeffprestes** [comment]
Hi All,

@scottjenson, unfortunately I think this page could be on 1% :
https://alelonoconarh.com.br/welcome/index.php
it has HTTPS, there is no robots.txt or any other HTTP header blocking the
crawler and it is not behind a firewall or there is no login page.
Do you have any guess what might be happening?

Thanks in advance!

-Jeff

**Comment by ferencbrachmann** [comment]
@jeffprestes special characters in the title/description maybe?

alternatively you can try embeding this into a Beeem landing page with the URL tool or iframe-it into an info tool!

**Comment by scottjenson** [comment]
When I try that link, I get a 404. That would certainly do it ;-)

**Comment by ferencbrachmann** [comment]
@scottjenson It is not working now, but it worked fine 2 hours ago.

**Comment by gconno3** [comment]
I don't believe the issue is necessarily the website, as it works on our lab's iPad and one of my other coworkers iPhones. I guess what I'm trying to say is that it shows up on some of our devices but not others.

**Comment by scottjenson** [comment]
It's hard to diagnose a problem when the website comes and goes. The fact that I can't see it is not a good sign. A more objective test would be to plug it into a web page tester, such as https://www.webpagetest.org and see how it performs. If they can't see it, it confirms you have some type of DNS problem.

**Comment by jeffprestes** [comment]
Hi @scottjensen and all,

We had changed it to static .html for test purposes but as well mentioned
by Ferenc it was working.
But even https://www.alelonoconarh.com.br/welcome/index.html
<https://alelonoconarh.com.br/welcome/index.html> it doesn't work either.
The short URL is: http://bit.ly/2blqd7i
I had reviewed all docs, tested it against webpagetest.org (see the
results: https://www.webpagetest.org/result/160811_ME_19D8/ ) it worked.
Tested it using Physical Web App Android and iOS and it worked. It worked
at all those places and apps except Chrome.
I can't find a technical reason for this.

I appreciate your assistance and review on this issue.

Thanks,

-Jeff

**Comment by scottjenson** [comment]
Sorry for the delay. I've just run this through verify.physical-web.org and everything works, but slowly. This implies that the redirection is taking a long long. If it takes too long, the phone client will not display it (but it will show up on a 'rescan'. I'll close this issue for now but if you still have an issue, please reopen.
