### ISSUE TITLE
duplicate nearby notifications for a beacon when using a forwarder

### ISSUE THREAD

**Issue by ferencbrachmann** [google/physical-web#781]
One of our clients had the following issue:

The URL encoded on the beacon: https://beeem.co/em000004

The attached screenshot shows that the cached "old" final URL and the "new" final URL are both displayed.

![screenshot_20160817-170352](https://cloud.githubusercontent.com/assets/20400452/17747601/d1bf6d18-64b5-11e6-8da2-02e4aa35ab84.png)

**Comment by kevinahuber** [comment]
Could related to #739 (Caching of Nearby URLs)

It currently caches on the broadcast URL, but also on redirects. So it's not treating one broadcast URL as one beacon with one destination, with no way to bust this behavior (currently).

**Comment by scottjenson** [comment]
Let me check. Get back to you in a bit...

**Comment by scottjenson** [comment]
This is a bug that will be fixed with the next release of Play Services. However, note this bug only affects attachments to UID beacons, not Eddystone-URL beacons.

**Comment by ferencbrachmann** [comment]
Dear Scott, this is an Eddystone URL beacon. We did identify the issue you're refering to also but that's not the bug in this case.

**Comment by scottjenson** [comment]
OK, sorry. I went back to the Nearby team and they confirmed that this will also affect Eddystone-URL as well (The original bug I reviewed only discussed the attachment).  They feel that both of these will be fixed with new GPS release coming in a few weeks.

**Comment by ferencbrachmann** [comment]
Has this promised GPS update been launched? I still got a duplicate notification a few days ago.

**Comment by scottjenson** [comment]
It is still there and in the pipeline. There is a rather nasty (unrelated bug) in Nearby that has shown up and is slowing everything down I'm afraid. The fix is going to be delayed until the next push 8 weeks later.

I'm very sorry for that. We're working as hard as we can to get this out there.
