### ISSUE TITLE
Physical Web Android app hangs when editing URL on beacon found message

### ISSUE THREAD

**Issue by sebflipper** [google/physical-web#782]
Editing a Physical Web beacons URL in the Android app hangs when the button on the beacon is pressed, puting it into config mode, app displays "beacon found", but it does not allow the URL to be set.

I've tried resetting the app and beacon to no avail.

Sometimes an "API key not available, please update settings." notification is displayed.

* Physical Web beacon version 1
* Samsung Galaxy S7
* Android 6.0.1
* Physical Web Android app 0.2.0

**Comment by scottjenson** [comment]
Yeah, we've put all of our "Edit URL" energy into the Eddystone Beacon Configuration web page (http://cf.physical-web.org) Please use that going forward. The existing 'Edit URL" menu item in the Physical Web app is left over from our original beacon and it's honestly just confusing to have it still around. We're going to remove it on our next release (in about 2 weeks)
