### ISSUE TITLE
PWS Behavior and Dynamic URLs

### ISSUE THREAD

**Issue by angst7** [google/physical-web#785]
I'm seeing an issue in which the PWS proxy servers are sending requests that don't appear to be on behalf of any client.  I don't know if this is related to the caching behavior issue #739 , but I don't think it is.  Here's the general flow of the issue:

A beacon (physical web weather station) base64 encodes some data and makes a url:  https://r1pl.com/AAAAAQEt4fB~  for example.  A nearby phone sees this and generates a request via PWS to fetch the data.  These URLs update about every 5 minutes (chosen to prevent the cache issue from creating a bunch of duplicates).  The data is logged at the server as history.

The problem occurs when I turn off the beacon.  (Only one such beacon exists, currently) Requests -- apparently old requests -- of the correct form continue to arrive to the server from the PWS proxy servers even with no beacon transmitting this data.  There doesn't seem to be a clear pattern to which URLs are resent or when, but they continue to be for over 12 hours after turning off the beacon.  

Does the PWS proxy system continue to recheck old URLs without any prompting from a PW enabled app sensing the URL?  (It seems this is so)  Is this intended behavior?

Thanks.

**Comment by scottjenson** [comment]
I wonder if this is an artifact of the caching bug we saw when moving over to Nearby. @mmocny do you have any context for this?

**Comment by scottjenson** [comment]
This clearly got lost. Sorry about that. I'm now cleaning up old issues. Are you still experiencing this issue? If so, any new information?

**Comment by angst7** [comment]
Thanks for following up.  It is ongoing.

The main issue is that the urls are only advertised for five minutes, but the PWS servers will request these urls periodically long after they have been transmitted by any beacon.  

As an example, last week I gave a talk on beacons at a local GDG meeting.  I ran a weather station beacon example for an hour or two at the meeting, then shut it off.  About five days later, a block of five requests for weather station beacons and the associated content were received in the space of about a minute and a half.

Each request started by fetching a previously broadcast URL:

`66.102.6.196 - - [28/Sep/2016:04:51:15 +0000] "GET /AAAAAUc-ZwB~ HTTP/1.1" 301 247 "http://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&ved=0CFwQFjAB&url=https%3A%2F%2Fr1pl.com%2FAAAAAUc-ZwB~&ei=QUzrV5XnG7vClwXmHQ&usg=AFQjCNFznerlNEzkO8X07uDdPecpoF1juQ" "Mozilla/5.0 (Linux; Android 6.0.1; SM-N920V Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.98 Mobile Safari/537.36" "-"
`

Then fetched the redirect page and any associated content.

The strange thing is that they appear to be proxied requests from real phones.  In this instance among the requests were three unique broadcast URLS: 
* /AAAAAUc-ZwB~
* /AAAAAQEwY8B~ 
* /AAAAAUEoJUB~

The last two were requested twice each.  These requests also looked like they came from four distinct phones:
* (Linux; Android 6.0.1; SM-N920V Build/MMB29K)
* (Linux; Android 6.0.1; SM-G920V Build/MMB29K)
* (iPhone; CPU iPhone OS 9_3_4 like Mac OS X)
* (Linux; Android 6.0.1; SAMSUNG SM-G920P Build/MMB29K)

But, as I said previously the beacon that broadcast these did so five days previously, and each would have been uniquely broadcast for no more than five minutes (unless the weather readings all remained unchanged).

So I'm having trouble understanding how the PWS servers cache and re-check stale URLs.  Knowledge of this would be helpful if someone wants to use the broadcast URL to send data back to the server in a reliable or time-dependent way.

It's not a super high priority. I can work around it by adding some sequence or timing into the data encoded in the URL so the server knows if a request is stale and needs to be ignored, but that consumes precious advertising bytes.

Thanks.

**Comment by adriancretu** [comment]
I don't see how this is a PW issue since you got hit by actual user phone's browser, not even GoogleBot. IMHO your URLs were cached by some app and later visited (might as well be a saved browser tab that wasn't redirected yet because it was offline). I think it's up to your back-end to handle expired URLs.

**Comment by angst7** [comment]
@adriancretu I've considered that.  And you're right - it's not GoogleBot hitting the server.  It's not a normal request from, say, Chrome on a users phone (which would show the phone IP).  When someone clicks on a beacon notification, the short/redirect URL is not requested, instead the destination URL is requested and loaded from the phone's IP, so that's not what's happening.  This would also rule out a stale, open tab, as it should behave in the same way if refreshed.   

It looks like a result from a web-search, perhaps, but again - all the IPs are google.  No actual phone browser ever hits the server (from its own IP).  Additionally, these requests all came as a burst within a minute or so of each other, many days after the beacon was turned off.  So if it's local caching behavior on a user's phone I wouldn't expect three or four of them to all fetch the urls within seconds of each other many days after seeing the beacon.

I agree that there are back-end solutions for dealing with this, but that's not really the point of my question.

**Comment by adriancretu** [comment]
Did you consider it might be Google's IP because of the "accelerated browsing" feature in Chrome? I'm not sure how it's called, it's basically the thing Chrome asks when first opened (and which I always skip, so I never remembered the branding).

**Comment by angst7** [comment]
No, I hadn't considered that.  I'm not sure what feature that is, but I'd be interested to look into it.  In this case, however, I don't think it would explain why the advertised URL was being fetched instead of the destination URL (when you click on a PW redirect result, chrome begins fetching the URL to which it redirected), or why so many distinct phones would be fetching old URLs in such a narrow band of time (a minute or so apart).  Unless it runs independently of user action on some fixed schedule, perhaps.

**Comment by adriancretu** [comment]
Nevermind, the Chrome data saver feature only works for http sites. So you may be right, Google might crawl your page using mobile user-agents (maybe for ranking purposes).
Your URL doesn't have any HTTP cache headers set, so it would make sense for Google to periodically re-index it.

**Comment by angst7** [comment]
Addressed in #820

**Comment by angst7** [comment]
Reopened per https://github.com/google/physical-web/issues/820#issuecomment-253990493

**Comment by mmocny** [comment]
Fantastic investigations, folks.  This information gives us a lot to go on.

Most likely, this is just an expected side effect of some of our backend systems.  We do periodic scans to make sure we have up to date content, and to help filter out shady stuff.  All of the behaviours you describe are not unexpected.

However, it could also be some issue with bad client-side caching of nearby beacons + needless requests to PWS.  I don't necessarily suspect this right now, but it would also have the above symptoms.  The bursty-ness of some of the traffic you are seeing is my only concern.


Judging by your great understanding of how the PWS system works, you probably do realize that we don't proxy real user requests through PWS, and that PWS does not make calls to your backend with each nearby user -- and have now found that sometimes PWS/other systems make calls outside of user requests as well.  Sometimes we also delay PWS and/or make spurious requests, and will probably start to increase how often we do that.

As such, when you mention "data logged at server for history", just bear all that in mind.

Thanks, and Cheers.

**Comment by angst7** [comment]
For my use, I think this is sufficient.  After all, Google won't be the only company making a scanner,  so I don't think a crystal clear understanding of these kinds of back-end side-effects should be necessary. 

The detail provided here and in #820 were very helpful.  I'm happy to close this if no one else has further questions.  Thanks!

**Comment by mmocny** [comment]
Thank you Matt, best of luck.

**Comment by jsiebens** [comment]
@mmocny thanks for the clarification. One last question: does it mean that some backend systems crawl our urls with mobile user-agents? Just like @angst7 mentioned before, we are also seeing some requests coming from Google ips with mobile user-agents, even when our beacons were stopped broadcasting the urls. And if I understand correctly, does requests are not coming from the PWS

**Comment by mmocny** [comment]
Yes, we have systems for testing, validation, abuse, etc.
