### ISSUE TITLE
URL not detected by chrome nor physical web

### ISSUE THREAD

**Issue by norhanmhmd** [google/physical-web#790]
i am trying to configure a beacon to send the below url 
https://www.zad-foundation.com/zad-ad/ 

but it wont get displayed by neither chrome nor physical web app, while other links like google maps link for example works perfectly fine

Appreciate your help please

**Comment by beaufortfrancois** [comment]
It looks like https://www.zad-foundation.com/robots.txt says to Physical Web GoogleBot to not index content hence why you're not seeing it there.
This is why also looking for https://www.google.com?q=www.zad-foundation.com doesn't return the website.

**Comment by norhanmhmd** [comment]
thanks for your reply, i enabled the indexing and still not working, does it reflect immediately or should i give it some more time?
also the website does not have much content only display just one image per  page and nothing more, could this be a factor why it is not displayed?

Thanks alot

**Comment by beaufortfrancois** [comment]
Give it a little bit of time ;)

**Comment by norhanmhmd** [comment]
it works now thanks :)
