### ISSUE TITLE
Meta Data with a 301/302 Redirect

### ISSUE THREAD

**Issue by watstyl08** [google/physical-web#797]
Say I'm broadcasting the following URL;

https://blank.info/123
The meta-data on this URL is "This is a blank domain"

Say I have a 301/302 redirect from blank.info to another URL --> https://destination.com/123
The meta-data on this URL is "This is the Destination domain"

Will Android/Chrome display the meta-data of blank.info or destination.com when it detects my eddystone beacon?

**Comment by nondebug** [comment]
It will display the metadata for the destination, assuming the Physical Web service is able to crawl the destination page.

**Comment by watstyl08** [comment]
Do you know if it will also display the URL for the destination?

**Comment by scottjenson** [comment]
For our PWS, it always resolves the URL first, THEN gets the meta data so everything displayed will be for the final destination page (assuming the PWS can reach it properly)
