### ISSUE TITLE
How do I connect Physical web android app with my laptop windows/Linux if I don't have the beacon as a developer

### ISSUE THREAD

**Issue by RajPratim21** [google/physical-web#798]
I am new to physical web and need help I am at my niche stages
As a developer sometimes the beacons may not be accessible to you . What if we can simulate a desktop environment for the beacon .
Thank  you

**Comment by derekshull** [comment]
Hi Raj,

There are a couple of options that you could start with. If you have an Android device there are a few beacon apps that have the ability to use your device as a beacon. I know off the top of my head that Radius Networks has an app that does this: https://play.google.com/store/apps/details?id=com.radiusnetworks.locate

If your desktop machine has Bluetooth you could use NodeJS to make the machine transmit a beacon using this repo: https://github.com/don/node-eddystone-beacon

If you'd like I could also send you a two week free trial of our beacon and content platform at www.beaconsage.com. If you're interested just email me at support@beaconsage.com and we can work out the details.

**Comment by scottjenson** [comment]
@RajPratim21 just to be sure, are you asking about using a laptop to simulate a beacon? If so, you can use @dermike 's excellent [mac app](https://github.com/dermike/electron-slide-beacon) to do that

**Comment by RajPratim21** [comment]
Yes sir I was asking about stimulating beacon via laptop having windows 10 or Ubuntu 16.04  and also equipped with Bluetooth facility 
Thank you

**Comment by scottjenson** [comment]
OK, then we're back to @derekshull 's advice. You'll need to (of course) have BT functionality on your laptop and then use something like Node as he linked to.

**Comment by jeffprestes** [comment]
Also, @RajPratim21 <https://github.com/RajPratim21> , you can check these
examples out:

https://github.com/jeffprestes/go-eddystone-url
https://github.com/jeffprestes/node-eddystone-url

Then you can set your own URL and create your own App.

**Comment by RajPratim21** [comment]
Thank you so much to all, 
 I will proceed as been directed by all of you
