### ISSUE TITLE
on clicking the FatBeacon demo app crashes with log java.lang.NoClassDefFoundError:

### ISSUE THREAD

**Issue by RajPratim21** [google/physical-web#806]
When tried to open the FatBeacon Demo ,app crashes with following message and highlights 
this line "private final AdvertiseCallback mAdvertiseCallback = new AdvertiseCallback"
 and reports java.lang.NoClassDeffFoundError do we have to put the demo file in some other package right now it's under Org.Physica-web.demos. where as Wifi direct is working fine while bwing in same folder.
![screenshot from 2016-08-31 01-55-30](https://cloud.githubusercontent.com/assets/15442871/18105775/5ac48900-6f1e-11e6-9734-1dcedd51efc0.png)

**Comment by hayesjordan** [comment]
It should work with the demo file in the demos directory.  What Android version are you using?

**Comment by RajPratim21** [comment]
Sir I am using android kitkat version 4.4.4

**Comment by hayesjordan** [comment]
Unfortunately KitKat does not support broadcasting over BLE so you will not be able to run the FatBeacon demo. I have a  fix for this (#809) so that KitKat users do not see the FatBeacon demo available.

**Comment by RajPratim21** [comment]
Thank you  #hayesjordan
