### ISSUE TITLE
Physical web causes problems in set up with android studio

### ISSUE THREAD

**Issue by RajPratim21** [google/physical-web#819]
Physical web causes problems in set up with android studio it can't find the files under libs folder 
specifically Collections and PWSclient 
though if collection folder is copied from libs to app/src/main/collections
it works fine also get build and everything works
Can we treat the copying of files from lib ..to app/... a solution to above problem I thought that may be files under app/.../main/physicalweb can't access the files? I have submitted a pull request #818 which gave error here but worked fine in my laptop

**Comment by cco3** [comment]
Thank you for filing the issue.  Unfortunately copying all the files over to another directory isn't a sufficient solution.  We'll have to figure out what studio is doing that is different from the gradle configuration.
