### ISSUE TITLE
Physical Web URL not being detected anymore

### ISSUE THREAD

**Issue by oninross** [google/physical-web#821]
**History lesson**
I dont recall changing any settings in my phone nor in the Chrome App.  I walked passed by a store that I didnt know that was broadcasting a Physical Web URL.  I swiped down my notification and found the webpage.  It was the first day that I knew I will be working on this technology.

**Initial testing**
I did my first set-up and was pretty much successful (keeping in mind I didnt change any settings on my phone nor the Chrome App).  I managed to broadcast a URL and change the destination URL with ease.  I can manage to detect the URL on my Nexus 5 and on any iOS device.

**Fast forward to today**
The beacon is still broadcasting a URL.  However, as I pull down the notification drawer, its not detecting the URL anymore.  Its actually sporadic.  Sometimes it shows, sometimes it doesnt.  Any ideas why this is happening?  Even if I use the Physical Web App, it cannot detect the URL.

**Question**
Does a user have to enable Physical Web and/or Nearby on to detect the URL?

**Comment by ferencbrachmann** [comment]
You can validate your URL with the current Google services at:
https://beaufortfrancois.github.io/sandbox/physical-web/url-validator/

**Comment by oninross** [comment]
Just checked and was a sucess

**Comment by oninross** [comment]
**Update**
I was playing around with some URLs and see what can Nearby notifications pick up.  Here are some of the links that I used:
- https://oninross.github.io/project-nat/
- https://www.facebook.com/daywithaminifig/
- and a third link that has query parameters in the URL (I cant disclose the link just yet as its a private repo)

All of these links follow the needed requirements
- HTTPS URLs
- Mobile optimized
- Bluetooth Enabled
- Location Enabled

**Scenario 1**
A "brand new user" with all default settings will not see the notification, even with the Physical Web enabled in the Chrome App

**Scenario 2**
I am using my Nexus 5 as a testing device.  I started out with https://www.facebook.com/daywithaminifig/ to be broadcasted.  I initially had no problems detecting the URL until I dismissed it.  The notification never came back.

**Scenario 3**
I am using my Nexus 5 as a testing device.  I started out with https://www.facebook.com/daywithaminifig/ to be broadcasted.  Then I switched the destination URL in bit,do to https://oninross.github.io/project-nat/.  Had no problems detecting the 2nd link.  But when I switched to the 3rd link (with query params), The notification just didn't show up anymore.

What am I missing?

**Comment by scottjenson** [comment]
I am so sorry this got lost. I was travelling and just fell behind in github triage. are you still having this issue? Keep in mind that nearby only scans on screen wake up so if you're walking around with your phone on, it won't show up.

What people are doing to force a scan is to click the Nearby icon in the quick setting drawer.

Scott

**Comment by ferencbrachmann** [comment]
Please read this post as it might have been related to your issues:
https://groups.google.com/forum/#!topic/physical-web-discuss/VJ_N3mvm9Do

**Comment by oninross** [comment]
Hi scott, 

With the query string method, I rewrote my web app.  It was not using query string and it was working.  Let me try it again and I will keep you posted.

I apologize but yoi lost me at "What people are doing to force a scan is to click the Nearby icon in the quick setting drawer." I dont see it on my phone.  I will double check on other Android phones.  My thoughts are this is quite troublesome for some users who doesnt know about this (like me).  My observation is that the moment they have dismissed the notifications (intentional or by accident), there is no easy way of showing nearby notifications again unless they: a) wait for X number of hours b) go to settings manually and reset the nearby notifications.

Is it possible for you to adjust this?  The experience that I am looking at is similar to the Physical Web app.  If you have dismissed the notification, the moment you close and wake up your screen, it will scan the area again thus showing the notification again.

While in the topic of Physical Web app, is it possible to seggregate the links into different notifications instead of combining it into one (similar to the Physical Web app)?  Experience wise if the user manages to discover different links in the area, it would be nice to let the user choose in the beginning instead of tapping twice (first being the notifications which keads to the list), then tapping on the link they are interested on

**Comment by scottjenson** [comment]
Keep in mind that for the next few weeks, we're in a confusing situation. We hope to have the situation fixed with the next release of Google Play Services. 

We have noticed that while notifications do work well for the random walk by scenario, there are just too many situations when you can't 100% count on them. The most obvious example is when users 'dismiss all'. The Physical Web notification will eventually come back but it'll take awhile and there are times you just want to look around you *now*.

That is why the nearby team put in a menu item to place a nearby icon on the phone's home screen. You can get it two ways: through a menu item in the nearby list view and through the on-boarding process. Again, not perfect, but we're experimenting.

We're also looking at ways of exposing it in Chrome more directly, we're hoping to discuss this approach when it ships in a month or two.

**Comment by oninross** [comment]
**The most obvious example is when users 'dismiss all'.** 
- I agree.  For better experience in my opinion is that the notifications will always be there unless they have muted the link.

**We're also looking at ways of exposing it in Chrome more directly, we're hoping to discuss this approach when it ships in a month or two.**
- My opinion, I like what the Physical Web app is doing.  You wake your phone up, slide down the notification drawer, and you see the notifications there.  Dismiss it, the next time you do the same drill, the notification will always be there until it has been muted by the user.

**Comment by deviousasti** [comment]
I've had some trouble with this as well. Before, it was a matter of luck whether it would show up in Nearby - switching the Physical Web Service in the Physical Web application to "Development" got it to start working again. This gives me hope that once you guys figure out the UX part of it, it should start working reliably. I imagine scenarios like being in front of a meter and getting a page to log the spot reading would then be feasible.

**Comment by scottjenson** [comment]
This is a complex problem and while having notificaitons has been a huge step forward, we clearly need a guaranteed way of bringing it up every time. For M and N users, you can tap on the Nearby icon and it will always give you the list. However, it's clearly not obvious/easy to do this. You can also install a homescreen shortcut but this too isn't obvious. You can't say we're not trying... ;-)

We hope that adding something to Chrome will also help. This takes time to get through the production pipeline and we hope to talk about it soon when it ships. 

Closing now as there doesn't seem to be any specific issue that is open. Feel free to reopen if I've missed something.
