### ISSUE TITLE
Nearby/PW is inconsistent

### ISSUE THREAD

**Issue by adriancretu** [google/physical-web#824]
[EDIT] - I closed this issue since I was testing with bad variables (beacon was advertising too rarely among other things). I even managed to register and see URL attachments to EID beacons. My last point still stands though.

I spent some time trying to get Nearby Notifications to work for an EID beacon (if that's not possible, my apologies - beacon is registered and visible in Beacon Tools). I never managed to, so I tried the simples possible case instead - a single Estimote physical beacon, configured as an Eddystone URL pointing to https://www.wikipedia.org

Nexus 5: Android 5.1 / GPS 9.4.52:
- BT on / Location on / Chrome PW on
- extremely complicated to manage to show a notification; sometimes it shows after screen is turned off and on, most times nothing happens; it seems that when the screen is turned on after a longer sleep period, the probability of any notification to appear is close to zero.
- Physical Web app shows the beacon, at the same time Nearby says that no links are around. The beacon is standing 30 cm away.

Nexus 6: Android N / GPS 9.4.52:
- BT on / Location on / Chrome PW on
- also buggy; notification appears after screen off/on with 50% probability, and its not even the Nearby notification, its the Physical Web app's one...

There are nice potential ground-breaking ideas for PW, but there needs to be more obvious ways to bring things up to the user, or at least make it an option based on all sorts of criteria (example: URL domain vs any installed apps or registered service workers - they would likely imply user agrees to be "annoyed"?). Absolutely nobody will randomly turn on their phone desperately looking for a hidden notification, except us developers :)

**Comment by scottjenson** [comment]
Adrian, don't be shy about this! If you feel you have a case where things aren't showing up, please don't be shy about posting another issue.
