### ISSUE TITLE
Configuring Physical Web tokens? 

### ISSUE THREAD

**Issue by edent** [google/physical-web#826]
I notice that the latest release of the Android client doesn't allow people to configure Beacons any more. 

How do I change the eddystone destination of the V2 beacon Google gave me?

**Comment by cco3** [comment]
Use this tool: https://beaufortfrancois.github.io/sandbox/web-bluetooth/eddystone-url-config/index.html

You may need Chrome 53 and you will have to enable web bluetooth

**Comment by edent** [comment]
That works on Android Chrome! Many thanks.

Any reason why it isn't part of the app? Very confusing!

**Comment by cco3** [comment]
The app is a place for us to try experimental features, and now that we have a primary configuration utility (the web tool) there's no need for a configuration feature in the prototype app.

**Comment by edent** [comment]
I get that - and it's your app to do with as you please - but how was I supposed to find that link?

The [documentation](https://github.com/google/physical-web/blob/master/documentation/android_client_walkthrough.md) still shows configuring in app.  If I hadn't read the changelog in Play Store, I'd have thought my tokens were broken.

**Comment by scottjenson** [comment]
Thats a good point, we should have updated the web page to remove that
confusion.

**Comment by beaufortfrancois** [comment]
@edent FYI http://cf.physical-web.org is the canonical URL

**Comment by edent** [comment]
@beaufortfrancois thanks! Is that linked or documented anywhere?

**Comment by beaufortfrancois** [comment]
Yes, you can see it in the "Configure beacons" section in https://google.github.io/physical-web/resources
