### ISSUE TITLE
Same Urls with parameters (GET) : random display...

### ISSUE THREAD

**Issue by sbegh** [google/physical-web#827]
Hi, first of all, sorry for my english... ;-)

this is my problem, we are building a kind of social network based on proximity with a custom CMS we build to manage content.

So we have **ONE** unique URL landing page for all users , and we pass a **GET** parameter in order to display the content of the users, eg : https://MyDomainName.tld/index.php?UUID_USER=xxxxxx
And all URLS are shortened with Goo.gl

All users have differents and unique title, description and favicon.

But in the Physical Web App (official) the urls are grouped randomly...sometimes we have one url, sometimes two etc... But in the notification : all beacons are detected (eg : 6 beacons nearby, pull to see them) > but again, just 1 or 2 are displayed in the next screen...

We have made several testing :
- Shortening URL based on the real adresse : https://MyDomainName.tld/index.php?UUID_USER=xxxxxx : failed...

We have made a rule of rewritting : https://MyDomainName.tld/xxxxxx and shortned it : failed
idem with a suffix : https://MyDomainName.tld/xxxxxx.html : failed
 we change the tld (original is a .pw, we have tried with a .io : failed.
 we try with another domain name : failed...

in brief...all test failed...except in Physical Web detection from Google Chrome, we can see all ours beacons in the list...???

So we made a test with somes facebook pages  pages that we admin : 

https://facebook.com/NameOfPage1
https://facebook.com/NameOfPage2
https://facebook.com/NameOfPage3
...
And its working like a charm !... why ??

We don't understand the difference between our solution that not working and the facebook pages which are ALL displayed, not ours...

Do you have a clue ? 
thank in advance

**Comment by scottjenson** [comment]
Sorry, but I'm not sure I understand. I think what you are saying is:
1. All beacons are detected in the Physical Web App notification
2. But only a few are displayed in the PW app list view
3. However, all of the URLs *are* detected by Chrome

Is this correct? If so:
* Can you refresh the list page in the Physical Web app and see everything?
* If so, how often are your beacons broadcasting a URL packet? 
* The recommended rate is every 700ms
* Can you detect using Nearby on Android?
* Does it display everything in it's list view?

Keep in mind that we've evolved. We started off in the Physical Web app but that is only for developers. We moved to Chrome but that has recently changed to using Nearby on Android. What we care about the most is using Nearby (when on Android) but you haven't mentioned that at all.

Scott

**Comment by sbegh** [comment]
Hi, And thank you for the fast answer !
We did a big mistake...and the solution was under ours eyes... In fact our system can manage title, description and favicon, but in ours tests we left the same title for all ours beacons (yes...we are stupid :-) )... it causes random groups...
Everything is ok now ! 
Can I email you the details of what we do for you to give us your opinion ?
Thank you for all you did, you do and you'll do :-)
Laurent
