### ISSUE TITLE
Why do we need GPS in scanning of physical web?

### ISSUE THREAD

**Issue by kanodia** [google/physical-web#833]
Hello

I know the question is an old one, but I am still not able to figure out why do we need user to switch on GPS to enable physical web scanning through nearby API?

Why can't it be done just with the help of bluetooth?

**Comment by cco3** [comment]
It's not a technical capability issue, but a permissions issue.  A location provider must be on to do a location-sensitive ble scan.

**Comment by kanodia** [comment]
@cco3 : Why do we need GPS at all. The BLE scanning will anyway be location specific. If we just switch on B.L.E. and let it scan for beacons, it will scan for only the area where it can reach which will always be location specific

**Comment by scottjenson** [comment]
I'll repeat was @cco3 just said: GPS is not required and we're not asking for GPS. We're asking for the Location permission (which happens to include GPS). The way Android permissions works is that in asking for the Location permission you also happen to get GPS as well. 

As looking up a beacon could potentially give away your location, like GPS, we have to ask for that permission. As you surmise, we don't need or use GPS.
