### ISSUE TITLE
Chrome not responding to Eddystone URL

### ISSUE THREAD

**Issue by ian-4dit** [google/physical-web#837]
I am starting to do some R&D for my company on Eddystone URLs and Google Chrome.  I have configured a number of beacons from different manufacturers with HTTPS URLs.  While I can get these from a test app I built for the purpose, I am not getting any response from Chrome.

If I access chrome://physical-web I get the following response:

Status
Physical Web is ON

Prerequisites
Android SDK version: Compatible
Data connection: Connected
Location services: Enabled
Location app permissions: Granted
Physical Web privacy settings: On
Bluetooth: Enabled

Nearby web pages
No nearby web pages found

Does anyone have any idea why none of the beacons are showing up?

The only thing I can think is that the beacons are not registered with Google, is this a requirement for them to be visible?

Any help would be gratefully received.

Cheers

Ian

**Comment by adriancretu** [comment]
Did you enable Nearby (from Google Settings)? Chrome doesn't scan anymore, unless Play Services is not installed, I think.

Also, Nearby scans for beacons only when you turn on the screen (this should be made more obvious). Your app was probably subscribing in foreground mode?

**Comment by ian-4dit** [comment]
Thanks for the info, I've switched that on, just waiting for something to happen now.  

So does this mean that if the default for Nearby is off, then no one will see the beacon unless they have an app.  I thought the whole purpose of the Eddystone / Physical Web was that phones would pick up on beacon URLs without anything specific being enabled / installed?

**Comment by adriancretu** [comment]
I'm not sure what the default value is, maybe someone can tell us? As far as I know, the first time a URL beacon is seen you should see a "on-boarding" notification, are you sure you didn't just skip that and so Nearby was disabled? You can also try to add URLs to Eddystone UID beacons if you register them in the Beacon Dashboard and attach a website to them, and see if that works.

**Comment by scottjenson** [comment]
If the user has BT and Location on, they should get a notification automatically. Part of the issue with the Physical Web scanning is that we can potentially give away their location. This means we need these permissions (which most users have on but certainly not all)

This does mean that there are times you'll need to prompt users to either turn on location or bluetooth for this to work. We appreciate this isn't as easy as people would like but it is a one time activity. Once users do it, it's on for all other Physical Web experiences.

I'm closing this but feel free to reply if you have more questions.
