### ISSUE TITLE
Nearby notifications not displaying

### ISSUE THREAD

**Issue by adamrenner** [google/physical-web#839]
Broadcasting eddystones with nexus 5x. Listening with nexus 7. I can see beacon if I manually scan in nearby discoveries or PW App.I cannot receive passive notifications. When prompted if I wanted notifications, I enabled.

**Comment by scottjenson** [comment]
Sorry, it's really hard to give support on issues like this. We've also received this question dozens of times. I wish there was a way to do a sticky post. Here are the steps to diagose if you can't see beacons:
* See if you can the beacons with a scanner (e.g. nrf connect)
* See if you can see the beacons iwth the Physical Web app
* See if your beacon URLs pass our filter (verify.physical-web.org
* Make sure Nearby Discoveries is turned on in Settings
* Scanning occurs when the phone wakes up.
