### ISSUE TITLE
Raspberry Pi/NodeJS Listening for Beacons

### ISSUE THREAD

**Issue by derekshull** [google/physical-web#843]
Does anyone know of a library out there with raspberry pi/nodeJS that would allow it to listen for beacons to come within range and then "trigger" something else to happen?

**Comment by scottjenson** [comment]
There is already an existing [node scanner in the Eddystone repo](https://github.com/google/eddystone/tree/master/eddystone-url/implementations/nodejs). It shouldn't be hard to take that and just call it's scan function repeatedly, looking for a  specific URL.

**Comment by ukBaz** [comment]
@derekshull I think the library you are looking for is:
https://github.com/sandeepmistry/node-eddystone-beacon-scanner

The library even does an estimate at distance.
