### ISSUE TITLE
Nearby Notifications: not all notifications are displayed

### ISSUE THREAD

**Issue by kanodia** [google/physical-web#844]
Hello everyone

I have been working on physical web for long.

Recently, I did a pilot run among 3000 people where I used Eddystone beacons and nearby notifications.

We put 7 beacons with a common UUID, configured at a frequency 0f 500ms and a power of 3Dbm.

It was a 2 day pilot run and at some point of time, we were transmitting 10-15 nearby notifications.

What we observed was, whenever a new user switched on B.T. and GPS to receive notification for the first time, he could see only one notification(the last one uploaded)

I think it is an issue with beacon scanner?

What do you think?

**Comment by ferencbrachmann** [comment]
do you have any stats to share on engagement?

**Comment by kanodia** [comment]
@ferencbrachmann : What stats do you need?

**Comment by ferencbrachmann** [comment]
Hey,
I'd love to see how many people visited your beacon landing pages. We get engagement numbers between 1% and 60% (of persons present) depending on the type of use and brick&mortar signage.

**Comment by scottjenson** [comment]
"7 beacons with a common UUID" is confusing to me. I'm not sure if you were using a UID beacon or a URL beacon. I'm trying to understand both the number of beacons and the number of UIDs or URLs you were sending at the same time.

**Comment by kanodia** [comment]
Hi Scott

We had placed 7 beacons (Eddystone UUD) configured with same Namespace and Instance ID.The reason we did that was because the ground was big in size hence to cover the entire place, we placed multiple beacons.

Since all the beacons were transmitting same UUID, we used nearby notifications. We uploaded 15-20 notifications into the beacon.

What we observed was that the users were only seeing 1 notification in the nearby discoveries screen. Ideally they should have seen all the 15-20 notifications.

**Comment by kanodia** [comment]
@ferencbrachmann : We are publishing a detailed case study on our pilot run with stats and learnings. Currently we are compiling all the data and collecting feedback from the sellers.

One thing I got to know that we influenced 15-20% of the total sales that happened at the event.

I will post the link to the case study as we complete it

Thanks

**Comment by scottjenson** [comment]
Can I ask why you are using UID beacons and not URL beacons?

**Comment by kanodia** [comment]
@scottjenson : We wanted to broadcast 15-20 messages via beacons. If we would have used URL, then we would need to have put 20 * 7 = 140 beacons to broadcast 20 messages to every place in the venue.

Buy with UUID, w could achieve this using 7 beacons only. Hence, we chose to go with UUID

**Comment by scottjenson** [comment]
Nearby is an early product and is quickly maturing. V1 was tuned to find URLs with Eddystone-URL beacons and specific messages for devices using Eddystone-UID. We've found a few bugs when using multiple URLs per message and this will be fixed in a future release.

**Comment by kanodia** [comment]
Okay Scott.

So to understand, we are working to fix the scanning of both URL and UUID.
In future releases, nearby would be able to scan for any number of messages through UUID or the particular URL.

Right

Thanks

**Comment by scottjenson** [comment]
That is correct
