### ISSUE TITLE
Validator Inconsistencies: fetch failed

### ISSUE THREAD

**Issue by ferencbrachmann** [google/physical-web#845]
@beaufortfrancois 
We're using the PW validator at https://beaufortfrancois.github.io/sandbox/physical-web/url-validator/ and have discovered some inconsistent results. The URL in question is http://b3m.it/BEKEVfEm
Our client gets fetch failed, I get success now (got fetch failed all the time untill about 20 minutes ago). Some colleagues are getting fetch failed too. BTW the URL works fine when I broadcast it.

**Comment by ferencbrachmann** [comment]
We experience no issues as of today. This issue could have been related to the recent move from Nearby back to Chrome? 
Is the validator using the same production services as Nearby/Chrome?

**Comment by mmocny** [comment]
(Yes, the validator uses the same service as Nearby/Chrome does)

**Comment by ferencbrachmann** [comment]
@mmocny as recently as of today we somtimes still got the fetch failed error messages for URLs that later turn out to be perfectly valid.

**Comment by ferencbrachmann** [comment]
@mmocny we have a CMS for the physical web (https://beeem.co) you can try it out for yourself. It would be very unlikely that we could not serve out a page within 5s as our services are on Azure with Cloudflare used as a CDN.
