### ISSUE TITLE
Do tablets show any issues in scanning of physical web?

### ISSUE THREAD

**Issue by kanodia** [google/physical-web#846]
Hello

I have tested for physical web with latest and a lot of smartphones with the latest play services.

I have never tested the scanning of physical web in a tablet device?

Do tablets show any error in scanning, provided in is running on Android Kitkat, latest play services(means there is nearby discoveries available) and bluetooth version 4.0

Thanks

**Comment by ferencbrachmann** [comment]
We've experienced no issues specific to Android tablets.
