### ISSUE TITLE
Changing URL of Nearby Notification dynamically

### ISSUE THREAD

**Issue by Hardztr** [google/physical-web#847]
Hi,
I have registered an old iBeacon in the Google Beacon Dashboard and added a Nearby Notification to it in form of an URL. This seems to work as intended. However I would like to change the URL on the beacon throughout the day, so only clients that has been in contact with the beacon recently knows what URL it is pointing to at the moment. It works when I change the URL manually in the dashboard, but I want to create a service to change it automatically. Is there an API to the Google Beacon Dashboard so I can make changes in the beacon settings programmatically?

**Comment by angst7** [comment]
You can manage your attachments using the [Proximity Beacon API](https://developers.google.com/beacons/proximity/guides).

**Comment by scottjenson** [comment]
Sorry, but that isn't our project so we can't help you. As @angst7 points out, please direct your questions to the Proximity Beacon API.
