### ISSUE TITLE
Nearby Notifications is Temporarily Muted: Is it resolved?

### ISSUE THREAD

**Issue by kanodia** [google/physical-web#848]
In the nearby notification page, it says that nearby has been disabled for sometime.

But in my test runs, I can still see nearby notification.

Has it been resumed?

**Comment by ferencbrachmann** [comment]
I noticed a change in the Google Settings app. The notifications are now under the menu item labeld "nearby" instead of "nearby discoveries"

**Comment by YogeshDabade** [comment]
I think notification from Nearby still are still muted. But when we go to nearby in settings beacons are detected

**Comment by scottjenson** [comment]
Yes, Nearby is not *off*, the list still works, it's just the notifications that no longer fire for this short window of time.

**Comment by mmocny** [comment]
Also, some users may still have the older version of Nearby installed and still be getting Notifications.  (Sorry, I don't have access to any upgrade charts to know the timeline.)

**Comment by mubiesam** [comment]
Received a notification today, is it back?
![20161025225835](https://cloud.githubusercontent.com/assets/11897667/19691901/8845e3b8-9b08-11e6-9255-95da8fa39f52.jpg)

**Comment by mmocny** [comment]
That is Chrome firing Notifications.  You must have updated to Chrome m54 stable, which fires notifications again.

Once Nearby is working again, Chrome should stop firing notifications automatically.

Cheers.

**Comment by scottjenson** [comment]
Assume question answered? Closing but feel free to reopen
