### ISSUE TITLE
Where can I buy Eddystone beacons with large battery life, around 3-5 years?

### ISSUE THREAD

**Issue by kanodia** [google/physical-web#849]
Hello 

I have been working with beacons from radius networks. The quality of beacons is fine but their battery life is poor.

I am looking to work with beacons which can atleast run for 3 years on a single stretch and with full usage?

Which is the best beacon to work with

Thank You

**Comment by edstros** [comment]
[BKON Connect's](https://bkon.com/product/bkon-a1/) beacons have a 4-year estimated battery life with standard non-connectible Eddystone-URL settings. Uses two AAA batteries, which come included.

**Comment by scottjenson** [comment]
g.co/beacons has a link to "get Eddystone" There are >30 beacon makers there. I'd suggest you look for the more professional versions that ship with 4AA batteries. Those are rated for many years.

**Comment by kanodia** [comment]
Thank You Scott.

I will look at them

if you can also provide a name of few vendors who ship 4AA battery beacons
, that will be very helpful

**Comment by scottjenson** [comment]
I'm sorry, but I hope you understand that we can't recommend any beacon maker, it would make the others a bit grumpy ;-) Honestly, they have all been reasonable,  you can't really go wrong.

**Comment by kanodia** [comment]
OK I understand Scott.

So when deciding beacon , I should look at those where the battery is 4 *
AA , right?

Also, in your experience, what is the max in years a beacon has potential
to run

**Comment by scottjenson** [comment]
I would think 4AAs should get ~5 years. Keep in mind that the quality of the battery is an issue as well as cheap batteries will naturally degrade in 5 years just sitting there. Newer beacons using the nrf52 chip (vs the older nrf51) will also las much longer on the same battery as the newer chipset is more efficient. I don't know which beacons use which chip. I'm just saying that in a year, you'll likely be able to buy beacons that will last much longer. The hardware is changing rapidly.

**Comment by scottjenson** [comment]
Sorry, I don't know. There are just too many variables. It would be foolish for me to promise something. For example, it's not just the number of batteries but the efficiency of the antenna, the processor, the quality/capacity of the batteries etc. In general, though, 2AAs should last a very long time (likely 2 years) and 4AA obviously longer.
