### ISSUE TITLE
Beacon Notifications in the mobile version of Chrome

### ISSUE THREAD

**Issue by mcthedog** [google/physical-web#850]
How can I get Physical Webs list of EddyStone-URL broadcasts in it own screen?

I need a more seamless viewing of the broadcast URL's?

**Comment by scottjenson** [comment]
Not sure I understand. When you select the Chrome notification, it takes you to a list of URLs. Do you want to see the list without going through the notification?

**Comment by mcthedog** [comment]
Hi Scott,

Thanks for the swift reply.

I suppose I was thinking of a push notification or similar. I'm new to Beacons etc. And although I've experimented with iOS Physical Web app and the equivslent Google Play Store variant of the Physicsl app but I wanted something where an app DOESN'T RUN or similar to a push notification. 

Just wondered what my current "seemless" options are?

Mark

**Comment by scottjenson** [comment]
For Android, it's built into the OS, if you have BT turned on (and Location) You'll get a *silent* push notification automatically. I assume that's what you're talking about?

For iOS, the only option for most consumers is to have Chrome installed. You have to turn on the Chrome widget (which is much easier with the upcoming force-touch option in Chrome) That allows you to simply 'swipe left' and see what is nearby.

**Comment by mcthedog** [comment]
Thanks Scott.

I managed to get the iOS version of the Physical App working pretty good. 

Android - however - is proving quirky. Chrome (Beta) is irksome so I wonder can you send me a HOW TO link for getting the Android Physical Web app even to "see" my beacon(s).

**Comment by scottjenson** [comment]
It's important to remember that we initially added the Physical Web to Chrome but then moved the scanning to Android Nearby. There is a bug right now preventing Android Notifications from firing but that should be fixed in ~6 weeks. As a backup Chrome is filling in with it's notifications but we're trying to get back to using the Android Notifications as fast as we can.

Once that's turned back on, you should just get the notification automatically if you have BT and location turned on.

**Comment by mcthedog** [comment]
Thanks Scott. Appreciate the candour. Happy to close the thread and continue my testing/creating empires! Kind regards

**Comment by mcthedog** [comment]
Oh I see and I thank Scott. Is there a way to acquire (via api or app) the silent Android push?  I presume the various Android apps intercept the silent push before they acquire then display the Eddystone url right?

Sounds like Chrome widgets are already available but a new release is imminent.

How do i enable the Chrome TODAY  widget RIGHT NOW?

That does make it somewhat clearer.



 
---*
Mark C
www.En1gmaEngine.co.uk
www.twitter.com/En1gmaEngine
Skype: Mark.Chapp

**Comment by scottjenson** [comment]
The Chrome widget only exists for iOS. There is no way to force the notification on Android. But you can force bringing up the Nearby list view. There is a menu item that lets you add to homescreen. This isn't for everyone but it does help get you to the list any time you'd like

**Comment by mcthedog** [comment]
Hi Scott,

Thanks for this. I thought the Nearby app was a tad poorly at the moment regarding beacon url processing isn't it?

 
---*
Mark C
www.En1gmaEngine.co.uk
www.twitter.com/En1gmaEngine
Skype: Mark.Chapp

**Comment by mcthedog** [comment]
Ok so I need the Nearby list in the Chrome widget do I?

Thanks Scott, I will experiment with the Chrome Widgets Nearby list and my beacons transmitting iBeacon frames.

Kind regards

 
---*
Mark C
www.En1gmaEngine.co.uk
www.twitter.com/En1gmaEngine
Skype: Mark.Chapp

**Comment by mcthedog** [comment]
Hi Scott and thank you.

I presume that now I have some beacons that I can register each UUID with Google Proximity AND Places API and view them on my Google account can I?

I have beacons from Kontakt.io, who I believe are one of your development partners on the Beacons programme?

Would it now be possible to register the uuids onto Google and maybe use a public-api key to access all beacons/display on map?

Kind regards.
 
---*
Mark C
www.En1gmaEngine.co.uk
www.twitter.com/En1gmaEngine
Skype: Mark.Chapp

**Comment by scottjenson** [comment]
You *can* do that. It's a bit faster to just use the URL frame type instead of UID though. That is something you just put into the beacon and go.
