### ISSUE TITLE
How can rotate token on the beacon url  ?

### ISSUE THREAD

**Issue by reno184** [google/physical-web#851]
In Physical web FAQ your are talking  about a rotating token on the beacon would constantly alter the URL.
Can someone explain to me how it's work ? can I use that with url shortener in my code ?

thank you very much

**Comment by scottjenson** [comment]
I rotating URL requires a custom beacon image. Nearly all beacons today just broadcast a fixed URL.

**Comment by reno184** [comment]
Ok thank you and where can we find doc or manufacturer about that ?

many thanks !

**Comment by adriancretu** [comment]
You can use [uriio.com](https://uriio.com) to create "rotating" (actually random) beacon URLs that redirect to your site. But to actually update an Eddystone beacon every time the URL "rotates", my guess is that you either:
a) need some support from the beacon manufacturer,
and/or
b) leave the beacon always connectable and use Eddystone-GATT to reconfigure it from a nearby control point.

For offline "URL rotations" you would need to come up with your own strategy and beacon firmware, similar to how EID works.

**Comment by scottjenson** [comment]
I agree with @adriancretu 's answer wrt doing everything through a server. If you'd like to have the beacon itself rotate the value, there are no beacon makers I know of that do that.

**Comment by reno184** [comment]
If you check those examples on physical [website](https://google.github.io/physical-web/examples) :

Restaurant buzzer, parking meter....

If I well understand, once someone get the url of the parking, or the restaurant and move away, he can continue to play with those services even if he not in the region of the beacon any more?

I'm looking hard to find out a solution to avoid this problem 

google nearby notification
evothings with cordova beacons plugins
pyh.net []( https://www.phy.net)
web-bluetooth...

but I still don't have find the good way,

I appreciate, if someone can help me...many thanks

**Comment by scottjenson** [comment]
Yes, WebBluetooth is the best way to solve this issue as you can connect to the beacon (or even just detect it) and only proceed if visible. 

If you are working on much bigger scale, like a concert, you can use the location API to make sure you're nearby. That's clearly not perfect but it's quick and easy and effective.

**Comment by reno184** [comment]
Many many thanks for your answer ;)

Finally I won't touch url, no rotation token any more...

Can I use webBluetooth to get on demande EID emit from my beacon ? then send it (EID) to google proximity api, and check if match ?

if yes,

do you know, where can I find a demo, or example nearly similar, to show me how to do that ?

Thanks very much, I appreciate your help ! Have a good day ;)

**Comment by scottjenson** [comment]
At this time no. You can only open the web page from the URL coming from the beacon.

**Comment by reno184** [comment]
to be more clear, my webpage will be in free access through URL, no worry about  that

But I won't permit any change in my database with firebase auth and rules.

In order to give credential to token to my user, I just need to know if this one is close to my beacon when is calling my webpage.

And in my backend, I can reset this token by click, after that, the user must to move again to beacon to get a new token.

 Webbluetooth seems to read/write any gatt informations, it's no possible to get EID to generate my own credential token ?

**Comment by ferencbrachmann** [comment]
The approach we will take with our Beeem (https://beeem.co) platform for this problem is to geofence the rendering of the page to a specific store location. We'll have a feature update for this in a few months time.

**Comment by scottjenson** [comment]
No, the EID doesn't work that way. Eddystone-URL beacons broadcast just a URL. You can make your own version of a beacon that rotates a token (as some beacon makers already do, BKON is an example of this) or you can use Geo Locoation (as Beeem will apparently soon do).

We are close to releasing an Eddystone beacon image written in mbed and open source. It is fully compliant with all 4 frame types and should run on a variety of mbed capable beacons. If you feel energetic, you could use that to roll you own beacon type.

EID broadcasts a UUID that cryptographically rotates, that means you can't know how it's gong to rotate (or it would be useless) Even if you attached a URL to that EID using the Android Beacon API, you can't connect to that beacon as it doesn't follow the format needed by WebBluetooth (that requires a NAME parameter for you to select it at the moment)

This restriction with WebBluetooth may change in the future, it's just not possible right now.

**Comment by scottjenson** [comment]
Unless you have a follow up question, I'll close this for now
