### ISSUE TITLE
URLs come back after swiping away

### ISSUE THREAD

**Issue by cco3** [google/physical-web#860]
Swipe away a URL and scroll around without refreshing.  The link comes back.  Not sure what's going on here.  We also want to consider a different interaction for starring blocking (i.e., long press for both....might be simpler to maintain and easier to use.)

**Comment by chrislazaris** [comment]
I have also experienced a similar abnormal behavior recently: while conducting a field experiment in real retail settings, we noticed that URLs are detected normally but do not disappear when out of proximity, even with swipe down and refresh. This behavior occurs both in nearby and the physical web app, but not within chrome scanning and other physical web browsers (e.g. phy.net). We tested with several smartphones which worked fine previously. Is it a bug or a feature?
