### ISSUE TITLE
Bug in Chrome for iOS widget with iOS 10

### ISSUE THREAD

**Issue by ferencbrachmann** [google/physical-web#865]
@scottjenson 
We had several issues with the onboarding message in the Chrome for iOS widget with iOS 10 or 10.1 (we're not sure).
If the physical web has not been enabled on yet, the onboarding message fails to render correctly and the OK button does not apear for the users only after taping on "show more" / "show less" several times.

**Comment by scottjenson** [comment]
Looking into it...

**Comment by scottjenson** [comment]
We've filed a bug to get more info. Hopefully know more tomorrow.

**Comment by scottjenson** [comment]
Found the problem, testing a solution on Chrome Canary on Monday. Thanks for pointing this out!

**Comment by ferencbrachmann** [comment]
Hi, great, isn't Canary exclusive to Mac OS, Windows and Android?

**Comment by scottjenson** [comment]
Of course, sorry. Just letting you know we found the problem and it's in the pipeline...

**Comment by scottjenson** [comment]
OK, just confirmed that the bug is fixed but it missed Chrome 55, will hopefully go into 56

**Comment by scottjenson** [comment]
My mistake, the fix is completed but it just missed the 'every-6-week' window of Chrome releases. No worries, assuming no issues with final testing, it'll just be in the next release, 57.
