### ISSUE TITLE
Nearby icon is not displayed in the notification bar when in proximity to Physical Web beacon

### ISSUE THREAD

**Issue by vkercan** [google/physical-web#866]
Nearby icon is not displayed in the notification bar when in proximity to Physical Web beacon. Debug information below:
- Phone: LG Nexus 5
- OS: Android 6.0.1
- Google Play services: 10.0.84
- URL: https://www.reddit.com/
- Video of anomaly: https://drive.google.com/file/d/0B_0BgSEsxNOcUy1UcG8wc2JnSEE/view

![about phone](https://cloud.githubusercontent.com/assets/24320020/20840693/6270a6a2-b8b1-11e6-8c93-c37873863b14.png)
![google play services](https://cloud.githubusercontent.com/assets/24320020/20840703/6c01f338-b8b1-11e6-8e72-48a9b686c598.png)

**Comment by scottjenson** [comment]
Thanks for writing this up. Very helpful. I want to make sure we're clear on the issue. The Nearby icon will 'light up' but only within the quick settings tray. It isn't supposed to show up in the collapsed notifications header at the top of the screen. Is that what you're expecting?

Scott

**Comment by oninross** [comment]
Hi @vkercan,

Are you talking about the Notification Icon in the drawer?  From my experience, the icon in the drawer or in the bar will not show in Nexus 5.  Probably Google is not supporting that anymore in Nexus 5.  @scottjenson can help us verify for us. :)  If I am not mistaken,  icons will only light up when you pull down the drawer and if you are nearby a beacon

**Comment by vkercan** [comment]
Hey Scott, Nino

What I am expecting is a Nearby icon in the notification bar as seen in our video which was taken before the last major update:

https://drive.google.com/open?id=0B_0BgSEsxNOcbzZCR1ZyY3ROdTA

See also screenshot and an icon on the top left corner. This icon used to light whenever the Physics Web beacon was nearby, but not anymore.

[Image]

Both of you are mentioning that a Nearby icon should light eventually somewhere. In my case the icon does not show up anywhere. Only notification appears when you slide down. But that is it.

In shot, is the Nearby icon still supported as in my case above? If not, what kind of experience is expected? Can you post a short video or screen where this is demonstrated?

Thank you and best regards, Vojko.
_____________________________

**Comment by ajitam** [comment]
I can also confirm the same behaviour (no icon in top left corner in any case) for two different phones:

* OnePlus X, 6.0.1 (OxygenOS 3.1.4), Google play services 10.0.84
* Motorola Moto G4 Plus, 6.0.1, Google play services 10.0.84

**Comment by scottjenson** [comment]
Sorry I didn't make this clear before but the icon showing up in the top left corner was a bug categorizing the notification as a high priority notification. That was fixed the last version released. This means that most notifications are MIN priority and only show up if the user pulls down to view it.

I can appreciate how this feels like a bug as it is a change, but as I tried to explain above, we're trying to balance discover with user frustration. We don't want this to feel spammy.

**Comment by scottjenson** [comment]
Closing but feel free to reopen/comment if needed

**Comment by RichyT** [comment]
I had this working but now although my beacon shows up if you open the nearby panel, it does not appear in the pull-down tray.

**Comment by dipbiswas** [comment]
Hi @RichyT,

Were you able find a solution to your issue? I am facing the same behavior. These notifications are showing up in the nearby app but not in the pulldown notification area.

Thanks
Dip

**Comment by RichyT** [comment]
No. I think it may have shown you one time but I'm not sure. It seems google keeps moving the goalposts on us. I am glad I am not heavily invested in this technology and pity anyone who made this part of their portfolio.


Sent from my T-Mobile 4G LTE Device

-------- Original message --------
