### ISSUE TITLE
Can't Push Certain Pages to Physical Web Beacon

### ISSUE THREAD

**Issue by montelco** [google/physical-web#873]
My issue kind of sounds similar to #852 except that I am able to push out our content to our hardware. So for instance, I can push out https://example.com or https://example.com/about. However, our content that we want pushed to the beacons is created by each user and their content lives at a short URL. So they can make content and push it out. 

Eg: https://example.com/h8wnAii or https://example.com/jHf7slo9

When any of those URLs are sent, they do not display on Nearby or in the Physical Web application. So I believe as far as I can tell, it's either something with my template view that the user's content renders on or it's something else. Please note this worked up until about five days ago.

**Comment by cco3** [comment]
Hello!
Have you tried testing your URLs at <http://verify.physical-web.org>?

**Comment by montelco** [comment]
I just attempted to verify the URL with this response: 

Reason Deadline Exceeded (Fetch timeout).

I'm not sure why this would timeout but my homepage, etc (all running on the same hardware and SSL cert) are fine.

**Comment by cco3** [comment]
+ @oahziur 

I'm not sure if the service distinguishes between actual timeouts and redirect chains that are too long...that might be something else for you to measure.

**Comment by montelco** [comment]
Okay, looking at things now it claims that there are too many redirects even though the template is almost identical to the main site. The only difference is that it loads in another CDN js file and it has the data that comes from our database.

**Comment by scottjenson** [comment]
I can verify more deeply on my side but I think our PWS stops chasing
redirects after 5. So there is a chance that your CDN is bouncing you
around a bit more than you bargained for. This is bad, not just for
the Physical Web but your site in general. There might be  simple
setting/configuration that will speed this up (on multiple fronts)

What you're doing by helping users easily create their own content portal
is something we'd like to support, if you can't find anything easy to fix
with your CDN, please get back to us.

Scott

**Comment by montelco** [comment]
It was working until about a day ago and I don't believe anything to have changed on my end. I'm moving some of our resources to being self-hosted rather than on a CDN if that should have any bearing. Was there a change in the metric used for redirect counting recently?

**Comment by montelco** [comment]
I'm just not sure what changed in the past few days to cause this issue. Our entire platform uses the Physical Web to power content delivery for the masses, so any ideas are greatly appreciated.

**Comment by montelco** [comment]
@scottjenson The issue ended up being how we track our visits on our side. The header was set to a zero refresh if a cookie wasn't set to force it to set and submit. Changed up our code to play nicely and not do that.
