### ISSUE TITLE
Restricting showing notification to an user

### ISSUE THREAD

**Issue by aramkris** [google/physical-web#875]
Hi, I am trying to find a way to restrict the notifications shown to a single user. For example, if I have a beacon broadcasting a URL (https://abc.com) and we use the Nearby service to get it to display on the users smartphone, then can I ensure that I show the notification only once to an user every day even if the user walks in and out of the range of beacon a lot more.

Context: We are trying to use beacons to drive some promotional content to users who walk into a shop inside a mall. We want to ensure that an user who might visit the shop multiple times doesn't see the notification every time. 

- Currently, we intend to switch off the URL every 30 mins in an hour just to ensure that we limit the notifications shown. Not an ideal way to do it, but we want to ensure that people don't get notification if they visit 3-4 times. So, we are taking a chance here.

**Comment by ferencbrachmann** [comment]
@aramkris We're working a completly different approach for the same thing. Instead of trying to catch limiting the notifications (you'll have a VERY hard time doing that as all scanning is annonymus). 
Notifications will only be MIN priority so not bothering the user much. 

Our approach in Beeem (https://beeem.co) is to create rules for how many times a particular content piece is shown on a page.

**Comment by aramkris** [comment]
I understand about using "MIN" priority, but what I am trying is to avoid sending it to the same user. Most probably this would need some change in the way Android (or Chrome) scans for nearby/physical web pages as the server should not maintain history of where a page has been served. 

"Create rules for how many times a particular content piece is shown on a page" -> You use a Progressive Web App to determine this or is it determined by the server itself.

**Comment by scottjenson** [comment]
At this point, we've tried to keep the notification story simple: if you are in range, you see it. We are trying to not have client specific tweaks for a specific Physical Web scanner. What I mean by this is that we very much want there to be >1 Physical Web scanning clients out there. We could give you a solution to our client but then it wouldn't work for anyone else.

Of course, this isn't really answering your question, I'm just letting you know our general thinking. Also, it seems to be a bit of a slippery slope: having each client somehow track user state.

As you both seem to be trying to make some type of 'offer' be less obtrusive, I should let you know that in our user testing, any type of offer through notifications was very unwanted.  People just don't want to get coupons as a top level item. Even if we were to come up with a solution, they would still be dismissed/not used. Of course, if you're offering a store map, etc and there is an offer on that page, that's different, it's a secondary issue.

We've discussed in previous issues that we are working on 'downranking' any notification that is dismissed too often. We've seen notifications with offers have a nearly 100% failure rate so would likely be downranked very quickly.

**Comment by craigahunter** [comment]
Hi Scott in respect to the above, if a landing page from an Eddystone beacon had an offer displayed as the main meta tag on the physical web with further links to the full website would this also be downranked as you suggest above?  I'm not a programmer or anything but just trying to understand more about the uses for marketing business.  I would like to provide businesses with hardware and a landing page first which then gives them the option to progress to mobile website etc.  Thanks for your time.

**Comment by craigahunter** [comment]
Just to add the offer may be the main header and the business added as a description on the landing page with other elements such as call, email, maps or visit website etc.

**Comment by scottjenson** [comment]
There isn't any very technical involved: if users mute your notification it will start getting down-ranked, to the point that it will no longer even generate a notification. We are just measuring users intent and if the crowd is actively voting against you, that's a strong sign. 

The notification takes the Title/Description that comes from your web page. We'll just show what your web page says so you are in complete control. I will let you know that any notification that says "Great deals!" or "Discount" or "Sale!" has been performing very very poorly in our user trials so far.

Scott

**Comment by craigahunter** [comment]
Ok thank you I understand.  Would the Down ranking then apply to the whole URL/website or just the particular landing page?  So if the title/description changed regularly to would still result in no notification being shown or would the new changes count as a new notification?  Sorry to take your time on the matter. Thanks craig

**Comment by scottjenson** [comment]
Interesting, I don't really know, let me look into it. This is a something that we're constantly working on so even if I did know, it might change (this is one of the reasons why we don't want to tie the URL beacons to specific scanners)

**Comment by adriancretu** [comment]
It would be helpful to know at what level the down-ranking is performed. What happens if a website allows user-generated content (landing pages on the same domain), would legitimate useful URLs be down-ranked because other ones are posting marketing spam? And how about when the URL changes frequently? How would the down-ranking work if the content stays the same but the URL changes? In my opinion, the down-ranking should be based on the content, not on its location.

**Comment by scottjenson** [comment]
It's based on it's performance. If enough people mute/dismiss it, it will be downranked. Clearly we have to be careful here and not do it too easily. We're unfortunately noticing a few depolyers that are just trying to push spammy notifications for coupons in mall locations and we have to find a solution to make sure users frustration is noted and taken into account.

**Comment by craigahunter** [comment]
In respect of the above can I give you a scenario...Lets say a chain of hotels had beacons all over the country (at its hotels) broadcasting its website domain using the physical web for marketing purposes.  Maybe 500 different locations.  If this was dismissed quite a bit by users in the different areas can I assume that the url for the hotel chain would no longer be shown at all (even if the locations were different).  For such a big roll out it could prevent problems for large organisations if its down ranks based on comparatively low mute/dismissal rates.  If it was dismissed say 100 times in a week it would effectively render all the other hotel chain beacons as being useless.  Assuming mute/dismissal down ranking purely URL based

**Comment by ferencbrachmann** [comment]
I think the concept of the physical web is very clear on this: a URL for every (individual) thing. Forcing the logic of the web as we know it on to the physical web will only create problems.

**Comment by aramkris** [comment]
I am closing this. This was more of a question rather than an issue (possibly an enhancement).
