### ISSUE TITLE
Omnibox issues in Chrome for iOS 55

### ISSUE THREAD

**Issue by ferencbrachmann** [google/physical-web#878]
Hey, I have a few screenshots that outline the issue: validated beacon URLs showing up in the widget (and on an Android device as well) but not in the omnibox.
![2017-01-12 11 30 57](https://cloud.githubusercontent.com/assets/20400452/21886882/ed6f754a-d8bd-11e6-80f8-2e476055d608.png)
![2017-01-12 11 31 05](https://cloud.githubusercontent.com/assets/20400452/21886881/ed6de55e-d8bd-11e6-9f9a-6f2674cb468a.png)
![2017-01-12 11 31 16](https://cloud.githubusercontent.com/assets/20400452/21886883/ed6fdfda-d8bd-11e6-9d8d-914115687f59.png)
![2017-01-12 10 31 28](https://cloud.githubusercontent.com/assets/20400452/21886974/450d68de-d8be-11e6-913f-7ae3719bf646.png)

**Comment by ferencbrachmann** [comment]
![2017-01-12 12 00 27](https://cloud.githubusercontent.com/assets/20400452/21887090/cd87d6c2-d8be-11e6-812d-eb10981880e2.png)

**Comment by cco3** [comment]
Hi!

**Comment by scottjenson** [comment]
OK, so I have to ask a couple of (obvious) questions, sorry
1) Did you restart Chrome?
2) Do you have "Location" turned on? (You can see this in Settings>Chrome>Privacy

Chrome asks when you first boot Chrome to use location. Most people say yes but if you've said no, we respect that you don't want to give up your location so don't scan.

**Comment by ferencbrachmann** [comment]
Issue found: even though I have the flags turned on there seems to be a PW setting turned off for  some reason. But can not change the settings as the screen becomes dead after I tap on "physical web".
Could this have something to do with the fact that this is a WiFi (only) iPad? (no GPS module)

![2017-01-12 21 47 27](https://cloud.githubusercontent.com/assets/20400452/21907857/a9784a3e-d911-11e6-8e38-684603365ebe.png)

**Comment by scottjenson** [comment]
Location isn't about only GPS it's about implied location. As a URL can be coded, it could give away your location, which is why we have to respect the location flag. I'll ask @nondebug to comment on what may be happening on the crash

**Comment by nondebug** [comment]
Hi Ferenc, I couldn't repro the crash (using an iPhone 6s) but there are some known UI bugs in the Physical Web preferences page in Chrome 55 that could be causing a crash on some devices. Which iPad model are you using?

I think this particular bug is fixed in Chrome 56. If you get a chance, could you sign up for the [Chrome Beta FlightTest](https://www.google.com/chrome/browser/beta.html) and see if you can access the prefs page?

**Comment by ferencbrachmann** [comment]
@nondebug iPad mini 2

**Comment by ferencbrachmann** [comment]
@scottjenson @nondebug The issues with the settings UI are all gone in Chrome 65 Beta but the beacons don't show up in the OmniBox as they do on the 4 iPhones I could test. All good inside the widget by the way so I'm certain something is wrong here.

**Comment by nondebug** [comment]
Thanks! Could you also check chrome://physical-web?

**Comment by ferencbrachmann** [comment]
The issue went away after visiting chrome://physical-web ...it displayed the beacon in question BTW
