### ISSUE TITLE
Physical URL showing on Nearby app but never creates a silent notification

### ISSUE THREAD

**Issue by diazdeteran** [google/physical-web#898]
I'm constantly broadcasting a physical URL at home to interact with a few IoT devices. About a few months ago I realized that the silent notification stopped showing. The only way to see this URL is by going directly into Nearby through settings or Chrome (Android version 7.1.1). I validated the URL (https://bienvenido-welcome.appspot.com/) and it returned "Success". The notification has not been muted.

**Comment by mmocny** [comment]
May be working as expected.  Notifications start optimistic but adjust according to usage patterns.  If your content is not proving consistently valuable to the public, it will stop showing as often.

For your use case, when you know the IoT devices are at home, hopefully opening the nearby app to find the links is no more tedious than opening your notification drawer.

In other words, Notifications are meant bring attention to great content, not to be a permanently dependable way to access all content.

Hopefully this makes sense!

**Comment by diazdeteran** [comment]
Good to know. Thanks!

**Comment by oninross** [comment]
the link to one of my beacons is actually to my personal website.  So that is not public worthy?  How is it decided that the content is not public worthy?
