### ISSUE TITLE
Omnibox Physical Web URLs in Chrome 57 on iOS

### ISSUE THREAD

**Issue by torbjornvatn** [google/physical-web#899]
I'm having the same issues as mentioned in #878, I can see two URLs when I go to `chrome://physical-web` but they won't show up in the omnibox. 

I'm on version `57.0.2987.100` and Physical Web is on/enabled in both the settings and under `chrome://flags`.
I've haven't gotten access to the beta version yet (have applied, though), so I haven't tested if it works there.

**Comment by torbjornvatn** [comment]
![img_1203](https://cloud.githubusercontent.com/assets/4453/23987463/094496ea-0a2a-11e7-9c4c-48eafb4a1414.PNG)
![img_1204](https://cloud.githubusercontent.com/assets/4453/23987464/0a5920e6-0a2a-11e7-8875-69219aa114c9.PNG)

**Comment by torbjornvatn** [comment]
And did work a couple of weeks ago.

![ezgif com-resize](https://cloud.githubusercontent.com/assets/4453/23988140/3f7d794a-0a2d-11e7-8805-218c93c6a2b8.gif)

**Comment by torbjornvatn** [comment]
And I've tried with my Android phone as well, but no luck there either

**Comment by nondebug** [comment]
Sorry for the frustration!  Omnibox integration hasn't launched yet in
Chrome Stable.  It was previously available on iOS by toggling
chrome://flags#ios-physical-web but as you discovered that switch no longer
enables the omnibox integration.

On Android, use Chrome Dev or Chrome Beta.  On Dev the feature is enabled
for 100% of logged-in users.  Please let us know if you have trouble
enabling it.

On iOS, sign up for Chrome Beta via TestFlight. It's enabled for ~90% of
logged-in users on Beta. You shouldn't need to wait long for approval, did
you check your spam folder?

Omnibox integration will start rolling out on Chrome Stable for both
Android and iOS sometime in the next few weeks and will likely take a few
more weeks to reach 100%.

**Comment by torbjornvatn** [comment]
I got access to the beta in Testflight yesterday and now it's working. Thanks
