### ISSUE TITLE
Physical web support not working on Android Chromium from source code

### ISSUE THREAD

**Issue by tvaleev** [google/physical-web#910]
I built Chromium for Android from open source and tried to see my beacon on chrome://physical-web but there are no results. At the same time on the same device in Chrome from Google play store it works good. 
Do somebody know why its happened?

**Comment by mmocny** [comment]
Discussed on [Chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=724136)

"PW Scanning only works on official builds of Chrome.  We may be able to get a version working in Chromium some day (only a few pieces need swapping out), but this is not available today."
