### ISSUE TITLE
Adding Physical-Web URLS?

### ISSUE THREAD

**Issue by thatcampbellkid** [google/physical-web#919]
Hi All!

I'm rather new to this, but have been playing with urls on and Nearby for a little now. I know only HTTPS addresses can be used, and that they will only work if they are successful in the url validator, but how can we add new urls to the project?

I have submitted urls to google, and have made sure that they are indexed, but cannot find how to validate them through the physical web project. Is there a process to submit a new url?

Thanks!

**Comment by mmocny** [comment]
There is no concept for "adding" a new URL.

You broadcast URLs using a Bluetooth beacon, and when a device detects that URL, it will validate through PWS.

If you have already validated your URL, then all that is left is to broadcast it from a beacon.

(The only time you may want to add a URL is if you are using a registered UID beacon, and want to add a URL attachment to it using the Beacon Dashboard.  This is similar, but not the same as Physical Web via Eddystone-URL, though)

**Comment by thatcampbellkid** [comment]
Hi @mmocny

Thanks for your response! I'm clear on the mechanics of eddystone and nearby, but I guess my question is more on how to add an https url to the PWS? 

For example:
Https://foo.com/ might work fine, but Https://bar.com/ might not work... What process would I have to look into to add Https://bar.com?

Hopefully that clarifies better. I'm not sure this is where I should be looking, but I was hoping someone might know, or what determines which addresses are included in the PWS?
