### ISSUE TITLE
Nearby notifications dead?

### ISSUE THREAD

**Issue by ferencbrachmann** [google/physical-web#922]
Hey, currently we can not get Nearby notifications on Android on either of our devices even though they show up in Google Settings / Nearby. Does anyone experience the same thing?

**Comment by itsMattShull** [comment]
@ferencbrachmann are you able to see the notifications now?  If so, can you share how you fixed the issue?  Thanks.

**Comment by ferencbrachmann** [comment]
@derekshull Yes, I've closed this issue. It seems that the URLs on the few beacons I had with me 24/7 did not trigger notifications (but showed up in Google Settings/Nearby) on several devices. Even though they did so for months. Probably there is some change in how Nearby fires notifications.
Doing a new page/beacon from scratch verified that nearby notifications do show up. 

Are you experiencing issues too?

**Comment by cryptofy** [comment]
hello guys anyone knows where I can get an existing solution for nearby notification to implement on my server? based on google eddystone url format.

I urgently need a developer who already have the solution. I want to integrate with an  MLM/affiliate software so as to make it platform for proximity marketing. 

my skype is: connect2danny

Thanks.

**Comment by ferencbrachmann** [comment]
Check out Beeem at https://beeem.co
