### ISSUE TITLE
Validating URLs through an API?

### ISSUE THREAD

**Issue by divye01** [google/physical-web#923]
Hey, I have been trying to find out a way to validate HTTPS URLs by an API call. However, I am unable to find the API you guys are using to validate the URL. Looks like the api extension looks something like this: 

`https://physicalweb.googleapis.com/v1alpha1/urls:resolve?key=API_KEY`

The Physical Web API is not available in Google's dashboard currently?

**Comment by mmocny** [comment]
Sorry, this API is not publically available.  The PWS is just a tool some Google apps use, it is not a part of the Physical Web ecosystem.  If you just want to verify a URL manually you can use verify.physical-web.org.
