### ISSUE TITLE
Raspberry Pi 3 as Eddystone Beacon

### ISSUE THREAD

**Issue by jonathanrjpereira** [google/physical-web#929]
Can I configure the Raspberry Pi 3 as a Bluetooth Eddystone beacon which would broadcast a URL?
Are there any good resources for this?

**Comment by dermike** [comment]
@jonathanrjpereira If you install node on it you can use: https://github.com/don/node-eddystone-beacon

**Comment by jonathanrjpereira** [comment]
What about reading/scanning Beacons on the RasPi?

**Comment by dermike** [comment]
@jonathanrjpereira Then I have this shameless plug https://github.com/dermike/physical-web-scan

**Comment by jonathanrjpereira** [comment]
This is awesome. Thanks a lot

**Comment by jonathanrjpereira** [comment]
If you have any, Please share any additional resources you have for Eddystone beacons on the Raspberry Pi

**Comment by jonathanrjpereira** [comment]
Any resources for the RasPi 3 in Python?

**Comment by dermike** [comment]
@jonathanrjpereira https://github.com/google/eddystone/blob/master/eddystone-url/implementations/PyBeacon/README.md

**Comment by ukBaz** [comment]
Looking at PyBeacon it uses the command line tools of "hcitool" and "hcidump" which are fine short term however those tools have been deprecated in newer versions of BlueZ. Those newer versions will make their way on to the Raspberry Pi eventually.
More background on this issue at:
https://www.spinics.net/lists/linux-bluetooth/msg70489.html

For my own use I have used the BlueZ DBus API although that does require the bluetoothd to be run with the "-experirmental" flag for advertising/creating a beacon.
Here is my example:
https://github.com/ukBaz/python-bluezero/blob/master/examples/eddystone-url-beacon.py

To scan for beacons using Python then the aioblescan library looks very good:
https://github.com/frawau/aioblescan

More generally I have been trying to keep track of libraries I find that use Python and run on Raspberry Pi for BLE. The results are at:
https://github.com/ukBaz/python-bluezero/wiki
Please feel free to correct any errors or omissions.
