### ISSUE TITLE
My 2 years of experience with physical web

### ISSUE THREAD

**Issue by kanodia** [google/physical-web#932]
Hello

My name is Abhishek Kanodia, from India.

I have been following physical web since July 2015. Like a lot of people here, I was also a big believer of this technology. Hence, I spent nearly 2 years of all my time and effort promoting it and building applications and use cases around it.

I launched multiple pilot runs on it through physical web on chrome ios, physical web inside chrome android, and nearby notifications. The range of pilot runs covered providing exclusive deals at events, retail stores to tracking assets in a FMCG supply chain.

And of course, I had thought and ideated about a lot more possible use cases regarding physical web

During my 2 years, I had spoken to 10000+ people about this technology, given demo and interacted with users.

But, after all my efforts, and failing multiple times on this technology, I sort of lost my belief on it.

The technology no doubt is charming and fascinating, more so because of its app less nature, but to be honest, this technology can only work when people switch on bluetooth and know what is it. We are easily talking at-least 4-5 years in future.

Expecting people to switch on bluetooth and then using physical web is not going to happen on its own. There needs to be a complete ecosystem built like wifi, where people know what is physical web, just like wifi.

Hence, to conclude, the odds against it are very high, especially in the next 4-5 years

THanks
Regards

PS: If people need any insights on my experience regarding physical web, I ll be happy to share

**Comment by cco3** [comment]
Hi Abishek,
Discussion like this is best held at
https://groups.google.com/d/forum/physical-web-discuss

The issue tracker is best for specific issues in the prototype app.
Thanks!
