### ISSUE TITLE
Google Nearby has stopped working

### ISSUE THREAD

**Issue by firecast** [google/physical-web#936]
Since Friday 9th March Google Nearby has stopped working. Neither do you get any notifications nor does the Nearby app show any content. We have customers across the globe who are reporting the same issue. 

Just to rule out issue mentioned from content policies as reported [here](https://github.com/google/eddystone/issues/226), we added a new beacon in a completely different account and attached a nearby notification to it. This also did not show up.

We've tested it on multiple devices with various OS versions. 

Can someone confirm if there is some issue with Nearby Notifications or is it just us who are facing this.

P.S. We started seeing this issue the same time google cloud functions reported its 4hr outage.

**Comment by ferencbrachmann** [comment]
@firecast Have you tried other URLs than from your own systems? Our customers have not reported any issues and we have no issues on our test devices either.

**Comment by firecast** [comment]
@ferencbrachmann We tried putting URL's which are not associated with our systems like wikipedia.com on the nearby notification attachment but still there seems to be no content for the beacon. Can you try clearing the cache of the Nearby app and testing again.

Out of the 20 devices we tested this on there is just one device that shows nearby content for al the beacons in the proximity. I know that the nearby notification is known to be inconsistent but we have never seen this kind of inconsistency.

**Comment by ferencbrachmann** [comment]
@firecast It's not a cache issue on our end for sure. Could it be the case that the domain was blacklisted/flagged by Google for spam for example?

**Comment by firecast** [comment]
@ferencbrachmann We did test that scenario by adding a completely new beacon on the Beacon dashboard for a new project and were still unable to see the notification on our test devices. We added a generic URL there as well not associated with our domain.

**Comment by ferencbrachmann** [comment]
@firecast Are you using Google Beacon dashboard or Eddystone URL?

**Comment by firecast** [comment]
@ferencbrachmann All our beacons are registered on the Google Dashboard for Nearby for their Eddystone UID. However, the beacons also broadcast the URL packets (Physical Web/Eddystone URL). 

Funny thing is that the Nearby app which generally shows content of both the Physical Web and Nearby is not showing for any.

**Comment by chiphysler** [comment]
Yes, since March 1st Google Nearby has been up and down.  In any case, only a faction of beacons are being seen with Nearby.   Saturday, 0% detection, and today I heard only a 3rd of beacons are being seen. 

After talking with numerous customers and other Beacon related vendors, Google is affecting Nearby users dramatically.   I even hear that they are having issues with their own Pixel 2 smartphone in detecting Nearby too.  Not sure if the Google folks monitor github, but it would be good to hear from Google regarding Nearby and beacon issues.

**Comment by ferencbrachmann** [comment]
I suggest you file a Nearby Bug Report here: https://github.com/google/physical-web/wiki/Taking-a-Nearby-Bug-Report

**Comment by firecast** [comment]
We got a response from nearby engineers and they have now fixed the issue. We are able to see nearby content as expected.

> Thanks for the bug report, it helped us nail down an issue triggered in the presence of an invalid URL beacon (ex: a non-HTTPS page) in the proximity of other valid beacons. This bug was included in a software rollout last week, and the fix should already be live. Since the bug only manifested with multiple beacons, with one in an invalid configuration, the impact was likely limited.

**Comment by wfive5** [comment]
I know this issue is closed but I am checking in as all our beacons are down and not found in nearby app at all. I have even set up a new dashboard and created a new project and new beacons with still nothing found. Has anyone else noticed this?

Google Nearby has stopped working. Neither do you get any notifications nor does the Nearby app show any content.

**Comment by Zimbu98** [comment]
https://www.androidpolice.com/2018/10/26/google-shuts-nearby-notifications-due-much-spam/

**Comment by wfive5** [comment]
Thanks for news: OK, we are using beacons in an art gallery to direct users to a video of the art installation that 100% of all users have loved the experience. Is there ANY other way of doing this with beacons and users NOT having to have to install an app first? We were using a 40 character message to inform them of the video and a ssl link. the video then took them on a journey of how the art piece was created... (We tried a custom app install and NO one wanted to install an app first...)

At the end of that android police announcement it stated:
However, this is not the end for Nearby. The API still has two other aspects with Messages and Connections, so if you're a developer invested in creating experiences that rely on those, you're in the clear.

Is anyone familiar with "Messages" or Connections"? Perhaps there is a way to enable our beacons for this?

**Comment by Zimbu98** [comment]
Nope. All other options require a special app install.

**Comment by wfive5** [comment]
Is there perhaps still an ibeacon option where only a URL link is displayed?

Or perhaps an Apple iPhone ibeacon option?

Any beacon with no pre-installed app option?

**Comment by Zimbu98** [comment]
Haha, you never give up! But, believe me, I know how you feel.

Sorry, the answer is still no. No other options that don’t require an app install. Zero. Zilch.

**Comment by RyanDool** [comment]
I am with Zimbu98.  Sorry to say, without an app install I cannot think of a way to accomplish your needs with ble tech... given the recent/current state of android/ios support.

**Comment by wfive5** [comment]
What about with this?
https://developers.google.com/nearby/connections/overview 
or this:
https://developers.google.com/nearby/messages/overview

**Comment by Zimbu98** [comment]
Oh, right! Yes, you can totally do both of those things. Just build your own app, incorporate those api's into your app, then get your visitors to download your app. Viola! ;-)

**Comment by wfive5** [comment]
We already built the gallery an app for this and ZERO downloads in 6 months. This is why we went with Nearby notifications, Once setup they had 50 views a day from the beacons with a very positive response... So NO an app is not an option... 8-(

Hoping anyone else can chime in... perhaps a way for the beacon to interact with any other pre-installed android app?

**Comment by Zimbu98** [comment]
But seriously, the only way I can suggest for you to get what you want is to offer your visitors some sort of hardware device (think of it as a really simple smartphone, so obviously you would need them to leave a deposit of some kind, or perhaps you could have a security system at the door that would prevent them from taking it away with them). 

Maybe one of those super cheap tablets would do the trick (no brandname, purchased direct from China). In this case, I would not even bother using beacons. Just have a menu on the tablet screen with different choices for each exhibit. When the visitor gets to exhibit A, they would tap A on the tablet and see a video or info about exhibit A. Tablet would not need bluetooth but would probably need wifi to download the content.

**Comment by Zimbu98** [comment]
Keep in mind, this is a WORLDWIDE decision from Google; there are millions of people effected and at least hundreds of companies basically put out of business overnight. If there was an option like you are hoping for, it would be worldwide news. There  is  no  option.

**Comment by RyanDool** [comment]
You could wait/hope for native mobile browser to better support the Web Bluetooth API (https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API).
