### ISSUE TITLE
Nearby Notifications stopped working since 1.July

### ISSUE THREAD

**Issue by fdietz** [google/physical-web#942]
Hi all,

first of all sorry for posting this here, but the "official Nearby mailing list" (https://groups.google.com/forum/#!forum/google-context-apis/join) as linked on https://developers.google.com/nearby/ is not available anymore it seems.

Since 1. July our Nearby Notifications are not being delivered anymore. Physical Web Notifications still work though.

We can still see that the Google Indexer is making requests to our destination URLs, but no Nearby notifications appear on our phones.

We haven't changed anything from our side and suspect a change from Google.

Has anyone noticed the same behaviour? 

If this is not the right place to ask these questions, can you please forward me to a more appropriate channel instead? 

Thanks in advance,
-Frederik Dietz

CTO - nrbyXmedia GmbH

**Comment by ferencbrachmann** [comment]
Dear Frederik, please submit your bug report here: https://github.com/google/physical-web/wiki/Taking-a-Nearby-Bug-Report

**Comment by pm4u2018** [comment]
If the notification works in debug mode then what does that mean?

**Comment by fdietz** [comment]
Thanks @ferencbrachmann! 

I have some good news: Notifications work again! 

But, it is sad that they stopped working for 3 days with no information why. 

And again: We didn't change anything from our side. We use Google's Nearby App only.

Has anyone here had similar experiences? What did you did in this case? Would it still make sense to open a bug report?

**Comment by ferencbrachmann** [comment]
@fdietz Things like this are sometimes reported but are isolated as far as I remember. You really should consult with the Nearby people as it could easily have been an isolated issue in Europe / Germany or only connected to your account. We got no reports from our customers but 99% of them use Eddystone-URL that had no issues.

**Comment by fdietz** [comment]
Thank you so much. Will do that!
