### ISSUE TITLE
Security Vulnerability Disclosure 

### ISSUE THREAD

**Issue by indianamoreau** [google/physical-web#957]
Hi,

I have found a high-risk security vulnerability which may result in remote code injection in this project. Who can I contact to responsibly disclose it?

Thanks,
Indiana Moreau

**Comment by bradmurray** [comment]
The project is dead and the service is discontinued by google so I wouldn't expect anybody to fix anything.

**Comment by indianamoreau** [comment]
Closing as I've received no answer.
