### ISSUE TITLE
URL physical-web.org can't be reached

### ISSUE THREAD

**Issue by al3xt96** [google/physical-web#958]
When opening URL in About Description in GitHub repository the website can't be reached

http://physical-web.org/ 

Is the website no longer in use and we can rely on documentation instead ?

**Comment by mmocny** [comment]
I'm not sure when/why the domain went down, but the site has not been updated for years.  The project is not maintained by the original authors, though I do believe there are other developers who maintain alternate clients.

**Comment by scottjenson** [comment]
The project was cancelled years ago so the domains stopped being updated
this year.

**Comment by al3xt96** [comment]
Thank you for info. 
@mmocny  I see now, there is still documentation left here as a reference, so in this case should I close this issue considering the project is no longer maintained by the original authors ?

@scottjenson  So in general case regarding open-source projects repositories are left for other developers to maintain even though they are not maintained by the original authors ?
